"""Additional unique Science 30 questions for production pool expansion."""

from .helpers import mc, nr

TOPIC_CIRC = "Circulatory and Immune Systems"
TOPIC_GEN = "Genetics and Molecular Biology"
TOPIC_CHEM = "Environmental Chemistry"
TOPIC_FIELD = "Field Theory and Electrical Energy"
TOPIC_EMR = "Electromagnetic Spectrum"
TOPIC_ENERGY = "Energy and the Environment"


def expansion() -> list[dict]:
    """Return ~120 unique questions with distinct stems and skills."""
    items = []

    circ = [
        ("Which vessel carries deoxygenated blood from the right ventricle to the lungs?",
         "pulmonary artery", ["pulmonary vein (oxygenated return)", "aorta (systemic artery)", "vena cava (systemic return)"],
         "The right ventricle pumps blood through pulmonary arteries to the lungs for oxygenation.",
         "Students confuse pulmonary arteries (to lungs) with pulmonary veins (from lungs).",
         "A1.2k", "Tracing deoxygenated blood path to lungs", "Easy", 60),
        ("Lymphocytes that produce antibodies upon activation are",
         "B lymphocytes (B cells)", ["red blood cells (oxygen transport)", "platelets (clot formation)", "neutrophils (phagocytosis only)"],
         "B cells differentiate into plasma cells that secrete antigen-specific antibodies.",
         "Students confuse antibody-producing B cells with T cells or phagocytes.",
         "A2.3k", "Identifying B lymphocyte antibody production role", "Medium", 80),
        ("The spleen functions in immunity primarily by",
         "filtering blood and initiating immune responses to blood-borne pathogens",
         ["pumping blood to the lungs for gas exchange", "producing digestive enzymes for fat breakdown", "storing bone marrow stem cells exclusively"],
         "The spleen filters blood, removes old RBCs, and mounts immune responses.",
         "Students confuse spleen function with heart pumping or digestive organs.",
         "A2.2k", "Describing spleen role in blood filtration and immunity", "Medium", 75),
        ("Histamine release during an allergic reaction causes",
         "vasodilation and increased capillary permeability leading to swelling",
         ["immediate destruction of all pathogens systemically", "permanent closure of all blood vessels", "conversion of hemoglobin to fibrinogen"],
         "Histamine dilates vessels and increases permeability, producing inflammation and swelling.",
         "Students think histamine directly kills all pathogens or converts blood proteins.",
         "A2.4k", "Explaining histamine role in allergic inflammation", "Medium", 80),
        ("Passive immunity differs from active immunity because passive immunity",
         "provides temporary antibodies without stimulating the recipient's immune memory",
         ["requires a live pathogen infection in the recipient", "creates permanent memory cells in all cases", "only works through vaccination with weakened virus"],
         "Passive immunity transfers pre-made antibodies (e.g., maternal or antiserum) without memory formation.",
         "Students confuse passive antibody transfer with active vaccination-induced memory.",
         "A2.5k", "Distinguishing passive from active immunity", "Medium", 85),
        ("The tricuspid valve prevents backflow of blood from the",
         "right ventricle into the right atrium during ventricular contraction",
         ["left ventricle into the left atrium during contraction", "aorta into the left ventricle during relaxation", "pulmonary vein into the left atrium during filling"],
         "The tricuspid valve sits between right atrium and right ventricle.",
         "Students name the mitral or aortic valve instead of the right-side tricuspid valve.",
         "A1.1k", "Identifying tricuspid valve location and function", "Easy", 70),
        ("Erythropoietin stimulates",
         "red blood cell production in bone marrow", ["white blood cell apoptosis in the spleen", "platelet destruction in the liver", "antibody secretion by plasma cells directly"],
         "EPO is a hormone that increases erythrocyte production when oxygen demand rises.",
         "Students confuse EPO with platelet or white cell regulation.",
         "A1.4k", "Describing erythropoietin effect on RBC production", "Medium", 80),
        ("Septic shock can result when",
         "widespread infection triggers dangerous systemic inflammation and vasodilation",
         ["a single papercut heals without any immune response", "vaccination creates memory B cells only", "exercise temporarily elevates heart rate slightly"],
         "Severe infection can cause systemic inflammatory response leading to dangerously low blood pressure.",
         "Students confuse mild localized injury with systemic septic inflammatory cascade.",
         "A2.4k", "Describing septic shock as systemic immune overreaction", "Hard", 90),
        ("The lymphatic system returns excess interstitial fluid to",
         "the bloodstream via lymphatic vessels and ducts", ["the digestive tract for reabsorption as nutrients", "the alveoli for gas exchange directly", "the renal tubules as concentrated urine only"],
         "Lymphatic capillaries collect interstitial fluid and return it to venous circulation.",
         "Students think lymph drains to lungs or kidneys rather than blood circulation.",
         "A1.3k", "Describing lymphatic fluid return to circulation", "Medium", 75),
        ("Cytotoxic T cells destroy infected cells primarily by",
         "releasing perforin and granzymes to induce target cell apoptosis",
         ["secreting antibodies that bind free viruses in plasma", "engulfing pathogens through phagocytosis like macrophages", "producing red blood cells in bone marrow"],
         "Cytotoxic T cells induce apoptosis in virus-infected or abnormal cells via perforin/granzyme.",
         "Students attribute phagocytosis or antibody secretion to cytotoxic T cells.",
         "A2.3k", "Explaining cytotoxic T cell killing mechanism", "Hard", 95),
        ("Blood typing compatibility for transfusion depends on",
         "matching ABO antigens and Rh factor to prevent agglutination",
         ["matching only white blood cell count between donor and recipient", "ensuring identical platelet shape in both individuals", "using only O-negative blood for every patient always"],
         "Incompatible antigens cause recipient antibodies to agglutinate donor RBCs.",
         "Students think any blood type can receive any other type safely.",
         "A1.4s", "Applying ABO/Rh compatibility rules for transfusion", "Medium", 85),
        ("Atherosclerosis increases heart attack risk because",
         "plaque narrows arteries and can rupture to form clots blocking coronary flow",
         ["it increases oxygen content of blood dramatically", "it converts arteries into veins structurally", "it eliminates all need for platelets in clotting"],
         "Coronary plaque buildup reduces blood flow; rupture can cause thrombosis and myocardial infarction.",
         "Students think atherosclerosis improves oxygen delivery or removes clotting ability.",
         "A1.1sts", "Analyzing atherosclerosis cardiovascular risk", "Medium", 90),
        ("Fever during infection helps the immune response by",
         "increasing metabolic rate and inhibiting some pathogen growth",
         ["eliminating all bacteria within minutes without immune cells", "permanently raising body temperature above 42°C always", "preventing any inflammation from occurring"],
         "Moderate fever supports immune function though very high fever is dangerous.",
         "Students think fever alone instantly cures infection or always prevents inflammation.",
         "A2.1k", "Explaining fever as non-specific immune response", "Easy", 70),
        ("The hepatic portal vein carries blood from the",
         "digestive organs to the liver for processing", ["lungs to the left atrium for oxygenation", "left ventricle to the body tissues", "kidneys to the bladder for filtration"],
         "Portal circulation routes nutrient-rich blood from gut to liver before systemic return.",
         "Students confuse portal vein with pulmonary or systemic arterial pathways.",
         "A1.2k", "Tracing hepatic portal circulation pathway", "Medium", 80),
        ("Anaphylaxis is a life-threatening reaction involving",
         "rapid systemic allergic response with airway constriction and hypotension",
         ["slow localized redness at a single mosquito bite only", "gradual increase in red blood cell count over months", "permanent immunity to all future allergens instantly"],
         "Anaphylaxis is severe, rapid, whole-body hypersensitivity requiring emergency treatment.",
         "Students confuse mild local allergy with systemic anaphylactic emergency.",
         "A2.4k", "Defining anaphylaxis as severe systemic allergy", "Hard", 90),
        ("The role of interferons in viral infection is to",
         "signal neighbouring cells to produce antiviral proteins", ["directly digest viral capsids inside red blood cells", "convert viruses into beneficial bacteria", "permanently eliminate all viruses from the planet"],
         "Interferons are cytokines that induce antiviral state in uninfected neighbouring cells.",
         "Students think interferons physically destroy viruses inside erythrocytes.",
         "A2.2k", "Describing interferon antiviral signalling role", "Medium", 85),
        ("Capillary exchange of oxygen occurs primarily by",
         "diffusion down the concentration gradient from blood to tissues",
         ["active transport requiring ATP in every red blood cell membrane", "osmosis of oxygen through the heart valves", "gravitational settling of oxygen to the feet only"],
         "O₂ diffuses from high partial pressure in capillary blood to lower pressure in tissues.",
         "Students think oxygen requires active transport or osmosis through heart valves.",
         "A1.3s", "Explaining oxygen diffusion at capillary beds", "Medium", 80),
        ("A person with Type O blood has",
         "anti-A and anti-B antibodies in plasma but no A or B antigens on RBCs",
         ["both A and B antigens on red blood cells", "no antibodies of any kind in plasma", "only Rh antigen with no other blood proteins"],
         "Type O lacks A/B antigens; plasma contains antibodies against A and B.",
         "Students think Type O has both antigens or no antibodies in plasma.",
         "A1.4k", "Identifying Type O blood antigen and antibody profile", "Medium", 75),
        ("Granulocytes such as neutrophils are classified as",
         "phagocytic white blood cells in innate immunity", ["oxygen-carrying cells in pulmonary circulation", "structural proteins in the blood clot mesh", "hormones regulating heart rate exclusively"],
         "Neutrophils are granulocytes that engulf pathogens during innate immune response.",
         "Students confuse granulocytes with erythrocytes or clotting proteins.",
         "A2.2k", "Classifying neutrophils as innate phagocytes", "Easy", 65),
        ("Blood doping with EPO is banned in sport because it",
         "artificially increases oxygen-carrying capacity giving unfair endurance advantage",
         ["decreases red blood cell count below safe levels", "eliminates all lactic acid from muscles permanently", "converts muscle tissue into bone marrow directly"],
         "EPO raises hematocrit, enhancing oxygen delivery and endurance performance.",
         "Students think EPO reduces RBC count or removes lactic acid entirely.",
         "A1.1sts", "Evaluating ethical issues of blood doping with EPO", "Medium", 90),
    ]

    gen = [
        ("The central dogma of molecular biology describes flow of information from",
         "DNA to RNA to protein", ["protein to RNA to DNA in all cells always", "RNA to DNA to lipid in every organism", "protein to DNA without any RNA intermediate ever"],
         "Information flows DNA → RNA (transcription) → protein (translation) in standard cells.",
         "Students reverse the central dogma direction or omit the RNA step.",
         "A3.1k", "Stating central dogma information flow", "Easy", 60),
        ("A frameshift mutation is particularly harmful because it",
         "shifts the reading frame altering all downstream codons", ["changes only a single amino acid with no other effect", "removes the cell membrane without touching DNA", "converts introns into functional ribosomes directly"],
         "Insertions/deletions not in multiples of three shift codon grouping downstream.",
         "Students think frameshift affects only one codon like a point mutation.",
         "A3.5k", "Explaining frameshift mutation reading frame effect", "Hard", 95),
        ("PCR (polymerase chain reaction) amplifies DNA by",
         "repeated cycles of denaturation, primer annealing, and extension", ["digesting DNA with restriction enzymes once only", "translating mRNA into protein in a test tube", "combining chromosomes through meiotic crossing over in vitro"],
         "PCR uses thermal cycling and DNA polymerase to exponentially copy a target sequence.",
         "Students confuse PCR with protein synthesis or meiotic recombination.",
         "A3.10k", "Describing PCR thermal cycle amplification steps", "Medium", 85),
        ("A heterozygous individual for a recessive disorder",
         "carries one mutant allele but typically shows no disease symptoms", ["always expresses severe disease phenotype", "has no alleles for that gene at all", "cannot pass any allele to offspring ever"],
         "Recessive disorders require two mutant alleles; carriers have one copy and are usually unaffected.",
         "Students think one recessive allele always causes full disease expression.",
         "A3.3k", "Defining heterozygous carrier status for recessive traits", "Easy", 70),
        ("Gel electrophoresis separates DNA fragments by",
         "size as they migrate through an agarose gel in an electric field", ["color of the nitrogenous bases only", "number of chromosomes in the cell nucleus", "protein folding patterns in the cytoplasm"],
         "Smaller DNA fragments move faster/farther through gel pores under applied voltage.",
         "Students think electrophoresis sorts by base color or chromosome count.",
         "A3.8k", "Explaining DNA gel electrophoresis size separation", "Medium", 85),
        ("A test cross (heterozygote × homozygous recessive) reveals",
         "the unknown genotype by examining offspring phenotypic ratios", ["the exact DNA sequence of every chromosome", "the age of the organism in years", "the blood type of unrelated individuals"],
         "Offspring ratios from test cross indicate whether parent was homozygous or heterozygous dominant.",
         "Students think test cross sequences entire genome or measures age.",
         "A3.2s", "Applying test cross to determine unknown genotype", "Medium", 90),
        ("Epigenetic changes differ from mutations because epigenetics",
         "alters gene expression without changing the DNA nucleotide sequence", ["permanently deletes entire chromosomes from the nucleus", "converts DNA into RNA irreversibly in all cells", "only occurs in bacteria with no effect in eukaryotes"],
         "Epigenetic marks (e.g., methylation) regulate expression while base sequence stays same.",
         "Students think epigenetics changes nucleotide sequence like point mutations.",
         "A3.7k", "Distinguishing epigenetic regulation from DNA mutation", "Hard", 95),
        ("The anticodon on a tRNA molecule",
         "base-pairs with the complementary mRNA codon during translation", ["forms hydrogen bonds with DNA during replication only", "attaches to ribosomal RNA to start transcription", "codes for three amino acids simultaneously"],
         "Each tRNA anticodon recognizes a specific mRNA codon at the ribosome A site.",
         "Students confuse anticodon function with DNA replication or transcription start.",
         "A3.6k", "Describing tRNA anticodon pairing during translation", "Medium", 80),
        ("Sickle cell anemia results from",
         "a point mutation in the beta-globin gene altering hemoglobin shape", ["deletion of an entire chromosome 21 set", "bacterial transformation in red blood cells", "excessive white blood cell production in marrow"],
         "A single nucleotide substitution in HBB gene produces abnormal hemoglobin S.",
         "Students attribute sickle cell to whole chromosome loss or bacterial infection.",
         "A3.5k", "Linking sickle cell to beta-globin point mutation", "Medium", 85),
        ("Gene therapy aims to",
         "introduce functional genetic material to treat or prevent disease", ["eliminate all DNA from patient cells permanently", "convert all recessive alleles to dominant in one treatment", "replace vaccines with antibiotics for viral infections only"],
         "Gene therapy delivers corrected genes or regulatory elements to affected cells.",
         "Students think gene therapy removes all DNA or replaces all vaccination.",
         "A3.9k", "Defining gene therapy therapeutic goal", "Medium", 85),
        ("A karyotype displays",
         "the number and appearance of chromosomes in a cell", ["the sequence of every amino acid in hemoglobin", "the rate of blood flow through the aorta", "the concentration of ozone in the stratosphere"],
         "Karyotyping arranges chromosomes to detect aneuploidy and structural abnormalities.",
         "Students confuse karyotype with protein sequencing or atmospheric chemistry.",
         "A3.4k", "Defining karyotype as chromosome visualization", "Easy", 65),
        ("Stem cells are valuable in medicine because they",
         "can differentiate into specialized cell types for repair or research", ["cannot divide and remain permanently frozen", "only produce red blood cells with no other potential", "eliminate the need for any immune system function"],
         "Pluripotent and multipotent stem cells can develop into various tissues.",
         "Students think stem cells are non-dividing or only make erythrocytes.",
         "A3.9k", "Explaining stem cell differentiation potential in medicine", "Medium", 80),
        ("A nonsense mutation introduces",
         "a premature stop codon truncating the protein", ["a new start codon at the beginning of every intron", "extra chromosomes into the diploid set", "a permanent double-strand break repaired by photosynthesis"],
         "Nonsense mutations create stop codons early, producing shortened nonfunctional proteins.",
         "Students confuse nonsense (stop) mutations with silent or missense changes.",
         "A3.5k", "Defining nonsense mutation premature stop effect", "Hard", 90),
        ("CRISPR-Cas9 technology is used to",
         "target and edit specific DNA sequences in the genome", ["amplify RNA without touching DNA at all", "measure blood pressure in the pulmonary circuit", "filter acid rain from industrial smokestacks"],
         "CRISPR guides Cas9 nuclease to a specific genomic site for precise editing.",
         "Students confuse CRISPR gene editing with PCR amplification or pollution control.",
         "A3.10k", "Describing CRISPR-Cas9 targeted genome editing", "Hard", 100),
        ("Down syndrome (trisomy 21) is detected by observing",
         "three copies of chromosome 21 in a karyotype", ["elevated hemoglobin in a complete blood count only", "low platelet count on a clotting assay only", "absence of all sex chromosomes in every cell"],
         "Trisomy 21 means three copies of chromosome 21; visible on karyotype analysis.",
         "Students diagnose trisomy 21 from blood chemistry without chromosome analysis.",
         "A3.4s", "Identifying trisomy 21 from karyotype evidence", "Medium", 85),
        ("A silent mutation",
         "changes a codon but does not alter the encoded amino acid", ["stops translation at the first codon always", "deletes an entire chromosome arm", "converts DNA polymerase into RNA polymerase"],
         "Degenerate genetic code allows some nucleotide changes without amino acid change.",
         "Students think any nucleotide change must change the protein sequence.",
         "A3.5k", "Defining silent mutation codon redundancy effect", "Medium", 80),
        ("Meiosis produces gametes with",
         "half the chromosome number of the parent body cell", ["twice the chromosome number of the parent cell", "identical diploid copies with no variation", "no genetic material in the nucleus at all"],
         "Meiosis reduces 2n to n through two divisions including homologous separation.",
         "Students think meiosis doubles chromosome number or produces identical diploid cells.",
         "A3.2k", "Stating meiosis chromosome number reduction", "Easy", 65),
        ("In a pedigree, a recessive X-linked trait most often appears in",
         "males who inherit the mutant allele from carrier mothers",
         ["females who always inherit two Y chromosomes", "males who inherit the allele only from fathers", "all offspring equally regardless of sex chromosome"],
         "Males (XY) express X-linked recessive traits with one mutant allele; females need two copies.",
         "Students think X-linked recessive affects both sexes equally or passes father-to-son on X.",
         "A3.3s", "Interpreting X-linked recessive pedigree pattern", "Hard", 95),
        ("Reverse transcriptase in retroviruses",
         "synthesizes DNA from an RNA template", ["translates proteins directly without any nucleic acid", "replicates only host cell ribosomes", "converts glucose to ATP in the viral capsid"],
         "Retroviruses use reverse transcriptase to make DNA from viral RNA genome.",
         "Students think reverse transcriptase translates protein or metabolizes glucose.",
         "A3.4k", "Describing reverse transcriptase RNA-to-DNA synthesis", "Hard", 90),
        ("A dihybrid cross studies inheritance of",
         "two traits determined by genes on different chromosome pairs", ["one trait on the Y chromosome only", "mitochondrial DNA with no nuclear involvement", "blood pressure and heart rate as single alleles"],
         "Dihybrid crosses track two independently assorting gene pairs (e.g., AaBb × AaBb).",
         "Students confuse dihybrid with single-trait or mitochondrial inheritance.",
         "A3.2k", "Defining dihybrid cross two-trait inheritance", "Medium", 85),
    ]

    chem = [
        ("The pH scale is logarithmic, so a decrease of one pH unit represents",
         "a tenfold increase in hydronium ion concentration", ["a tenfold decrease in hydronium ion concentration", "no change in hydronium ion concentration", "a doubling of hydroxide ion concentration only"],
         "Each pH unit change is a factor of 10 in [H₃O⁺]; lower pH means higher acidity.",
         "Students think lower pH means less acid or that pH change is linear not logarithmic.",
         "B1.3k", "Interpreting logarithmic pH concentration change", "Medium", 80),
        ("Hard water contains elevated concentrations of",
         "calcium and magnesium ions", ["sodium chloride from ocean evaporation only", "pure ozone dissolved as a liquid", "radioactive carbon-14 exclusively"],
         "Ca²⁺ and Mg²⁺ ions cause soap scum and scale; common in groundwater.",
         "Students confuse hard water minerals with table salt or ozone.",
         "B1.6k", "Identifying calcium and magnesium in hard water", "Easy", 60),
        ("The greenhouse effect is enhanced when atmospheric concentrations of CO₂ and CH₄",
         "increase infrared absorption and re-radiation toward Earth's surface", ["decrease all infrared absorption to zero", "reflect all incoming solar UV before it reaches Earth", "eliminate convection in the troposphere completely"],
         "More greenhouse gases trap additional outgoing IR, warming the lower atmosphere.",
         "Students think greenhouse gases reflect incoming UV or stop all convection.",
         "B2.3k", "Explaining enhanced greenhouse effect mechanism", "Medium", 80),
        ("Primary air pollutants are emitted",
         "directly from sources such as vehicles and industry", ["only after chemical reactions in the atmosphere", "exclusively from natural lightning with no human source", "only as secondary products of ozone formation"],
         "Primary pollutants (e.g., CO, NOₓ, particulates) come straight from combustion sources.",
         "Students confuse primary direct emissions with secondary atmospheric reaction products.",
         "B1.8k", "Distinguishing primary from secondary air pollutants", "Medium", 75),
        ("A buffer solution resists pH change because it contains",
         "a weak acid and its conjugate base (or weak base and conjugate acid)", ["only a strong acid at very high concentration", "only distilled water with no dissolved ions", "a strong base that fully ionizes at all times"],
         "Buffers use equilibrium between weak acid/base pair to neutralize added H⁺ or OH⁻.",
         "Students think strong acid alone or pure water buffers pH changes.",
         "B1.4k", "Describing buffer weak acid-conjugate base composition", "Medium", 85),
        ("Eutrophication of a lake is accelerated by",
         "excess nitrogen and phosphorus nutrients promoting algal blooms", ["reduced sunlight from mountain shadows only", "decrease in all dissolved gases permanently", "removal of all carbon dioxide from the atmosphere"],
         "Nutrient runoff causes algal overgrowth, oxygen depletion, and ecosystem disruption.",
         "Students attribute eutrophication to shading or global CO₂ removal.",
         "B2.4k", "Explaining nutrient-driven eutrophication process", "Medium", 80),
        ("The ozone layer primarily protects life by absorbing",
         "high-energy ultraviolet radiation from the Sun", ["all infrared radiation from Earth's surface", "visible light wavelengths between 500 and 600 nm", "radio waves from communication satellites"],
         "Stratospheric O₃ absorbs UV-B and UV-C, reducing DNA damage at Earth's surface.",
         "Students think ozone absorbs IR or visible light rather than UV.",
         "B2.5k", "Describing stratospheric ozone UV protection role", "Easy", 65),
        ("Heavy metal contamination in water such as lead is dangerous because",
         "lead accumulates in tissues and interferes with neurological development", ["lead increases dissolved oxygen benefiting all fish", "lead neutralizes all acids raising pH above 14 instantly", "lead converts all organic matter to harmless nitrogen gas"],
         "Lead is toxic, persistent, and bioaccumulates, especially harming nervous system function.",
         "Students think heavy metals improve water quality or neutralize all acidity.",
         "B2.3k", "Explaining lead bioaccumulation health risk", "Medium", 85),
        ("Thermal pollution from industrial cooling water can harm aquatic ecosystems by",
         "reducing dissolved oxygen solubility and altering species temperature ranges", ["increasing dissolved oxygen at all temperatures linearly", "converting all water to ice regardless of season", "eliminating all bacteria beneficial and harmful instantly"],
         "Warmer water holds less O₂; species adapted to specific temperatures may decline.",
         "Students think heating water always increases dissolved oxygen for fish.",
         "B2.4k", "Analyzing thermal pollution aquatic ecosystem impact", "Medium", 85),
        ("Acid rain with pH below 5.6 can damage forests by",
         "leaching essential nutrients and releasing toxic aluminum from soil", ["increasing soil pH above 10 in all regions", "adding nitrogen fertilizer beneficial to all trees", "converting all CO₂ in leaves to oxygen gas instantly"],
         "Acid deposition mobilizes toxic metals and removes Ca²⁺, Mg²⁺ from soil.",
         "Students think acid rain fertilizes forests or raises soil pH dramatically.",
         "B1.8k", "Describing acid rain forest and soil damage", "Medium", 85),
        ("Nanotechnology in environmental applications may use nanoparticles to",
         "detect or remediate pollutants at very small scales", ["eliminate all laws of thermodynamics in reactors", "convert all fossil fuels to gold metal", "remove gravity from contaminated sites"],
         "Nanomaterials offer high surface-area reactivity for sensing and cleanup applications.",
         "Students think nanotechnology violates physics or transmutes elements.",
         "B3.3k", "Describing nanotechnology environmental remediation potential", "Hard", 90),
        ("The nitrogen cycle includes bacterial nitrogen fixation which",
         "converts atmospheric N₂ into ammonia usable by plants", ["converts all ammonia back to N₂ gas in one step only", "produces stratospheric ozone from nitrogen exclusively", "eliminates all nitrate from ocean water permanently"],
         "Nitrogen-fixing bacteria reduce N₂ to NH₃/NH₄⁺, making nitrogen available to ecosystems.",
         "Students think fixation releases N₂ or creates ozone from nitrogen alone.",
         "B2.2k", "Describing bacterial nitrogen fixation in nitrogen cycle", "Medium", 80),
        ("A carbon footprint measures",
         "total greenhouse gas emissions caused by an activity or entity", ["only the mass of carbon soot on a filter paper", "the number of trees in a national park only", "the voltage of a solar panel at noon only"],
         "Carbon footprint quantifies CO₂-equivalent emissions from energy, transport, products, etc.",
         "Students equate carbon footprint with visible soot mass or tree count alone.",
         "B2.1sts", "Defining carbon footprint as emission measure", "Easy", 70),
        ("Phytoremediation uses plants to",
         "absorb, stabilize, or degrade contaminants in soil or water", ["generate nuclear power in root mitochondria", "eliminate all need for the nitrogen cycle globally", "convert all heavy metals to plastic polymers"],
         "Certain plants hyperaccumulate or metabolize pollutants, aiding site cleanup.",
         "Students think phytoremediation produces nuclear energy or replaces biogeochemical cycles.",
         "B3.3k", "Defining phytoremediation plant-based cleanup", "Medium", 80),
        ("Dissolved oxygen in a healthy stream is typically",
         "higher than in a stagnant eutrophic pond", ["zero in all moving water bodies", "higher in warm stagnant ponds than cold streams", "unrelated to temperature or biological activity"],
         "Aeration and lower temperatures in streams maintain higher dissolved O₂ levels.",
         "Students think stagnant warm water always has more oxygen than cold flowing streams.",
         "B2.4s", "Comparing dissolved oxygen in stream vs eutrophic pond", "Medium", 75),
        ("Limestone (calcium carbonate) can neutralize acid rain in soil because it",
         "reacts with H⁺ ions forming soluble calcium salts and water", ["releases additional sulfur dioxide into groundwater", "decreases pH further by adding more acid", "converts all soil nitrogen to unreactive N₂ gas instantly"],
         "CaCO₃ + 2H⁺ → Ca²⁺ + CO₂ + H₂O helps buffer acidic deposition effects.",
         "Students think limestone adds acid or releases SO₂ when neutralizing.",
         "B1.7k", "Explaining limestone acid neutralization in soil", "Medium", 80),
        ("Volatile organic compounds (VOCs) contribute to smog because they",
         "react in sunlight with NOₓ to form ground-level ozone and oxidants", ["absorb all oxygen from the atmosphere permanently", "increase stratospheric ozone uniformly worldwide", "precipitate as solid sulfuric acid rain only"],
         "VOCs participate in photochemical reactions producing tropospheric ozone in smog.",
         "Students think VOCs deplete all atmospheric oxygen or only form acid rain.",
         "B1.8k", "Explaining VOC role in photochemical smog formation", "Medium", 85),
        ("An exothermic neutralization reaction between acid and base",
         "releases heat as H⁺ and OH⁻ form water", ["absorbs large amounts of heat cooling to below 0°C always", "produces only gaseous hydrogen without any liquid", "requires no water formation at any stage"],
         "H⁺(aq) + OH⁻(aq) → H₂O(l) is exothermic, warming the mixture.",
         "Students think neutralization always absorbs heat or produces only H₂ gas.",
         "B1.2s", "Describing exothermic acid-base neutralization enthalpy", "Medium", 80),
        ("Persistent organic pollutants (POPs) are problematic because they",
         "resist degradation and bioaccumulate in food chains", ["dissolve instantly in rainwater and disappear", "convert to harmless oxygen gas within hours", "only affect abiotic rocks with no biological uptake"],
         "POPs like DDT/PCBs persist, biomagnify, and cause long-term ecological harm.",
         "Students think POPs break down rapidly or only affect non-living matter.",
         "B2.3k", "Explaining POP persistence and bioaccumulation risk", "Medium", 85),
        ("Greywater recycling in homes reuses",
         "wastewater from sinks and showers for irrigation or flushing", ["all industrial sulfuric acid waste from smelters", "stratospheric ozone for drinking without treatment", "spent nuclear fuel rods for garden fertilizer"],
         "Greywater systems reuse relatively clean household wastewater, reducing freshwater demand.",
         "Students confuse greywater with industrial acid waste or nuclear materials.",
         "B3.2sts", "Describing residential greywater recycling application", "Easy", 70),
    ]

    field = [
        ("Coulomb's law describes the force between two point charges as",
         "inversely proportional to the square of the distance between them", ["directly proportional to distance squared always", "independent of charge magnitude at all distances", "proportional to the cube of distance between charges"],
         "F = kq₁q₂/r²; force decreases rapidly as separation increases.",
         "Students invert the distance relationship or ignore charge magnitude dependence.",
         "C1.1k", "Stating Coulomb inverse-square force relationship", "Medium", 85),
        ("Electric field lines indicate",
         "direction and relative strength of the field around charges", ["exact speed of electrons in a copper wire always", "color of visible light emitted by the charge", "mass of the proton in every nucleus"],
         "Field lines point from + to −; density indicates field strength.",
         "Students think field lines show electron speed or photon color.",
         "C1.2k", "Interpreting electric field line direction and density", "Easy", 65),
        ("Ohm's law states that for an ohmic conductor at constant temperature",
         "current is directly proportional to voltage across the conductor", ["resistance decreases when voltage decreases always", "current is independent of voltage in all materials", "power equals resistance divided by voltage squared"],
         "V = IR; doubling voltage doubles current if R is constant.",
         "Students misapply Ohm's law or confuse P = VI with V/R incorrectly.",
         "C1.3k", "Applying Ohm's law voltage-current proportionality", "Easy", 60),
        ("A fuse protects a household circuit by",
         "melting when current exceeds a safe level, breaking the circuit", ["increasing voltage to all appliances simultaneously", "storing excess charge in a magnetic field permanently", "converting AC to DC without any resistance change"],
         "The fuse element melts from I²R heating when current is too high.",
         "Students think fuses boost voltage or store charge magnetically.",
         "C1.7k", "Explaining fuse overcurrent protection mechanism", "Easy", 65),
        ("Kirchhoff's current law at a junction states that",
         "total current entering equals total current leaving", ["voltage is the same at every point in any circuit", "resistance sums to zero in all parallel branches", "power is always conserved without any heat loss"],
         "Charge conservation: ΣI_in = ΣI_out at any node in a steady circuit.",
         "Students confuse KCL (current) with KVL (voltage loop) or energy loss.",
         "C1.6k", "Applying Kirchhoff current law at circuit junction", "Medium", 85),
        ("A step-down transformer decreases voltage because",
         "the secondary coil has fewer turns than the primary coil", ["the primary coil has fewer turns than the secondary always", "iron core eliminates all magnetic flux entirely", "AC frequency doubles in the secondary winding automatically"],
         "Turns ratio V_s/V_p = N_s/N_p; fewer secondary turns yield lower secondary voltage.",
         "Students reverse turns ratio effect or think core eliminates flux.",
         "C1.10k", "Explaining step-down transformer turns ratio", "Medium", 80),
        ("Magnetic field strength around a long straight current-carrying wire",
         "decreases with increasing distance from the wire", ["increases linearly with distance from the wire", "is zero at all points outside the wire always", "depends only on wire color not current magnitude"],
         "B ∝ I/r for long straight conductor; field weakens with distance.",
         "Students think B increases with distance or depends on wire appearance.",
         "C1.5k", "Describing magnetic field distance dependence for straight wire", "Medium", 80),
        ("Electrical power in a resistor is calculated by",
         "P = VI, also equal to I²R and V²/R", ["P = R/I only for all circuit elements", "P = V + I for any combination of values", "P = IR² for ohmic conductors at all times"],
         "Power dissipated: P = VI = I²R = V²/R in resistive elements.",
         "Students add V and I or use incorrect combinations like P = IR².",
         "C1.3s", "Calculating resistor power using P = VI and I²R", "Medium", 85),
        ("A capacitor stores energy in",
         "the electric field between its plates", ["the magnetic field around a solenoid exclusively", "gravitational potential of electron mass only", "chemical bonds in the dielectric metal plates"],
         "Energy U = ½CV² stored in electric field between charged capacitor plates.",
         "Students think capacitors store energy magnetically or gravitationally.",
         "C1.4k", "Identifying electric field as capacitor energy storage", "Medium", 80),
        ("Electrical grounding in a home safety system",
         "provides a low-resistance path for fault current to earth", ["increases resistance to block all current flow always", "eliminates the need for insulation on all wires", "converts all AC outlets to high-voltage DC supply"],
         "Ground wire carries leakage/fault current safely to earth, tripping breakers.",
         "Students think grounding blocks all current or removes wire insulation needs.",
         "C1.7k", "Explaining household electrical grounding safety purpose", "Easy", 70),
        ("Resistance of a wire increases when",
         "the wire is longer or has smaller cross-sectional area", ["the wire is shorter and thicker simultaneously for same material", "temperature decreases in a superconductor above T_c always", "voltage across the wire is reduced to zero"],
         "R = ρL/A; longer thinner wires have higher resistance.",
         "Students think shorter thicker wires increase R or confuse with superconductivity.",
         "C1.3k", "Relating wire length and area to resistance", "Medium", 75),
        ("A circuit breaker differs from a fuse because a circuit breaker",
         "can be reset after tripping rather than replaced", ["melts permanently every time any current flows", "only works in DC circuits never in AC wiring", "increases current capacity when it overheats"],
         "Breakers use thermal/magnetic trip mechanisms and are reusable after fault clearance.",
         "Students think breakers melt like fuses or only function in DC systems.",
         "C1.7k", "Distinguishing resettable breaker from one-time fuse", "Easy", 65),
        ("Electric potential energy of two like charges placed closer together",
         "increases as work is required to push them nearer against repulsion", ["decreases because repulsion does positive work automatically", "remains zero regardless of separation distance", "converts entirely to nuclear binding energy"],
         "Like charges repel; moving them closer stores additional potential energy.",
         "Students think repulsion lowers potential energy when charges approach.",
         "C1.2s", "Analyzing potential energy change for like charges", "Hard", 95),
        ("In a series circuit with identical bulbs, if one bulb burns out",
         "the circuit opens and all bulbs go out", ["remaining bulbs become brighter because current doubles", "voltage across each remaining bulb drops to zero individually only", "total resistance drops to zero ohms instantly"],
         "Series path interruption stops current through all components.",
         "Students think remaining series bulbs stay lit or get brighter after one fails.",
         "C1.6k", "Predicting series circuit behaviour when one bulb fails", "Easy", 65),
        ("The unit of electric field strength is",
         "newtons per coulomb (N/C), equivalent to volts per metre (V/m)", ["joules per second only (watts)", "coulombs per newton (C/N) exclusively", "ohms per volt (Ω/V) for all fields"],
         "E = F/q has units N/C; also E = V/d gives V/m.",
         "Students confuse field units with power (W) or invert N/C to C/N.",
         "C1.2k", "Identifying electric field strength SI units", "Medium", 75),
        ("A galvanometer can be converted to an ammeter by",
         "connecting a low-resistance shunt in parallel with it", ["connecting a large resistor in series only without any shunt", "replacing the coil with a permanent magnet only", "eliminating all current flow through the device entirely"],
         "Parallel shunt carries most current, allowing galvanometer to measure large currents.",
         "Students add series resistance (voltmeter config) when converting to ammeter.",
         "C1.8k", "Describing shunt resistor ammeter conversion", "Hard", 95),
        ("Electrical energy consumed by an appliance is",
         "E = Pt, the product of power and time", ["E = P/t, power divided by time always", "E = V/R without multiplying by time or current", "E = I/R for all household devices"],
         "Energy (kWh) = power (kW) × time (h); E = Pt in SI units.",
         "Students divide power by time or omit time factor in energy calculation.",
         "C1.3s", "Calculating electrical energy from power and time", "Easy", 70),
        ("Magnetic flux through a loop increases when",
         "the magnetic field strength through the loop increases or effective area increases", ["the loop is rotated so field lines are parallel to the plane only", "all magnetic field lines bypass the loop entirely by design", "electric current in the loop drops to zero amperes always"],
         "Φ = BA cos θ; stronger field, larger area, or better alignment increases flux.",
         "Students think parallel field orientation maximizes flux (it minimizes it).",
         "C1.5k", "Identifying factors increasing magnetic flux through loop", "Medium", 85),
        ("A resistor colour code band of red-violet-yellow on a 4-band resistor indicates",
         "resistance of approximately 270 kΩ with gold or silver tolerance band", ["resistance of 27 Ω with no multiplier band", "capacitance of 270 microfarads in the circuit", "inductance of 27 millihenries in the coil"],
         "Red=2, violet=7, yellow=×10⁴ → 27×10⁴ Ω = 270 kΩ (4th band is tolerance).",
         "Students misread colour code multiplier or confuse resistor with capacitor value.",
         "C1.9k", "Reading four-band resistor colour code value", "Hard", 100),
        ("Electric shock severity depends significantly on",
         "current through the body, path, and duration of contact", ["only the colour of the insulation on the wire", "the brand name printed on the circuit breaker", "whether the wire is coiled clockwise or counterclockwise"],
         "It is current (amperes), not voltage alone, that determines physiological effect.",
         "Students focus on voltage alone or irrelevant wire physical appearance.",
         "C1.1sts", "Analyzing factors affecting electric shock severity", "Medium", 90),
    ]

    emr = [
        ("Radio waves have the longest wavelengths in the electromagnetic spectrum, which means they",
         "have the lowest frequencies and lowest photon energies in the spectrum", ["have the highest frequencies of all EMR types", "travel slower than gamma rays in vacuum always", "cannot be produced by any human technology ever"],
         "λ is longest for radio; f and E are lowest (E = hf).",
         "Students think long wavelength means high frequency or that c differs by type in vacuum.",
         "C2.1k", "Relating radio wave wavelength to frequency and energy", "Easy", 60),
        ("X-rays are used medically for imaging because they",
         "penetrate soft tissue but are absorbed more by dense bone", ["are completely absorbed by all human tissue equally", "have wavelengths longer than AM radio waves always", "travel only along copper wires in hospital buildings"],
         "Differential absorption creates contrast between bone and soft tissue on film/detector.",
         "Students think X-rays cannot penetrate tissue or have radio-wave wavelengths.",
         "C2.2k", "Explaining X-ray medical imaging tissue penetration", "Medium", 80),
        ("The speed of all electromagnetic radiation in vacuum is",
         "approximately 3.0 × 10⁸ m/s regardless of frequency", ["proportional to frequency so gamma travels faster", "zero for ultraviolet and only visible light moves", "different for each colour of visible light in vacuum"],
         "All EMR travels at c in vacuum; frequency/wavelength vary, not speed.",
         "Students think higher frequency means faster speed in vacuum.",
         "C2.5k", "Stating constant speed of EMR in vacuum", "Easy", 55),
        ("Microwave ovens heat food primarily by",
         "absorption of microwave photons causing polar molecules (especially water) to rotate", ["ionizing all food molecules like gamma radiation does", "emitting visible red light from a hot filament coil only", "inducing nuclear fission in water molecules"],
         "Microwave radiation excites molecular rotation/vibration in polar molecules, producing heat.",
         "Students confuse non-ionizing microwave heating with ionizing nuclear processes.",
         "C2.3k", "Explaining microwave dielectric heating of polar molecules", "Medium", 85),
        ("Polarized sunglasses reduce glare from water surfaces because they",
         "block horizontally polarized reflected light while passing some vertical component", ["absorb all wavelengths of light equally without polarization effect", "increase the intensity of reflected glare for better vision", "convert unpolarized sunlight into gamma radiation"],
         "Specular reflection from horizontal surfaces is often horizontally polarized; filters block it.",
         "Students think sunglasses amplify glare or polarize light into ionizing radiation.",
         "C2.4k", "Explaining polarized lens glare reduction mechanism", "Medium", 85),
        ("In the photoelectric effect, increasing light intensity while keeping frequency constant",
         "increases the number of photoelectrons emitted but not their maximum kinetic energy", ["increases maximum kinetic energy of each photoelectron linearly", "prevents any electrons from being emitted at all", "decreases the work function of the metal surface"],
         "Each photon ejects at most one electron; higher intensity means more photons, more electrons.",
         "Students think intensity raises electron KE rather than count (frequency sets max KE).",
         "C2.7k", "Distinguishing photoelectric intensity vs frequency effects", "Hard", 95),
        ("FM radio signals typically have",
         "higher frequency and shorter wavelength than AM radio signals", ["lower frequency and longer wavelength than all AM stations always", "identical frequency to visible green light in vacuum", "wavelength measured in kilometres for all FM broadcasts"],
         "FM band (~88–108 MHz) is higher frequency/shorter λ than AM (~540–1600 kHz).",
         "Students reverse AM/FM frequency relationship or compare FM to visible light.",
         "C2.6k", "Comparing FM and AM radio frequency and wavelength", "Easy", 65),
        ("Ionizing radiation such as gamma rays can damage living tissue because",
         "high-energy photons can ionize atoms and break chemical bonds in biomolecules", ["they only warm tissues slightly like a microwave oven always", "they have wavelengths too long to interact with any matter", "they increase cell division rate without any DNA interaction"],
         "Ionizing radiation removes electrons and can cause mutations and cell death.",
         "Students think gamma rays only heat gently or cannot interact due to long λ.",
         "C2.2k", "Explaining ionizing radiation biological damage mechanism", "Medium", 85),
        ("Refraction of light at an air-glass boundary occurs because",
         "light changes speed in glass, bending at the interface", ["light speed changes in vacuum at the boundary only", "glass absorbs all frequencies equally without direction change", "photon mass increases in glass causing gravitational bending only"],
         "Snell's law: speed change at boundary causes direction change (bending).",
         "Students think refraction requires speed change in vacuum or gravity alone.",
         "C2.4k", "Explaining refraction due to speed change at boundary", "Medium", 80),
        ("Astronomical spectroscopy identifies elements in stars by",
         "matching absorption/emission line patterns to known elemental spectra", ["measuring the mass of the star with a bathroom scale", "counting the number of planets in the solar system only", "determining blood type of the star's core plasma"],
         "Each element produces unique spectral lines from electron transitions.",
         "Students confuse spectroscopy with planetary counting or irrelevant biological measures.",
         "C2.8k", "Describing elemental identification via stellar spectroscopy", "Medium", 85),
        ("Infrared thermography detects",
         "thermal radiation emitted by objects based on their temperature", ["only visible light reflected from mirrors exclusively", "radio waves from communication towers exclusively", "gamma rays produced by nuclear reactors in all buildings"],
         "Warmer objects emit more IR; cameras detect IR intensity to map temperature.",
         "Students think thermography uses reflected visible light or detects gamma rays.",
         "C2.3k", "Explaining infrared thermography temperature detection", "Medium", 80),
        ("The electromagnetic spectrum ordered by increasing frequency is",
         "radio, microwave, infrared, visible, ultraviolet, X-ray, gamma", ["gamma, X-ray, ultraviolet, visible, infrared, microwave, radio", "visible, radio, gamma, microwave, infrared, ultraviolet, X-ray", "infrared, visible, radio, gamma, microwave, ultraviolet, X-ray"],
         "Standard order runs from lowest f (radio) to highest f (gamma).",
         "Students memorize incorrect order reversing gamma and radio positions.",
         "C2.1k", "Ordering EM spectrum regions by increasing frequency", "Easy", 60),
        ("LASER light differs from ordinary incandescent bulb light because laser emission is",
         "coherent, monochromatic, and highly directional", ["incoherent with all wavelengths and random phases", "always lower intensity than any thermal source", "produced only by chemical reactions in the filament"],
         "Laser: one wavelength, in-phase photons, narrow beam; bulb: broad thermal spectrum.",
         "Students think lasers are incoherent broadband sources like incandescent bulbs.",
         "C2.9k", "Distinguishing laser coherence from incandescent emission", "Medium", 85),
        ("Wireless internet (Wi-Fi) uses",
         "microwave-frequency electromagnetic radiation to transmit data", ["sound waves in the audible 20 Hz to 20 kHz range only", "direct current flowing through the air between routers", "gravitational waves from router antenna mass oscillation"],
         "Wi-Fi operates in GHz microwave bands carrying digital data via EM waves.",
         "Students think Wi-Fi uses audible sound or DC conduction through air.",
         "C2.6k", "Identifying Wi-Fi as microwave EM data transmission", "Easy", 65),
        ("Sunburn is primarily caused by exposure to",
         "ultraviolet (UV) radiation from the Sun", ["infrared radiation that only warms the skin harmlessly always", "radio waves from solar magnetic field oscillations only", "visible green light which ionizes all skin cells instantly"],
         "UV-B especially damages skin DNA, causing sunburn and increasing cancer risk.",
         "Students attribute sunburn to harmless IR warming or visible green light ionization.",
         "C2.2k", "Linking sunburn to ultraviolet skin damage", "Easy", 60),
        ("The Doppler effect for sound occurs when",
         "the observed frequency changes due to relative motion between source and observer", ["sound speed in air changes with the colour of the source", "the amplitude of the wave always doubles when source approaches", "only electromagnetic waves exhibit Doppler shift never sound"],
         "Approaching source: higher observed f; receding: lower observed f.",
         "Students think Doppler applies only to light or that sound speed changes with colour.",
         "C2.10k", "Describing Doppler frequency shift for moving sound source", "Medium", 80),
        ("Fiber optic communication relies on",
         "total internal reflection guiding light pulses through a glass core", ["absorption of all light by the cladding within one metre always", "transmission of electric current through copper filaments in air", "reflection from mirrors placed every kilometre in open air"],
         "Light signals reflect inside core at core-cladding boundary via TIR, minimizing loss.",
         "Students think fiber optics use air-gap mirrors or conduct electricity through air.",
         "C2.4k", "Explaining fiber optic total internal reflection guidance", "Medium", 85),
        ("Blackbody radiation intensity at high temperature",
         "increases and peaks at shorter wavelengths (Wien's law)", ["decreases to zero at all wavelengths simultaneously", "peaks at longer wavelengths as temperature rises without limit", "emits only a single visible wavelength independent of temperature"],
         "Hotter objects radiate more power; peak wavelength shifts shorter with temperature.",
         "Students think hotter objects peak at longer λ or emit single colour only.",
         "C2.8k", "Applying Wien's law to blackbody peak wavelength shift", "Hard", 95),
        ("Radar systems detect aircraft by",
         "transmitting radio/microwave pulses and measuring reflected echo time and frequency shift", ["listening for audible engine noise only at night", "measuring gravitational pull of aircraft on the ground station", "detecting visible light emitted by jet fuel combustion exclusively"],
         "Radar uses EM pulse round-trip time for range; Doppler shift can give speed.",
         "Students think radar uses sound detection or gravity rather than EM pulse echo.",
         "C2.6s", "Describing radar pulse echo detection principle", "Medium", 85),
        ("Exposure to UV-C from unshielded germicidal lamps is hazardous because",
         "UV-C is highly ionizing and causes severe skin and eye damage", ["UV-C only warms skin gently like infrared heat lamps always", "UV-C has wavelength too long to interact with any biological tissue", "UV-C converts all skin cells to beneficial vitamin D instantly without risk"],
         "UV-C is absorbed by DNA/proteins causing burns and damage; not safe for skin exposure.",
         "Students underestimate UV-C harm thinking it is harmless warmth or vitamin D only.",
         "C2.2sts", "Evaluating UV-C germicidal lamp exposure health risk", "Medium", 90),
    ]

    energy = [
        ("Fossil fuels are considered non-renewable because",
         "their formation takes millions of years and consumption exceeds natural replenishment", ["they regenerate fully within one human lifetime always", "they are produced continuously by photosynthesis in coal mines", "they contain no carbon and cannot be burned for energy"],
         "Coal, oil, gas form over geological time; reserves deplete faster than they reform.",
         "Students think fossil fuels renew quickly or contain no combustible carbon.",
         "D1.5k", "Explaining non-renewable nature of fossil fuels", "Easy", 60),
        ("Solar photovoltaic cells convert",
         "sunlight directly into electrical energy via the photovoltaic effect", ["thermal energy from coal combustion into light only", "kinetic energy of wind into chemical fuel without any photons", "gravitational potential of water dams into nuclear energy"],
         "PV cells use semiconductor junctions to generate electricity from incident photons.",
         "Students confuse PV electricity generation with thermal coal or wind-to-chemical conversion.",
         "D2.4k", "Describing photovoltaic sunlight-to-electricity conversion", "Easy", 65),
        ("The second law of thermodynamics implies that energy conversions are",
         "never 100% efficient; some energy always becomes dispersed waste heat", ["always perfectly efficient with no entropy increase ever", "impossible in any real system including living organisms", "only applicable to mechanical systems not electrical ones"],
         "Entropy increases; no heat engine or real process converts energy with 100% useful output.",
         "Students think perfect efficiency is achievable or second law applies only to mechanics.",
         "D2.3k", "Applying second law to real energy conversion efficiency limits", "Medium", 85),
        ("Hydroelectric dams generate electricity by",
         "converting gravitational potential energy of stored water into kinetic then electrical energy", ["burning hydrogen gas stored in the reservoir directly", "absorbing solar UV in the concrete dam wall exclusively", "converting nuclear fission in turbine blades to light"],
         "Water flow drives turbines connected to generators (gravitational PE → KE → electrical).",
         "Students think hydro plants burn fuel in water or use nuclear fission in turbines.",
         "D2.4k", "Tracing hydroelectric PE-to-electrical energy conversion", "Easy", 65),
        ("Energy density of gasoline is advantageous for vehicles because",
         "a relatively small mass stores large chemical energy for long travel range", ["gasoline has lower energy per mass than all battery systems always", "gasoline produces no CO₂ when burned in any engine", "gasoline regenerates in the fuel tank through photosynthesis"],
         "Liquid hydrocarbons pack high chemical energy per kg, enabling portable high-range transport.",
         "Students think gasoline has low energy density or regenerates or emits no CO₂.",
         "D1.5k", "Comparing gasoline energy density for transportation", "Medium", 80),
        ("Carbon-neutral biomass energy claim assumes",
         "CO₂ released during combustion was recently absorbed during plant growth", ["no CO₂ is produced when any biomass is burned ever", "fossil carbon is added to the atmosphere without any offset", "biomass combustion violates conservation of energy entirely"],
         "Recent biomass carbon cycle can balance combustion CO₂ if regrowth matches harvest rate.",
         "Students think biomass combustion emits zero carbon or adds fossil carbon.",
         "D2.1sts", "Evaluating carbon-neutral biomass energy accounting", "Medium", 85),
        ("Insulation in building envelopes reduces energy demand by",
         "slowing heat transfer through walls and roofs", ["generating electricity from temperature differences alone always", "eliminating all need for ventilation and fresh air exchange", "converting all waste heat back to chemical fuel in the walls"],
         "Insulation lowers conductive/convective heat loss/gain, reducing heating/cooling loads.",
         "Students think insulation generates electricity or removes ventilation needs entirely.",
         "D1.3k", "Explaining building insulation heat transfer reduction", "Easy", 65),
        ("Nuclear fission power plants produce electricity by",
         "using fission heat to generate steam that drives turbines connected to generators", ["directly converting gamma rays into household current without steam", "burning uranium metal with oxygen in open flame like coal", "using fusion of hydrogen in tokamak reactors commercially everywhere today"],
         "Fission heats water/steam → turbine → generator; not direct gamma-to-wire conversion.",
         "Students confuse fission steam cycle with combustion or commercial fusion.",
         "D2.5k", "Describing nuclear fission steam-turbine electricity generation", "Medium", 80),
        ("Smart grid technology improves energy management by",
         "using digital communication to balance supply, demand, and grid reliability", ["eliminating all power lines and using only batteries in every home", "preventing any renewable source from connecting to the grid ever", "converting all AC transmission to DC without any conversion losses"],
         "Smart meters and sensors optimize distribution, integrate renewables, and improve response.",
         "Students think smart grids remove transmission lines or block all renewables.",
         "D2.10k", "Defining smart grid digital energy management role", "Medium", 85),
        ("Life-cycle analysis (LCA) of an energy technology considers",
         "environmental impacts from resource extraction through disposal", ["only the operating cost during one week of use", "only the colour of the equipment paint on exterior panels", "only the voltage output at peak sun on one afternoon"],
         "LCA includes mining, manufacturing, operation, maintenance, and end-of-life disposal.",
         "Students limit analysis to short-term cost or single performance snapshot.",
         "D2.1sts", "Defining life-cycle analysis scope for energy systems", "Medium", 85),
        ("Tidal energy harnesses",
         "gravitational potential energy from rising and falling ocean tides", ["only chemical energy stored in dissolved table salt exclusively", "solar ultraviolet ionizing all seawater molecules directly", "nuclear fusion occurring naturally in every tide pool"],
         "Tidal barrages/turbines capture PE/KE of tidal water movement driven by Moon/Sun gravity.",
         "Students think tides provide chemical salt energy or UV ionization power.",
         "D2.4k", "Explaining tidal gravitational energy harvesting", "Medium", 80),
        ("Energy returned on energy invested (EROEI) compares",
         "useful energy output to energy invested in obtaining that energy", ["total economic price of electricity to government tax revenue only", "number of solar panels visible from a highway overpass", "mass of coal ash produced without any energy accounting"],
         "EROEI = energy delivered / energy spent; values >1 needed for net energy gain.",
         "Students confuse EROEI with monetary price or visual panel count.",
         "D2.2k", "Defining EROEI energy output vs input ratio", "Hard", 95),
        ("Geothermal energy from hot dry rock systems uses",
         "injected water circulated through heated underground rock to produce steam or hot fluid", ["combustion of methane stored in granite pores exclusively", "direct conversion of Earth's magnetic field to AC without heat", "photosynthesis in underground caves powered by rock fluorescence"],
         "Water is pumped through fractured hot rock, heated, and used to drive turbines.",
         "Students think geothermal dry rock burns methane or harvests magnetic field directly.",
         "D2.4k", "Describing hot dry rock geothermal fluid circulation", "Hard", 95),
        ("Demand-side management encourages consumers to",
         "shift electricity use to off-peak times reducing peak load on the grid", ["use maximum power simultaneously during peak hours always", "disconnect from the grid permanently without any alternative supply", "increase incandescent lighting during heat waves to save energy"],
         "Shifting load (e.g., timers on appliances) flattens demand peaks, improving grid stability.",
         "Students think demand management means maximizing simultaneous peak use.",
         "D1.1k", "Describing demand-side management peak load reduction", "Medium", 80),
        ("Hydrogen fuel cells produce electricity by",
         "combining hydrogen and oxygen electrochemically with water as by-product", ["burning hydrogen in open flame without any electrochemical reaction", "splitting water using only mechanical gears without any chemistry", "fusing hydrogen nuclei in a tokamak inside each car engine"],
         "Fuel cell: 2H₂ + O₂ → 2H₂O + electrical energy via electrochemical cells.",
         "Students confuse fuel cells with combustion engines or nuclear fusion reactors.",
         "D2.6k", "Describing hydrogen fuel cell electrochemical reaction", "Medium", 85),
        ("Alberta oil sands bitumen requires upgrading because raw bitumen",
         "is too viscous and high in impurities for direct pipeline refining as crude", ["is already identical to gasoline ready for any car engine", "contains no carbon and cannot be processed chemically", "evaporates completely at room temperature without any processing"],
         "Bitumen is thick and sour; upgrading produces lighter synthetic crude for refineries.",
         "Students think bitumen is ready-to-use gasoline or contains no hydrocarbons.",
         "D1.4k", "Explaining bitumen upgrading necessity for pipeline transport", "Medium", 85),
        ("Energy conservation in a home audit might recommend",
         "sealing air leaks and upgrading to efficient appliances", ["removing all insulation to increase air circulation heat loss", "running space heaters with windows open during winter nights", "switching all lighting to highest-wattage incandescent bulbs available"],
         "Audits identify waste: drafts, inefficient devices, poor insulation improvements.",
         "Students recommend actions that increase energy waste rather than reduce it.",
         "D1.3s", "Applying home energy audit conservation recommendations", "Easy", 70),
        ("Wind turbine capacity factor is typically below 100% because",
         "wind speed varies and turbines cannot generate rated power at all times", ["turbines are deliberately shut off whenever electricity is needed most", "wind energy violates conservation of energy on calm days only", "generator coils convert all wind to heat without any rotation ever"],
         "Intermittent wind means actual annual output is fraction of nameplate rating × time.",
         "Students think turbines always run at rated power or violate energy conservation.",
         "D2.4k", "Explaining wind turbine capacity factor below nameplate", "Medium", 85),
        ("Small modular nuclear reactors (SMRs) are proposed to",
         "provide scalable lower-capacity nuclear power with factory-built modules", ["replace all solar panels with coal-fired steam engines in homes", "eliminate all need for cooling water in every design without exception", "generate power only from chemical battery discharge without fission"],
         "SMRs aim for flexible deployment with smaller output and modular construction.",
         "Students confuse SMRs with coal home units or chemical battery-only systems.",
         "D2.5k", "Describing small modular reactor design purpose", "Hard", 95),
        ("The Alberta electricity grid integrates diverse sources including",
         "natural gas, coal, hydro, wind, and solar generation", ["only geothermal fusion plants with no fossil or renewable mix", "exclusively hand-cranked generators with no transmission lines", "only imported electricity with no domestic generation ever"],
         "Alberta's grid uses mixed generation portfolio including fossils and growing renewables.",
         "Students think Alberta uses only one exotic source or no domestic generation.",
         "D1.1k", "Identifying Alberta electricity generation source diversity", "Easy", 65),
    ]

    for qt, ans, dist, expl, mis, oc, skill, diff, time in circ:
        items.append(mc(qt, ans, dist, expl, mis, topic=TOPIC_CIRC, outcome_code=oc,
                          skill_tested=skill, difficulty=diff, estimated_time_seconds=time))
    for qt, ans, dist, expl, mis, oc, skill, diff, time in gen:
        items.append(mc(qt, ans, dist, expl, mis, topic=TOPIC_GEN, outcome_code=oc,
                          skill_tested=skill, difficulty=diff, estimated_time_seconds=time))
    for qt, ans, dist, expl, mis, oc, skill, diff, time in chem:
        items.append(mc(qt, ans, dist, expl, mis, topic=TOPIC_CHEM, outcome_code=oc,
                          skill_tested=skill, difficulty=diff, estimated_time_seconds=time))
    for qt, ans, dist, expl, mis, oc, skill, diff, time in field:
        items.append(mc(qt, ans, dist, expl, mis, topic=TOPIC_FIELD, outcome_code=oc,
                          skill_tested=skill, difficulty=diff, estimated_time_seconds=time))
    for qt, ans, dist, expl, mis, oc, skill, diff, time in emr:
        items.append(mc(qt, ans, dist, expl, mis, topic=TOPIC_EMR, outcome_code=oc,
                          skill_tested=skill, difficulty=diff, estimated_time_seconds=time))
    for qt, ans, dist, expl, mis, oc, skill, diff, time in energy:
        items.append(mc(qt, ans, dist, expl, mis, topic=TOPIC_ENERGY, outcome_code=oc,
                          skill_tested=skill, difficulty=diff, estimated_time_seconds=time))

    # Numerical response expansion
    items.extend([
        nr("A resting adult heart rate is 72 beats per minute. How many beats occur in 5 minutes?",
           "360", "72 × 5 = 360 beats in five minutes.", "Students divide 72 by 5 instead of multiplying.",
           topic=TOPIC_CIRC, outcome_code="A1.1s", skill_tested="Calculating total heartbeats over five-minute interval",
           difficulty="Easy", estimated_time_seconds=55),
        nr("If cardiac output is 5.0 L/min and heart rate is 100 beats/min, what is stroke volume in litres per beat? Express to two decimal places.",
           "0.05", "Stroke volume = CO/HR = 5.0/100 = 0.05 L/beat.", "Students multiply CO and HR instead of dividing.",
           topic=TOPIC_CIRC, outcome_code="A1.3s", skill_tested="Calculating stroke volume from cardiac output and heart rate",
           difficulty="Medium", estimated_time_seconds=90),
        nr("A population is in Hardy-Weinberg equilibrium with allele frequency p = 0.6 for dominant allele A. What is the expected frequency of genotype aa? Express as a decimal to two decimal places.",
           "0.16", "q = 1 − 0.6 = 0.4; freq(aa) = q² = 0.16.", "Students use p² instead of q² for recessive homozygote frequency.",
           topic=TOPIC_GEN, outcome_code="A3.3s", skill_tested="Calculating recessive homozygote frequency from allele p",
           difficulty="Hard", estimated_time_seconds=100),
        nr("A DNA sample has 30% adenine (A) bases. What percent of bases are guanine (G)? Assume equal A=T and G=C pairing.",
           "20", "A=T=30%; remaining 40% is G+C, so G=20%.", "Students assign 30% to G or forget complementary pairing rules.",
           topic=TOPIC_GEN, outcome_code="A3.4s", skill_tested="Calculating guanine percent from adenine in double-stranded DNA",
           difficulty="Medium", estimated_time_seconds=90),
        nr("What is the molar mass of water (H₂O) in g/mol? Use H = 1 g/mol and O = 16 g/mol.",
           "18", "M = 2(1) + 16 = 18 g/mol for water.", "Students add only one hydrogen or use O = 8 g/mol.",
           topic=TOPIC_CHEM, outcome_code="B1.1s", skill_tested="Calculating molar mass of water from atomic masses",
           difficulty="Easy", estimated_time_seconds=60),
        nr("A solution has hydroxide ion concentration 1.0 × 10⁻⁴ mol/L. What is the pH? Express to one decimal place.",
           "10.0", "pOH = −log(10⁻⁴) = 4; pH = 14 − 4 = 10.0 for aqueous solution at 25°C.", "Students report pOH value as pH without subtracting from 14.",
           topic=TOPIC_CHEM, outcome_code="B1.3s", skill_tested="Calculating pH from hydroxide ion concentration",
           difficulty="Medium", estimated_time_seconds=95),
        nr("A 12 V battery drives 2.0 A through a resistor. What is the resistance in ohms?",
           "6", "R = V/I = 12/2.0 = 6 Ω.", "Students multiply V × I instead of dividing voltage by current.",
           topic=TOPIC_FIELD, outcome_code="C1.3s", skill_tested="Calculating resistance from Ohm's law V and I",
           difficulty="Easy", estimated_time_seconds=65),
        nr("An electric heater rated 1500 W operates for 2 hours. How many kilowatt-hours (kWh) of energy are used?",
           "3", "Energy = 1.5 kW × 2 h = 3 kWh.", "Students use 1500 W without converting to kW before multiplying by hours.",
           topic=TOPIC_FIELD, outcome_code="C1.3s", skill_tested="Calculating kWh energy from appliance power rating",
           difficulty="Easy", estimated_time_seconds=70),
        nr("Light in vacuum has frequency 6.0 × 10¹⁴ Hz. What is the wavelength in nanometres? Use c = 3.0 × 10⁸ m/s. Express to zero decimal places.",
           "500", "λ = c/f = 3.0×10⁸/(6.0×10¹⁴) = 5.0×10⁻⁷ m = 500 nm.", "Students forget to convert metres to nanometres after calculation.",
           topic=TOPIC_EMR, outcome_code="C2.6s", skill_tested="Calculating visible wavelength in nm from frequency",
           difficulty="Medium", estimated_time_seconds=95),
        nr("A solar panel produces 250 W in full sun. How many hours of operation produce 1.5 kWh of energy?",
           "6", "Time = Energy/Power = 1.5 kWh/0.25 kW = 6 h.", "Students divide power by energy or forget kW conversion.",
           topic=TOPIC_ENERGY, outcome_code="D2.4s", skill_tested="Calculating operating time for solar energy output target",
           difficulty="Medium", estimated_time_seconds=85),
        nr("A coal plant is 35% efficient. If it burns fuel providing 10 000 MJ of energy, how many MJ of electricity are produced? Express to zero decimal places.",
           "3500", "Useful output = 0.35 × 10 000 = 3500 MJ electrical.", "Students divide by 0.35 or subtract 35% instead of multiplying.",
           topic=TOPIC_ENERGY, outcome_code="D2.3s", skill_tested="Calculating useful electrical output from plant efficiency",
           difficulty="Medium", estimated_time_seconds=90),
        nr("Wind turbine rated 2.0 MW operates at 40% capacity factor for 24 hours. How many MWh are generated? Express to one decimal place.",
           "19.2", "Output = 2.0 MW × 0.40 × 24 h = 19.2 MWh.", "Students omit capacity factor or multiply by 100 instead of 0.40.",
           topic=TOPIC_ENERGY, outcome_code="D2.4s", skill_tested="Calculating MWh from turbine capacity factor over one day",
           difficulty="Hard", estimated_time_seconds=100),
    ])

    return items
