"""Unit C (Cell Division): mitosis, meiosis — original Biology 30 questions."""

from .helpers import mc, nr, wr

TOPIC = "Cell Division"


def questions():
    q = [
        mc(
            "Mitosis produces daughter cells that are",
            "genetically identical to the parent cell",
            ["haploid with half the chromosome number always", "genetically different due to crossing over", "lacking any nuclear material"],
            "Mitosis maintains chromosome number and genetic identity for growth and repair.",
            "Crossing over occurs in meiosis, not mitosis.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Describing products of mitosis",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "The stage of mitosis during which chromosomes align at the cell equator is",
            "metaphase",
            ["prophase", "anaphase", "telophase"],
            "Metaphase is characterized by chromosomes aligned on the metaphase plate.",
            "Anaphase involves sister chromatid separation.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Identifying mitosis stages",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "Sister chromatids separate during",
            "anaphase of mitosis",
            ["prophase of meiosis I only", "interphase before DNA replication", "cytokinesis exclusively"],
            "Anaphase involves cohesin breakdown and movement of sister chromatids to opposite poles.",
            "Homologous chromosomes separate in meiosis I; sisters in meiosis II and mitosis anaphase.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Identifying timing of chromatid separation",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Cytokinesis in animal cells occurs by",
            "formation of a cleavage furrow",
            ["building a cell plate from the centre outward", "dissolving the nuclear envelope permanently without division", "meiosis without DNA replication"],
            "Animal cells pinch inward via actin-myosin ring. Plants form a cell plate.",
            "Cell plates are characteristic of plant cytokinesis.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Comparing cytokinesis in animal cells",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "The cell cycle phase when DNA replication occurs is",
            "S phase of interphase",
            ["G1 before any synthesis", "M phase during mitosis", "G0 permanently in all cells"],
            "DNA is duplicated during S (synthesis) phase before mitosis.",
            "Replication does not occur during M phase.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Locating DNA replication in cell cycle",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "Meiosis I is described as reduction division because it",
            "separates homologous chromosome pairs producing haploid cells",
            ["duplicates DNA without cell division", "produces four diploid cells", "only occurs in somatic skin cells"],
            "Meiosis I halves the chromosome number by separating homologues.",
            "Meiosis produces haploid, not diploid, products.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Explaining reduction division in meiosis I",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "Crossing over during prophase I of meiosis contributes to",
            "genetic recombination between homologous chromosomes",
            ["identical daughter cells in every division", "doubling of chromosome number in gametes", "elimination of all allelic variation"],
            "Exchange of segments between non-sister chromatids creates new allele combinations.",
            "Mitosis does not involve crossing over.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Explaining crossing over significance",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Independent assortment of chromosomes occurs during",
            "metaphase I of meiosis",
            ["interphase of mitosis only", "cytokinesis of meiosis II exclusively", "DNA replication in S phase"],
            "Random alignment of homologous pairs at metaphase I leads to independent assortment.",
            "Sister chromatid separation is not independent assortment.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Identifying when independent assortment occurs",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "A cell with diploid number $2n = 12$ after meiosis II produces gametes with",
            "$n = 6$ chromosomes each",
            ["$n = 12$ chromosomes each", "$n = 3$ chromosomes each", "$n = 24$ chromosomes each"],
            "Meiosis halves the diploid number: $12 \\div 2 = 6$.",
            "Students forget meiosis halves chromosome number.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Calculating haploid chromosome number",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Synapsis and formation of tetrads occur in",
            "prophase I of meiosis",
            ["prophase of mitosis", "anaphase II of meiosis", "G2 of interphase"],
            "Homologous chromosomes pair as tetrads during meiotic prophase I.",
            "Mitotic prophase has no synapsis.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Identifying prophase I events",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Nondisjunction in meiosis I results in gametes with",
            "an extra or missing homologous chromosome",
            ["always perfect haploid sets", "only mitochondrial DNA abnormalities", "no effect on offspring chromosome number"],
            "Failure of homologue separation yields n+1 and n-1 gametes.",
            "Nondisjunction has significant effects on zygote karyotype.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Predicting nondisjunction consequences in meiosis I",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Down syndrome (trisomy 21) most commonly arises from",
            "nondisjunction during maternal meiosis I",
            ["crossing over in sperm mitosis", "DNA replication in G1 phase", "cytokinesis failure in zygote mitosis only"],
            "Trisomy 21 typically results from meiotic nondisjunction producing n+1 gamete.",
            "Trisomy involves meiotic error, not mitotic crossing over.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Relating trisomy 21 to nondisjunction",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "A karyotype showing 47, XXY indicates",
            "Klinefelter syndrome",
            ["Turner syndrome (45,X)", "normal male 46,XY", "trisomy 21"],
            "XXY is Klinefelter. Turner is 45,X; normal male is 46,XY.",
            "Sex chromosome aneuploidies are commonly confused.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Interpreting sex chromosome karyotypes",
            difficulty="Medium", estimated_time_seconds=80,
        ),
        mc(
            "Turner syndrome karyotype is typically",
            "45, X",
            ["47, XXY", "46, XX", "47, XXX"],
            "Monosomy X (45,X) causes Turner syndrome in females.",
            "XXY is Klinefelter; XXX is trisomy X.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Identifying Turner syndrome karyotype",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "The homologous region of X and Y chromosomes is important during",
            "meiosis because X and Y can pair and segregate",
            ["mitosis because homologues always pair in somatic cells", "cytokinesis in bacteria", "transcription in prokaryotes without a nucleus"],
            "Pseudoautosomal regions allow X-Y pairing in meiosis I.",
            "Somatic mitosis does not involve homologue pairing.",
            topic=TOPIC, outcome_code="C1.3k",
            skill_tested="Explaining X-Y pairing in meiosis",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Chiasmata visible during meiosis represent",
            "sites where crossing over occurred between homologues",
            ["centromeres attaching to spindle fibres in mitosis only", "nuclear pores for RNA export", "replication origins in interphase only"],
            "Chiasmata are physical manifestations of crossovers holding homologues together.",
            "Chiasmata are meiosis-specific crossover sites.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Interpreting chiasmata in meiosis",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "A somatic cell in G2 phase of the cell cycle contains",
            "twice the DNA content of the same cell in G1",
            ["half the DNA of G1 due to division", "no DNA because replication has not started", "four times the DNA of a gamete at all times"],
            "After S phase, DNA content doubles until mitosis divides it.",
            "G2 follows replication; DNA is doubled relative to G1.",
            topic=TOPIC, outcome_code="C1.2k",
            skill_tested="Comparing DNA content across cell cycle phases",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Cancer cells often exhibit uncontrolled division partly because of",
            "mutations in genes regulating the cell cycle checkpoints",
            ["complete loss of all DNA", "inability to replicate DNA ever", "permanent arrest in G0 in all cases"],
            "Oncogene activation or tumour suppressor loss disrupts checkpoints (e.g., p53).",
            "Cancer involves excessive, not absent, division.",
            topic=TOPIC, outcome_code="C1.6k",
            skill_tested="Relating cell cycle regulation to cancer",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "The mitotic index of a tissue sample measures",
            "the proportion of cells undergoing mitosis",
            ["the total number of chromosomes in the organism", "the rate of crossing over in gametes", "the concentration of hormones in blood"],
            "Mitotic index = (cells in mitosis / total cells) × 100%, indicating proliferation rate.",
            "Mitotic index is about division frequency, not chromosome count.",
            topic=TOPIC, outcome_code="C1.2k",
            skill_tested="Defining mitotic index",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Colchicine disrupts spindle formation. Treating a dividing cell with colchicine during metaphase would most likely",
            "prevent chromosome movement to poles, arresting division",
            ["accelerate sister chromatid separation", "cause immediate completion of cytokinesis", "induce meiosis in somatic cells"],
            "Without functional spindles, chromosomes cannot segregate properly.",
            "Spindle disruption blocks movement, not accelerates it.",
            topic=TOPIC, outcome_code="C1.2k",
            skill_tested="Predicting effects of spindle inhibitors",
            difficulty="Hard", estimated_time_seconds=110,
        ),
        nr(
            "Order mitosis phases: (1) anaphase, (2) metaphase, (3) prophase, (4) telophase. Record all four digits.",
            "3214",
            "Prophase (3), metaphase (2), anaphase (1), telophase (4).",
            "Anaphase placed before metaphase.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Sequencing mitosis phases",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        nr(
            "Order meiosis I stages: (1) telophase I, (2) metaphase I, (3) prophase I, (4) anaphase I. Record all four digits.",
            "3241",
            "Prophase I (3), metaphase I (2), anaphase I (4), telophase I (1).",
            "Meiosis I anaphase confused with mitosis timing.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Sequencing meiosis I stages",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        nr(
            "A cell has $2n = 16$. How many chromosomes are in each cell immediately after meiosis I? Record the two-digit answer.",
            "8",
            "Meiosis I halves the number: $16 \\div 2 = 8$ chromosomes per cell (still duplicated chromatids).",
            "Students answer 16 or 4 incorrectly.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Calculating chromosome number after meiosis I",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        wr(
            "Compare mitosis and meiosis in terms of purpose, number of divisions, and genetic variation in daughter cells.",
            "Mitosis: one division producing two genetically identical diploid cells for growth/repair; no crossing over. Meiosis: two divisions producing four genetically unique haploid gametes; crossing over and independent assortment generate variation.",
            "Marking guide: (1) Purpose contrast — 2 marks. (2) Division number — 1 mark. (3) Ploidy of products — 2 marks. (4) Variation mechanisms in meiosis — 2 marks.",
            "Students state meiosis produces identical cells or omit variation sources.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Comparing mitosis and meiosis comprehensively",
            difficulty="Medium", estimated_time_seconds=260,
        ),
        wr(
            "Explain how nondisjunction during meiosis can lead to trisomy in a zygote. Include which division may be affected and the chromosome number in the resulting gamete.",
            "If homologues fail to separate in meiosis I, or sister chromatids in meiosis II, a gamete receives n+1 chromosomes. When fertilized by a normal n gamete, the zygote is 2n+1 (trisomy). Example: n+1 gamete with chromosome 21 plus normal gamete yields trisomy 21 (47 chromosomes).",
            "Marking guide: (1) Define nondisjunction — 1 mark. (2) Identify meiosis I or II — 2 marks. (3) n+1 gamete described — 2 marks. (4) Zygote trisomy outcome — 1 mark.",
            "Students describe trisomy without explaining gamete chromosome number.",
            topic=TOPIC, outcome_code="C1.1k",
            skill_tested="Explaining mechanism of trisomy formation",
            difficulty="Hard", estimated_time_seconds=280,
        ),
    ]
    q += _supplement()
    return q


def _supplement():
    s = []
    items = [
        ("During prophase of mitosis, each chromosome consists of", "two sister chromatids joined at a centromere", ["four homologous chromatids in a tetrad", "a single unduplicated chromatid always", "only circular DNA without proteins"], "DNA replication in S phase creates sister chromatids visible in mitotic prophase.", "Tetrads are meiosis I structures.", "C1.1k", "Describing chromosome structure in mitosis", "Easy", 60),
        ("The centromere functions to", "attach chromatids to spindle fibres via kinetochores", ["replicate DNA during S phase directly", "produce ribosomes for the cell", "synthesize all cellular lipids"], "Kinetochores at centromeres connect chromatids to spindle microtubules.", "DNA polymerase replicates DNA, not centromeres.", "C1.1k", "Identifying centromere function", "Easy", 60),
        ("Binary fission in bacteria differs from eukaryotic mitosis because binary fission", "does not involve a mitotic spindle or nuclear envelope breakdown", ["always produces four haploid cells", "requires crossing over between homologues", "only occurs in human liver cells"], "Prokaryotes lack spindle apparatus and membrane-bound nucleus.", "Bacterial division is not meiotic.", "C1.1k", "Comparing binary fission and mitosis", "Medium", 85),
        ("A cell in metaphase of mitosis has a chromosome count of", "2n with each chromosome having two chromatids", ["n haploid chromosomes only", "4n due to two rounds of replication without division", "zero chromosomes visible"], "Metaphase mitotic cells are diploid (2n) with duplicated chromosomes.", "n chromosomes describe gametes or post-meiotic cells.", "C1.2k", "Determining ploidy at mitotic metaphase", "Medium", 80),
        ("Polyploidy in plants can result from", "failure of cytokinesis after mitosis or meiosis", ["only bacterial conjugation", "removal of all centromeres", "exclusive male meiosis without females"], "Cytokinesis failure doubles chromosome sets, common in plant breeding.", "Polyploidy is not caused by bacterial conjugation in plants.", "C1.1k", "Explaining polyploidy formation", "Hard", 110),
        ("The SRY gene on the Y chromosome triggers", "development of testes in mammalian embryogenesis", ["ovarian development regardless of other genes", "mitosis in bacterial cells", "photosynthesis in leaf cells"], "SRY initiates male gonadal differentiation pathway.", "Ovarian default pathway occurs without SRY function.", "C1.4k", "Describing SRY gene role in sex determination", "Medium", 90),
        ("In birds, females are ZW and males are ZZ. A female bird produces gametes with", "either Z or W chromosome (one sex chromosome each)", ["always ZZ like males", "no sex chromosomes in any egg", "four W chromosomes per egg"], "Female birds (ZW) produce Z or W gametes by meiotic segregation.", "ZZ is the male bird karyotype.", "C1.1k", "Applying sex determination to ZW system", "Hard", 115),
        ("Interphase is sometimes called the resting phase, but it is metabolically active because", "the cell grows and replicates DNA in preparation for division", ["no biochemical activity occurs at all", "chromosomes are visible and moving to poles", "crossing over occurs between tetrads"], "Interphase includes G1, S, and G2 with high metabolic activity.", "Chromosome movement occurs in M phase, not interphase.", "C1.1k", "Clarifying interphase activity", "Easy", 65),
        ("A biopsy shows 8% mitotic index versus 2% in normal tissue. This suggests", "higher cell proliferation rate in the biopsy tissue", ["complete absence of cell division", "all cells are in G0 permanently", "meiosis occurring in somatic liver cells"], "Elevated mitotic index indicates more cells dividing per unit time.", "Higher, not lower, division is indicated.", "C1.2k", "Interpreting mitotic index data", "Medium", 85),
        ("Checkpoint proteins such as p53 can halt the cell cycle if", "DNA damage is detected, allowing repair before division", ["the cell has perfect DNA always skipping G1", "spindle fibres form too early in G1", "all hormones are absent from blood"], "p53 activates repair pathways or apoptosis when damage is sensed.", "Checkpoints respond to damage, not hormone absence alone.", "C1.6k", "Explaining G1/S checkpoint function", "Medium", 90),
        ("Telophase of mitosis is characterized by", "reformation of nuclear envelopes around daughter nuclei", ["alignment of chromosomes at the equator", "separation of homologous chromosomes", "crossing over between non-sister chromatids"], "Telophase reverses prophase events: nuclei reform, chromosomes decondense.", "Equatorial alignment is metaphase.", "C1.1k", "Identifying telophase events", "Easy", 55),
        ("Meiosis II is most similar to mitosis because it", "separates sister chromatids in each haploid cell", ["pairs homologous chromosomes in tetrads", "duplicates DNA before starting", "produces diploid daughter cells"], "Meiosis II aligns and separates sister chromatids like mitosis.", "Homologue pairing is meiosis I only.", "C1.1k", "Comparing meiosis II to mitosis", "Medium", 85),
        ("A primary oocyte is arrested in prophase I until", "puberty when hormonal signals resume meiosis monthly", ["birth when it immediately completes meiosis IV", "fertilization of a sperm in the testes", "implantation in the seminiferous tubule"], "Oogenesis arrests at prophase I for years until ovulation cycle resumes.", "Meiosis IV does not exist.", "C1.3k", "Describing oocyte meiotic arrest", "Medium", 90),
        ("Spermatogenesis produces functional sperm beginning at", "puberty and continuing throughout adult life", ["before birth only in the ovary", "after menopause in females", "only once during embryonic development"], "Males continuously produce sperm from puberty onward.", "Female gametogenesis timing differs from male.", "C1.3k", "Describing spermatogenesis timing", "Easy", 65),
        ("A human cell with 92 chromatids during mitotic metaphase has diploid number", "2n = 46", ["2n = 92", "2n = 23", "2n = 184"], "92 chromatids = 46 duplicated chromosomes, so 2n = 46.", "Chromatid count is twice chromosome count at metaphase.", "C1.2k", "Calculating diploid number from chromatid count", "Hard", 110),
    ]
    for qt, ans, dist, expl, mis, oc, skill, diff, time in items:
        s.append(mc(qt, ans, dist, expl, mis, topic=TOPIC, outcome_code=oc,
                    skill_tested=skill, difficulty=diff, estimated_time_seconds=time))

    s += [
        nr("If mitotic index is $6$% and $500$ cells are counted, how many cells are in mitosis? Record the two-digit answer.", "30",
           "$500 \\times 0.06 = 30$ cells.", "Students multiply by 6 instead of 0.06.",
           topic=TOPIC, outcome_code="C1.2k", skill_tested="Calculating mitotic index count", difficulty="Medium", estimated_time_seconds=80),
        nr("A species has $2n = 20$. How many chromosomes per gamete? Record the two-digit answer.", "10",
           "$20 \\div 2 = 10$.", "Students give 20 or 5.",
           topic=TOPIC, outcome_code="C1.1k", skill_tested="Computing haploid number", difficulty="Easy", estimated_time_seconds=55),
        wr("Describe the events of prophase I of meiosis that contribute to genetic variation, naming at least two processes.",
           "Synapsis forms tetrads allowing crossing over between non-sister chromatids of homologues, creating recombinant chromosomes. Independent assortment at metaphase I randomizes which homologue orientations segregate to each pole, producing diverse gamete combinations.",
           "Marking guide: (1) Synapsis/tetrad — 1 mark. (2) Crossing over — 2 marks. (3) Independent assortment — 2 marks.",
           "Students mention only one variation source.",
           topic=TOPIC, outcome_code="C1.1k", skill_tested="Explaining meiotic sources of variation", difficulty="Medium", estimated_time_seconds=240),
    ]
    return s
