"""Unit C (Genetics and Molecular Biology) — original Biology 30 questions."""

from .helpers import mc, nr, wr

TOPIC = "Genetics and Molecular Biology"


def questions():
    q = [
        mc(
            "Mendel's law of segregation states that",
            "two alleles for a trait separate during gamete formation",
            ["all genes assort independently regardless of chromosome location", "dominant alleles physically blend with recessive alleles", "only sex chromosomes segregate during meiosis"],
            "Each gamete receives one allele of each gene as homologues separate in meiosis I.",
            "Independent assortment is a separate law from segregation.",
            topic=TOPIC, outcome_code="C2.1k",
            skill_tested="Stating law of segregation",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "A heterozygous individual (Aa) exhibits the dominant phenotype because",
            "one dominant allele is sufficient to express the trait",
            ["the recessive allele is always deleted from DNA", "dominant alleles code for no functional protein", "both alleles are always equally expressed in all cells"],
            "Complete dominance: one functional dominant allele masks recessive in heterozygotes.",
            "Recessive alleles remain present but may not affect phenotype.",
            topic=TOPIC, outcome_code="C2.1k",
            skill_tested="Explaining dominant phenotype in heterozygotes",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "A testcross (Aa × aa) is used to",
            "determine whether an individual with dominant phenotype is homozygous or heterozygous",
            ["always produce only homozygous dominant offspring", "map genes on the Y chromosome exclusively", "prevent crossing over during meiosis"],
            "Crossing with homozygous recessive reveals hidden recessive alleles in offspring ratios.",
            "Testcrosses reveal genotype, not prevent crossing over.",
            topic=TOPIC, outcome_code="C2.2k",
            skill_tested="Applying testcross reasoning",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "In a dihybrid cross AaBb × AaBb with genes on different chromosomes, the expected phenotypic ratio is",
            "9:3:3:1",
            ["3:1 only", "1:1:1:1 always for every dihybrid", "1:2:1 for both traits combined"],
            "Independent assortment of two heterozygous genes yields classic 9:3:3:1 ratio.",
            "3:1 is monohybrid ratio, not dihybrid.",
            topic=TOPIC, outcome_code="C2.2k",
            skill_tested="Predicting dihybrid phenotypic ratios",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Linked genes on the same chromosome violate independent assortment and produce",
            "more parental-type offspring than recombinant types in test crosses",
            ["exactly 9:3:3:1 ratios always", "no offspring ever", "only homozygous offspring"],
            "Linkage reduces recombinant frequency; parental combinations predominate unless crossing over separates alleles.",
            "9:3:3:1 assumes unlinked genes.",
            topic=TOPIC, outcome_code="C2.3k",
            skill_tested="Predicting linkage effects on offspring ratios",
            difficulty="Hard", estimated_time_seconds=110,
        ),
        mc(
            "Haemophilia is X-linked recessive. A carrier mother (X$^H$X$^h$) and unaffected father (X$^H$Y) have sons with haemophilia with probability",
            "50%",
            ["0% because fathers pass X to sons", "100% for all children", "25% for daughters only"],
            "Sons inherit X from mother: half receive X$^h$ and are affected.",
            "Fathers pass Y to sons, not X; mother's X determines son phenotype.",
            topic=TOPIC, outcome_code="C2.5k",
            skill_tested="Calculating X-linked inheritance probability",
            difficulty="Medium", estimated_time_seconds=95,
        ),
        mc(
            "Red-green colour blindness is X-linked recessive. An affected male and unaffected female (no family history) have daughters who are",
            "all carriers (phenotypically normal if mother homozygous dominant)",
            ["all affected because daughters get father's Y", "never carriers because X-linked traits skip females", "homozygous recessive always"],
            "Affected father passes X to all daughters; if mother is homozygous dominant, daughters are carriers.",
            "Fathers pass X to daughters, not Y.",
            topic=TOPIC, outcome_code="C2.5k",
            skill_tested="Predicting X-linked carrier status in offspring",
            difficulty="Medium", estimated_time_seconds=95,
        ),
        mc(
            "Watson and Crick's DNA model proposed that the two strands are",
            "antiparallel and held together by complementary base pairing",
            ["parallel with identical nucleotide sequences", "connected by peptide bonds between bases", "single-stranded with no hydrogen bonds"],
            "Antiparallel 5' to 3' orientation with A-T and G-C hydrogen bonding defines the double helix.",
            "Peptide bonds join amino acids, not DNA strands.",
            topic=TOPIC, outcome_code="C3.1k",
            skill_tested="Describing Watson-Crick DNA model features",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "Chargaff's rules state that in DNA",
            "the amount of adenine equals thymine and guanine equals cytosine",
            ["adenine equals guanine in all species", "thymine equals cytosine always", "all four bases are present in equal proportions"],
            "Complementary base pairing explains Chargaff's equality: A=T, G=C.",
            "A pairs with T, not G.",
            topic=TOPIC, outcome_code="C3.1k",
            skill_tested="Applying Chargaff's rules",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Semiconservative DNA replication means each daughter molecule contains",
            "one original strand and one newly synthesized strand",
            ["two entirely new strands with no original template", "only RNA without any DNA", "four identical strands in one helix"],
            "Meselson-Stahl demonstrated each new DNA helix retains one parental strand.",
            "Conservative model (all old strands together) was disproved.",
            topic=TOPIC, outcome_code="C3.2k",
            skill_tested="Defining semiconservative replication",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "DNA polymerase III in prokaryotes requires a primer because it",
            "can only add nucleotides to an existing 3' OH group",
            ["synthesizes DNA in the 3' to 5' direction exclusively", "does not need template DNA", "replaces RNA with amino acids directly"],
            "Primase provides short RNA primer with 3' OH for polymerase elongation in 5'→3' direction.",
            "DNA polymerase extends 5'→3', not 3'→5'.",
            topic=TOPIC, outcome_code="C3.2k",
            skill_tested="Explaining role of primase and polymerase",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "The leading strand during replication is synthesized",
            "continuously toward the replication fork",
            ["only in short Okazaki fragments away from the fork", "without any template", "only after all RNA is removed from ribosomes"],
            "Leading strand synthesis proceeds continuously 5'→3' as fork opens.",
            "Lagging strand uses Okazaki fragments.",
            topic=TOPIC, outcome_code="C3.2k",
            skill_tested="Distinguishing leading and lagging strand synthesis",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Okazaki fragments are found on the",
            "lagging strand and are later joined by DNA ligase",
            ["leading strand only without any joining", "mRNA during transcription exclusively", "protein primary structure during translation"],
            "Discontinuous synthesis on lagging strand produces Okazaki fragments sealed by ligase.",
            "Leading strand is continuous, not fragmented.",
            topic=TOPIC, outcome_code="C3.2k",
            skill_tested="Describing Okazaki fragment processing",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "During transcription, RNA polymerase binds to the",
            "promoter region upstream of the gene",
            ["tRNA anticodon loop", "ribosome P site exclusively", "centromere during anaphase"],
            "Promoters (e.g., TATA box in eukaryotes) initiate transcription.",
            "Anticodons are on tRNA, not promoter DNA.",
            topic=TOPIC, outcome_code="C3.3k",
            skill_tested="Identifying promoter role in transcription",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "In eukaryotes, pre-mRNA undergoes splicing to",
            "remove introns and join exons before export from nucleus",
            ["add amino acids to growing polypeptide chains", "replicate DNA semiconservatively", "produce Okazaki fragments on lagging strand"],
            "Spliceosome removes introns; mature mRNA contains continuous exon sequence.",
            "Splicing is RNA processing, not translation.",
            topic=TOPIC, outcome_code="C3.3k",
            skill_tested="Explaining mRNA splicing",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "The genetic code is degenerate because",
            "most amino acids are encoded by more than one codon",
            ["each codon specifies multiple different amino acids", "DNA has no thymine in any organism", "all proteins have identical primary sequences"],
            "Degeneracy: 64 codons code for 20 amino acids with redundancy (e.g., leucine has six codons).",
            "Each codon specifies one amino acid (or stop); degeneracy refers to multiple codons per amino acid.",
            topic=TOPIC, outcome_code="C3.3k",
            skill_tested="Defining genetic code degeneracy",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "A nonsense mutation introduces a",
            "premature stop codon in the mRNA",
            ["change in regulatory DNA far from any gene only", "duplication of an entire chromosome always", "new start codon at the beginning of every intron"],
            "Nonsense mutations create early stop codons, truncating the protein.",
            "Missense changes one amino acid; nonsense creates stop.",
            topic=TOPIC, outcome_code="C3.6k",
            skill_tested="Classifying nonsense mutations",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "A frameshift mutation caused by insertion of one nucleotide will",
            "alter every amino acid downstream of the insertion site",
            ["change only one amino acid without affecting downstream sequence", "always improve protein function", "prevent transcription from occurring entirely"],
            "Reading frame shift changes codon grouping for all subsequent sequence.",
            "Single nucleotide insertion is not a silent point mutation.",
            topic=TOPIC, outcome_code="C3.6k",
            skill_tested="Predicting frameshift mutation effects",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "During translation, the ribosome reads mRNA codons and matches them to",
            "anticodons on tRNA carrying specific amino acids",
            ["DNA bases on the lagging strand", "histone proteins in nucleosomes only", "promoter sequences on chromosome 1 only"],
            "tRNA anticodon pairs with mRNA codon; amino acid is added to polypeptide chain.",
            "Translation uses RNA, not DNA template directly.",
            topic=TOPIC, outcome_code="C3.3k",
            skill_tested="Describing codon-anticodon pairing",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "The start codon AUG codes for",
            "methionine and initiates translation",
            ["phenylalanine only", "a stop signal ending the protein", "thymine in the DNA strand"],
            "AUG is both methionine codon and universal translation start in eukaryotes.",
            "UAA, UAG, UGA are stop codons, not AUG.",
            topic=TOPIC, outcome_code="C3.3k",
            skill_tested="Identifying start codon function",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "PCR (polymerase chain reaction) amplifies DNA by using",
            "cycles of denaturation, primer annealing, and extension with thermostable polymerase",
            ["meiosis and fertilization in a test tube", "only RNA polymerase without any primers", "crossing over between homologous chromosomes in vitro"],
            "PCR thermocycles separate strands, bind primers, and extend with Taq polymerase.",
            "PCR is amplification, not meiosis.",
            topic=TOPIC, outcome_code="C3.4k",
            skill_tested="Describing PCR steps",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Gel electrophoresis separates DNA fragments primarily by",
            "size, with smaller fragments migrating farther through the gel",
            ["colour of nitrogenous bases exclusively", "the age of the DNA sample", "number of chromosomes in the organism only"],
            "Negatively charged DNA moves toward positive electrode; smaller pieces travel faster.",
            "Base colour does not determine gel migration distance.",
            topic=TOPIC, outcome_code="C3.4k",
            skill_tested="Explaining gel electrophoresis separation principle",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "CRISPR-Cas9 gene editing uses guide RNA to",
            "direct Cas9 nuclease to a specific DNA sequence for cleavage",
            ["translate mRNA into protein without ribosomes", "replicate entire chromosomes without polymerase", "prevent all mutations from ever occurring in nature"],
            "Guide RNA base-pairs with target DNA; Cas9 creates double-strand break for repair/editing.",
            "CRISPR edits DNA; it does not perform translation.",
            topic=TOPIC, outcome_code="C3.4k",
            skill_tested="Explaining CRISPR-Cas9 mechanism",
            difficulty="Medium", estimated_time_seconds=95,
        ),
        mc(
            "Mitochondrial DNA is inherited primarily from the",
            "mother because sperm contribute few mitochondria to the zygote",
            ["father because Y chromosome carries all mitochondria", "placenta exclusively without any cellular DNA", "environment with no genetic component"],
            "Maternal cytoplasm donates mitochondria; paternal contribution is minimal and often degraded.",
            "Y chromosome does not contain mitochondrial genome.",
            topic=TOPIC, outcome_code="C3.7k",
            skill_tested="Explaining maternal mitochondrial inheritance",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "A pedigree showing an affected father and affected daughter but unaffected mother suggests the trait is most likely",
            "autosomal dominant",
            ["X-linked recessive only with no exceptions", "Y-linked recessive affecting daughters", "mitochondrial with paternal transmission"],
            "Father-to-daughter transmission with affected father rules out X-linked recessive (father passes Y to sons). Autosomal dominant fits.",
            "Y-linked traits affect males only; daughters cannot inherit Y-linked disease genes from father.",
            topic=TOPIC, outcome_code="C2.2k",
            skill_tested="Interpreting pedigree inheritance pattern",
            difficulty="Hard", estimated_time_seconds=120,
        ),
        nr(
            "In a monohybrid cross Tt × Tt, what fraction of offspring are expected to be homozygous recessive? Express as a decimal rounded to two decimal places.",
            "0.25",
            "Punnett square yields 1/4 tt = 0.25.",
            "Students answer 0.50 confusing heterozygous fraction.",
            topic=TOPIC, outcome_code="C2.2k",
            skill_tested="Calculating monohybrid genotypic probability",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        nr(
            "Order protein synthesis steps: (1) tRNA delivers amino acids, (2) mRNA exits nucleus, (3) transcription, (4) ribosome assembly on mRNA. Record all four digits.",
            "3241",
            "Transcription (3), mRNA processing/export (2), ribosome binds mRNA (4), tRNA delivers amino acids (1).",
            "Translation steps placed before transcription.",
            topic=TOPIC, outcome_code="C3.3k",
            skill_tested="Sequencing gene expression steps",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        wr(
            "Explain the central dogma of molecular biology and describe what happens during each of transcription and translation in a eukaryotic cell.",
            "Central dogma: DNA → RNA → protein. Transcription: RNA polymerase synthesizes mRNA using DNA template in nucleus; pre-mRNA is processed (capping, splicing, poly-A tail). Translation: mature mRNA exported to cytoplasm; ribosome reads codons; tRNA brings amino acids; polypeptide elongates until stop codon.",
            "Marking guide: (1) Central dogma stated — 1 mark. (2) Transcription details — 3 marks. (3) Translation details — 3 marks.",
            "Students omit nuclear vs cytoplasmic compartmentalization in eukaryotes.",
            topic=TOPIC, outcome_code="C3.3k",
            skill_tested="Describing central dogma and gene expression",
            difficulty="Hard", estimated_time_seconds=300,
        ),
        wr(
            "A student claims a trait showing affected males passing to all daughters but no sons is X-linked dominant. Evaluate this claim using pedigree reasoning.",
            "Affected males pass X to daughters only (not sons). If all daughters of affected fathers are affected, the allele on father's X is expressed in daughters — consistent with X-linked dominant. Sons inherit father's Y, so they would not receive father's X-linked allele. The claim is reasonable if mothers are unaffected or heterozygous; if sons of carrier mothers can be affected, X-linked pattern must be distinguished from autosomal.",
            "Marking guide: (1) Father transmits X to daughters — 2 marks. (2) Sons inherit Y from father — 1 mark. (3) Evaluate consistency with X-linked dominant — 2 marks. (4) Note alternative patterns if needed — 1 mark.",
            "Students fail to note father-son transmission pattern for X-linked traits.",
            topic=TOPIC, outcome_code="C2.2k",
            skill_tested="Evaluating pedigree-based inheritance claims",
            difficulty="Hard", estimated_time_seconds=300,
        ),
    ]
    q += _supplement()
    return q


def _supplement():
    s = []
    items = [
        ("Codominance in AB blood type means", "both IA and IB alleles are fully expressed in heterozygotes", ["only the recessive i allele is expressed", "the phenotype is always intermediate like pink flowers", "neither allele is present in red blood cells"], "AB individuals express both A and B antigens — codominance.", "Incomplete dominance blends phenotypes; codominance shows both.", "C2.1k", "Distinguishing codominance from incomplete dominance", "Medium", 85),
        ("Incomplete dominance in snapdragon flower colour (red × white → pink) demonstrates", "heterozygotes with an intermediate phenotype", ["complete masking of recessive allele", "X-linked recessive inheritance", "linkage on the Y chromosome"], "Rr heterozygotes are pink — blended intermediate expression.", "Pink is intermediate, not dominant masking.", "C2.1k", "Explaining incomplete dominance", "Easy", 70),
        ("A Punnett square for Aa × Aa shows genotypic ratio", "1 AA : 2 Aa : 1 aa", ["1:1 Aa:aa only", "9:3:3:1", "all AA"], "Monohybrid self-cross genotypic ratio is 1:2:1.", "9:3:3:1 is dihybrid phenotypic ratio.", "C2.2k", "Determining monohybrid genotypic ratio", "Easy", 65),
        ("Blood type parent with genotype IAi × IBi can produce offspring with types", "A, B, AB, and O", ["only AB", "only O", "A and B but never AB or O"], "Cross can yield IAIB (AB), IAi (A), IBi (B), ii (O).", "All four blood types are possible from this cross.", "C2.2k", "Predicting ABO blood type offspring", "Medium", 95),
        ("Huntington disease is autosomal dominant. An affected heterozygous parent (Hh) × unaffected (hh) has affected offspring probability", "50%", ["0%", "100%", "25% only for females"], "Hh × hh gives 50% Hh affected, 50% hh unaffected.", "Dominant heterozygote transmits H to half of offspring.", "C2.2k", "Calculating autosomal dominant risk", "Easy", 70),
        ("Cystic fibrosis is autosomal recessive. Two carrier parents (Cc × Cc) have affected child probability", "25%", ["50%", "0%", "100%"], "Cc × Cc yields 1/4 cc affected.", "Carrier × carrier gives 25% affected, 50% carrier.", "C2.2k", "Calculating autosomal recessive risk", "Easy", 70),
        ("A double helix has 30% adenine. What percent is guanine?", "20%", ["30%", "40%", "70%"], "A=T=30%. Remaining 40% is G+C; equal G and C gives 20% each.", "Students forget Chargaff: G=C and A+G+T+C=100%.", "C3.1k", "Calculating base composition from Chargaff rules", "Medium", 90),
        ("The 5' cap on eukaryotic mRNA functions to", "protect mRNA and assist ribosome binding during translation initiation", ["terminate transcription at the promoter", "join Okazaki fragments", "catalyze peptide bond formation directly"], "5' cap stabilizes mRNA and is recognized by initiation factors.", "Cap is added after transcription starts, not at termination.", "C3.3k", "Explaining 5' cap function", "Medium", 85),
        ("The poly-A tail on mRNA", "increases stability and assists nuclear export", ["codes for lysine amino acids", "replaces all introns during splicing", "directs DNA replication origin firing"], "Polyadenylation protects 3' end from degradation.", "Poly-A is not translated into amino acids.", "C3.3k", "Explaining poly-A tail function", "Easy", 70),
        ("A silent (synonymous) point mutation", "may not change the amino acid due to code degeneracy", ["always changes protein folding catastrophically", "deletes an entire chromosome", "prevents RNA polymerase from binding always"], "Third-base wobble often allows same amino acid despite base change.", "Silent mutations can still affect splicing but often preserve amino acid.", "C3.6k", "Classifying silent mutations", "Medium", 85),
        ("A missense mutation", "substitutes one amino acid for another in the polypeptide", ["introduces a premature stop codon always", "has no effect on protein sequence ever", "duplicates an entire gene cluster"], "Missense changes one codon to code different amino acid.", "Nonsense creates stop; missense changes amino acid.", "C3.6k", "Classifying missense mutations", "Easy", 65),
        ("Reverse transcriptase in retroviruses synthesizes", "DNA from an RNA template", ["RNA from protein template", "lipids from carbohydrate template", "DNA without any template molecule"], "Retroviruses convert viral RNA genome to DNA for host integration.", "Normal transcription is DNA→RNA, not RNA→DNA.", "C3.2k", "Describing reverse transcription", "Medium", 90),
        ("DNA fingerprinting using STR analysis compares", "variable number tandem repeats between individuals", ["only mitochondrial ribosomes", "the entire genome sequence of every cell identically", "amino acid sequences of all haemoglobin molecules only"], "STR alleles differ in repeat count, providing individual-specific profiles.", "STRs are non-coding repetitive DNA markers.", "C3.4k", "Explaining STR-based DNA fingerprinting", "Medium", 90),
        ("A restriction enzyme cuts DNA at", "specific recognition sequences producing defined fragments", ["random locations without any sequence specificity", "only RNA polymerase binding sites during transcription", "centromeres during every mitosis automatically"], "Restriction endonucleases recognize palindromic sequences.", "Specificity is key to molecular cloning.", "C3.4k", "Describing restriction enzyme action", "Easy", 70),
        ("A recombinant plasmid contains", "foreign DNA inserted into a bacterial plasmid vector", ["only viral RNA without DNA", "human ribosomes for translation in nucleus", "meiotic spindles for chromosome separation"], "Vectors carry inserted genes into host bacteria for replication/expression.", "Plasmids are DNA vectors, not ribosome structures.", "C3.4k", "Defining recombinant plasmid", "Easy", 70),
        ("Gene therapy aims to", "introduce functional genes to compensate for defective alleles", ["eliminate all allelic variation in populations", "prevent meiosis in somatic cells", "replace mitosis with binary fission in humans"], "Therapeutic genes are delivered via vectors to restore function.", "Gene therapy targets defective genes, not meiosis.", "C3.4k", "Explaining gene therapy purpose", "Easy", 75),
        ("Epigenetic methylation of DNA can", "silence gene expression without changing nucleotide sequence", ["change the primary DNA sequence permanently", "replace transcription with DNA replication", "cause immediate frameshift in all genes"], "Methyl groups on cytosine often repress transcription.", "Epigenetics modifies expression, not primary sequence.", "C3.5k", "Explaining DNA methylation epigenetic effect", "Hard", 110),
        ("A lac operon in bacteria is induced when", "lactose is present, relieving repression of transcription", ["glucose binds the operator directly always", "RNA polymerase is permanently absent from bacteria", "all genes are always transcribed at maximum rate"], "Lactose/allolactose inactivates repressor, allowing lac gene transcription.", "Glucose preference involves catabolite repression, separate mechanism.", "C3.5k", "Explaining lac operon induction", "Hard", 115),
        ("A nonsense suppressor tRNA might", "read through a stop codon inserting an amino acid instead of terminating", ["delete the entire chromosome 21", "prevent all translation from ever starting", "convert DNA into protein without RNA"], "Suppressor tRNAs mutate anticodon to pair with stop codon, extending chain.", "Suppressors affect termination, not DNA structure.", "C3.6k", "Explaining nonsense suppressor mechanism", "Hard", 120),
        ("Sickle cell anemia involves a point mutation in the beta-globin gene changing", "glutamic acid to valine at position 6", ["methionine to stop codon at position 1 always", "entire deletion of chromosome 11", "conversion of haemoglobin to insulin"], "GAG→GTG substitutes valine, creating HbS with altered shape.", "Single amino acid change causes sickling under low O2.", "C3.6k", "Describing sickle cell molecular basis", "Medium", 90),
        ("BRCA1 mutations increase cancer risk because they impair", "DNA repair pathways for double-strand breaks", ["all mitosis in neurons exclusively", "digestion of proteins in the stomach", "secretion of insulin from beta cells"], "BRCA1 participates in homologous recombination repair; loss increases mutation accumulation.", "BRCA1 is DNA repair, not digestive function.", "C3.6k", "Relating tumour suppressor mutations to cancer", "Hard", 115),
        ("A karyotype of a cancer cell might show aneuploidy because", "checkpoint failures allow division with incorrect chromosome segregation", ["meiosis occurs in all liver cells normally", "DNA never replicates in cancer cells", "crossing over prevents all division"], "Cancer often exhibits chromosomal instability from checkpoint defects.", "Cancer involves mitotic errors, not routine meiosis in somatic cells.", "C3.6k", "Explaining aneuploidy in cancer cells", "Medium", 95),
        ("Homology among genes in different species suggests", "shared evolutionary ancestry", ["the genes have no functional relationship ever", "convergent evolution with no common origin always", "identical chromosomal location on Y in all species"], "Sequence similarity reflects descent from common ancestral gene.", "Homology indicates common ancestry, not random similarity.", "C3.7k", "Interpreting gene homology", "Medium", 85),
        ("A phylogenetic tree based on mitochondrial DNA sequences helps determine", "evolutionary relationships and maternal lineage patterns", ["only the blood type of living individuals", "the rate of photosynthesis in plants exclusively", "daily hormone cycles in teenagers"], "mtDNA evolves at measurable rate useful for phylogeny and maternal line tracing.", "mtDNA is not used for ABO blood typing.", "C3.7k", "Applying mtDNA to evolutionary analysis", "Medium", 90),
    ]
    # Fix the duplicate/broken item - remove the "Actually fix" entry and keep clean version
    clean_items = [it for it in items if not it[0].startswith("Actually fix")]
    for qt, ans, dist, expl, mis, oc, skill, diff, time in clean_items:
        s.append(mc(qt, ans, dist, expl, mis, topic=TOPIC, outcome_code=oc,
                    skill_tested=skill, difficulty=diff, estimated_time_seconds=time))

    s += [
        nr("A DNA sample is 22% guanine. What percent is adenine? Record the two-digit answer.", "28",
           "Chargaff: G=C. With G=22%, C=22%. A+T=100-44=56%. A=T=28%.",
           "Students subtract 22 from 100 without halving.",
           topic=TOPIC, outcome_code="C3.1k", skill_tested="Calculating adenine from guanine content",
           difficulty="Medium", estimated_time_seconds=85),
        nr("Cross AaBb × aabb. What fraction of offspring show both dominant traits? Express as decimal to two places.", "0.25",
           "Each gene segregates independently: 1/2 dominant for each → 1/4 both dominant.",
           "Students add probabilities instead of multiplying.",
           topic=TOPIC, outcome_code="C2.2k", skill_tested="Calculating dihybrid test cross probability",
           difficulty="Hard", estimated_time_seconds=110),
        nr("How many possible codons exist in the genetic code? Record the two-digit answer.", "64",
           "Each of three positions has 4 options: 4×4×4=64 codons.",
           "Students answer 20 (number of amino acids) or 61.",
           topic=TOPIC, outcome_code="C3.3k", skill_tested="Calculating number of codons",
           difficulty="Easy", estimated_time_seconds=55),
        wr("Describe how a deletion of two base pairs in the middle of an open reading frame can affect the resulting protein.",
           "Deleting two bases shifts the reading frame, altering every subsequent codon. A premature stop codon may appear, producing a truncated nonfunctional protein. If translation continues, the amino acid sequence is entirely wrong downstream, typically eliminating normal function.",
           "Marking guide: (1) Frameshift described — 2 marks. (2) Downstream codon changes — 2 marks. (3) Functional consequence — 2 marks.",
           "Students claim only one amino acid changes.",
           topic=TOPIC, outcome_code="C3.6k", skill_tested="Explaining deletion mutation protein effects",
           difficulty="Medium", estimated_time_seconds=260),
        wr("Explain how gel electrophoresis and PCR could be used together to confirm whether two individuals share a specific DNA marker.",
           "PCR amplifies the target region using specific primers. Gel electrophoresis separates products by size. Matching band positions indicate identical allele sizes; different migration indicates different alleles.",
           "Marking guide: (1) PCR amplification — 2 marks. (2) Gel separation — 2 marks. (3) Band comparison — 2 marks.",
           "Students describe techniques without connecting them.",
           topic=TOPIC, outcome_code="C3.4k", skill_tested="Integrating PCR and electrophoresis techniques",
           difficulty="Hard", estimated_time_seconds=280),
    ]
    return s
