"""Unit D: Population and Community Dynamics — original Biology 30 questions."""

from .helpers import mc, nr, wr

TOPIC = "Population and Community Dynamics"


def questions():
    q = [
        mc(
            "A population is best defined as",
            "all individuals of the same species living in a defined area at a given time",
            ["all organisms of every species in a biome globally", "only the dominant predators in an ecosystem", "the physical habitat without any living organisms"],
            "Population ecology focuses on one species within a specific geographic area.",
            "Community includes multiple species; population is single species.",
            topic=TOPIC, outcome_code="D1.1k",
            skill_tested="Defining biological population",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "The gene pool of a population refers to",
            "the total collection of alleles present in all individuals",
            ["only dominant alleles that are expressed phenotypically", "the mitochondria inherited from fathers", "the food web connecting producers and consumers"],
            "Gene pool encompasses every allele frequency for all gene loci in the population.",
            "Recessive alleles are part of the gene pool even when not expressed.",
            topic=TOPIC, outcome_code="D1.1k",
            skill_tested="Defining gene pool concept",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Hardy-Weinberg equilibrium assumes",
            "no mutation, no migration, large population, random mating, and no natural selection",
            ["constant natural selection favouring recessive alleles always", "small population size with frequent genetic drift only", "non-random mating increasing homozygosity always"],
            "Five conditions (no evolution factors) must hold for allele frequencies to remain constant generation to generation.",
            "Natural selection violates Hardy-Weinberg assumptions.",
            topic=TOPIC, outcome_code="D1.2k",
            skill_tested="Stating Hardy-Weinberg assumptions",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "In Hardy-Weinberg, if $p$ is the frequency of allele A and $q$ of allele a, the expected frequency of genotype Aa is",
            "$2pq$",
            ["$p^2$", "$q^2$", "$pq$"],
            "Heterozygote frequency under HW equilibrium is $2pq$.",
            "$p^2$ is AA homozygous; $q^2$ is aa homozygous.",
            topic=TOPIC, outcome_code="D1.2k",
            skill_tested="Applying Hardy-Weinberg heterozygote frequency",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "Genetic drift has the strongest effect when",
            "population size is small",
            ["population size is infinitely large", "no alleles exist in the gene pool", "Hardy-Weinberg equilibrium is perfectly met"],
            "Random sampling error in allele transmission disproportionately affects small populations.",
            "Large populations buffer against drift.",
            topic=TOPIC, outcome_code="D1.3k",
            skill_tested="Explaining conditions favouring genetic drift",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "The founder effect is a form of",
            "genetic drift when a small group establishes a new population",
            ["directional selection increasing fitness always", "competitive exclusion between two species", "primary succession on bare rock"],
            "Founders carry only a subset of original population alleles, altering frequencies.",
            "Founder effect is drift, not selection.",
            topic=TOPIC, outcome_code="D1.3k",
            skill_tested="Defining founder effect",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "A bottleneck event reduces genetic diversity because",
            "surviving individuals carry limited allelic variation into the recovered population",
            ["mutation rate drops to zero permanently", "all recessive alleles become dominant", "gene flow increases from many new migrants always"],
            "Catastrophic reduction in population size randomly eliminates many alleles.",
            "Bottlenecks decrease, not increase, diversity initially.",
            topic=TOPIC, outcome_code="D1.3k",
            skill_tested="Explaining genetic bottleneck consequences",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Directional selection shifts the phenotype distribution because",
            "individuals at one extreme have higher fitness",
            ["all phenotypes have exactly equal survival always", "only heterozygotes are selected against every generation", "mutation stops occurring entirely"],
            "Directional selection favours one extreme trait value, moving the population mean.",
            "Stabilizing selection favours intermediates, not extremes.",
            topic=TOPIC, outcome_code="D1.4k",
            skill_tested="Describing directional selection",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Stabilizing selection is common for traits like",
            "human birth weight, where intermediate weights have highest survival",
            ["peppered moth colour during industrial pollution only", "antibiotic resistance increasing over every generation without limit", "sexual selection for extreme tail length always"],
            "Stabilizing selection reduces phenotypic variance around an optimal intermediate.",
            "Directional selection on moth colour is a classic directional, not stabilizing, example.",
            topic=TOPIC, outcome_code="D1.4k",
            skill_tested="Identifying stabilizing selection examples",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Disruptive selection can lead to",
            "two distinct phenotypic groups when extremes are favoured over intermediates",
            ["a single peak shifting in one direction only", "complete Hardy-Weinberg equilibrium in one generation", "loss of all genetic variation immediately"],
            "Disruptive selection favours both extremes, potentially driving speciation.",
            "Directional selection shifts one peak; disruptive splits into two.",
            topic=TOPIC, outcome_code="D1.4k",
            skill_tested="Describing disruptive selection outcomes",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Speciation through allopatric isolation occurs when",
            "geographic barriers separate populations that diverge genetically",
            ["species interbreed freely in the same habitat without barriers", "gene flow increases between two subpopulations", "all mutations are immediately lethal"],
            "Physical separation prevents gene flow, allowing independent evolution.",
            "Sympatric speciation occurs without geographic separation.",
            topic=TOPIC, outcome_code="D1.2k",
            skill_tested="Explaining allopatric speciation",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "In a community, predation differs from parasitism because predation typically",
            "kills the prey individual directly for consumption",
            ["always benefits both species equally over time", "never involves one organism living on or in another", "only occurs between plants and fungi"],
            "Predators usually kill prey; parasites often feed without immediate host death.",
            "Parasitism usually does not kill host immediately.",
            topic=TOPIC, outcome_code="D2.1k",
            skill_tested="Distinguishing predation and parasitism",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Mutualism is an interaction where",
            "both species benefit from the association",
            ["one benefits and the other is harmed", "one benefits and the other is unaffected", "both species are harmed equally"],
            "Mutualism (+/+) benefits both participants (e.g., mycorrhizae and plants).",
            "Commensalism is +/0; parasitism is +/-.",
            topic=TOPIC, outcome_code="D2.1k",
            skill_tested="Defining mutualism",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "Commensalism is characterized by",
            "one organism benefiting and the other unaffected",
            ["both organisms being harmed", "both organisms benefiting equally always", "one organism killing the other immediately"],
            "Commensalism (+/0): one benefits, one neutral (e.g., barnacles on whales).",
            "Mutualism requires benefit to both.",
            topic=TOPIC, outcome_code="D2.1k",
            skill_tested="Defining commensalism",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "Interspecific competition occurs when",
            "two species require the same limited resource",
            ["members of the same species fight only within a clutch", "predators always benefit prey populations", "commensal species exchange nutrients equally"],
            "Different species competing for shared resources can limit each other's growth (competitive exclusion principle).",
            "Intraspecific competition is within a species.",
            topic=TOPIC, outcome_code="D2.1k",
            skill_tested="Defining interspecific competition",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "A keystone species has disproportionate impact because",
            "its removal causes major community structure changes",
            ["it is always the most abundant species numerically", "it never interacts with other trophic levels", "it only exists at the bottom of food chains"],
            "Keystone species (e.g., sea otters) maintain community balance despite lower biomass.",
            "Abundance does not define keystone status.",
            topic=TOPIC, outcome_code="D2.3k",
            skill_tested="Explaining keystone species concept",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Primary succession begins on",
            "substrate with no soil, such as bare rock after volcanic eruption",
            ["previously forested soil with existing seed bank", "agricultural fields abandoned for one season only", "coral reefs with established diverse communities"],
            "Primary succession builds soil and communities from scratch on lifeless substrate.",
            "Secondary succession follows disturbance where soil remains.",
            topic=TOPIC, outcome_code="D2.3k",
            skill_tested="Distinguishing primary and secondary succession",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Secondary succession after a forest fire progresses faster than primary succession because",
            "soil and seed banks often remain available",
            ["no sunlight reaches the ground ever", "all nutrients are permanently removed from Earth", "pioneer species cannot colonize disturbed areas"],
            "Existing soil, nutrients, and propagules accelerate community recovery.",
            "Fires may open canopy increasing light for pioneers.",
            topic=TOPIC, outcome_code="D2.3k",
            skill_tested="Explaining rapid secondary succession",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "A climax community is",
            "a relatively stable end stage of succession in a given climate",
            ["the first pioneer species to colonize bare rock only", "a community that never changes regardless of disturbance", "always dominated by a single bacterial species"],
            "Climax communities persist until major disturbance resets succession.",
            "Climax can be disrupted; it is not permanently unchanging.",
            topic=TOPIC, outcome_code="D2.3k",
            skill_tested="Defining climax community",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Exponential population growth occurs when",
            "resources are unlimited and growth rate is proportional to population size",
            ["carrying capacity limits growth immediately from start", "death rate always exceeds birth rate", "immigration is zero in all populations always"],
            "Exponential growth shows a J-shaped curve: $dN/dt = rN$.",
            "Logistic growth applies when carrying capacity limits population.",
            topic=TOPIC, outcome_code="D3.1k",
            skill_tested="Describing exponential growth conditions",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Logistic growth differs from exponential growth because logistic growth",
            "approaches carrying capacity ($K$) as growth rate slows",
            ["continues indefinitely without any upper limit", "has zero birth rate at all times", "ignores environmental resistance factors"],
            "Logistic model: $dN/dt = rN(1-N/K)$ produces S-shaped curve leveling at $K$.",
            "Exponential growth has no carrying capacity term.",
            topic=TOPIC, outcome_code="D3.1k",
            skill_tested="Comparing exponential and logistic growth",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Carrying capacity ($K$) represents",
            "the maximum population size an environment can sustain long-term",
            ["the minimum population before extinction always", "the birth rate minus immigration only", "the number of predators in a food web exclusively"],
            "$K$ reflects resource limits including food, space, and nesting sites.",
            "Carrying capacity is environmental limit, not minimum viable population.",
            topic=TOPIC, outcome_code="D3.1k",
            skill_tested="Defining carrying capacity",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "A survivorship Type I curve (high survival early, mortality later) is typical of",
            "large mammals with few offspring and high parental care",
            ["fish producing thousands of eggs with high early mortality", "insects with constant mortality rate across ages", "bacteria dividing exponentially without aging"],
            "Type I: humans, elephants — most survive to old age then die.",
            "Type III shows high early mortality (many fish, plants).",
            topic=TOPIC, outcome_code="D3.4k",
            skill_tested="Interpreting survivorship curve types",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "r-selected species typically have",
            "many offspring, little parental care, and rapid maturation",
            ["few offspring with extensive parental investment", "very slow population growth always at carrying capacity", "extremely long lifespans with one offspring per lifetime always"],
            "r-strategists maximize reproductive rate in unstable environments.",
            "K-selected species have few offspring and high care.",
            topic=TOPIC, outcome_code="D3.4k",
            skill_tested="Describing r-selected life history traits",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "K-selected species are most likely to thrive when",
            "population is near carrying capacity in a stable environment",
            ["environment fluctuates wildly with unlimited resources always", "no competition exists for any resource", "mutation rate is zero in all organisms"],
            "K-strategists compete efficiently at high density near $K$.",
            "r-selection favours unstable, not stable, high-resource conditions.",
            topic=TOPIC, outcome_code="D3.4k",
            skill_tested="Describing K-selected life history strategy",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        nr(
            "In a population, allele A has frequency $p=0.6$. What is the expected frequency of genotype aa if Hardy-Weinberg applies? Express as decimal to two places.",
            "0.16",
            "$q = 1 - 0.6 = 0.4$. $q^2 = 0.16$.",
            "Students calculate $2pq$ (heterozygote) instead of $q^2$.",
            topic=TOPIC, outcome_code="D1.2k",
            skill_tested="Calculating homozygous recessive frequency from allele frequency",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        nr(
            "A population grows from $500$ to $680$ individuals in one year. What is the net growth in individuals? Record the three-digit answer.",
            "180",
            "$680 - 500 = 180$ individuals.",
            "Students record final population size instead of change.",
            topic=TOPIC, outcome_code="D3.2k",
            skill_tested="Calculating absolute population growth",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        wr(
            "Explain how gene flow, genetic drift, and natural selection can each cause allele frequency changes in a population, providing one example of each.",
            "Gene flow: migration introduces new alleles (e.g., pollen from distant plants). Genetic drift: random allele loss in small populations (e.g., founder effect on an island). Natural selection: differential survival/reproduction (e.g., antibiotic resistance in bacteria). All change gene pool frequencies over generations.",
            "Marking guide: (1) Gene flow defined with example — 2 marks. (2) Genetic drift defined with example — 2 marks. (3) Natural selection defined with example — 2 marks.",
            "Students describe evolution generally without distinguishing mechanisms.",
            topic=TOPIC, outcome_code="D1.2k",
            skill_tested="Comparing mechanisms of microevolution",
            difficulty="Hard", estimated_time_seconds=280,
        ),
        wr(
            "A lake ecosystem loses its top predator due to overfishing. Predict two ecological changes that may follow and explain them using community ecology concepts.",
            "Without predators, mesopredator or herbivore populations may increase (trophic cascade), reducing primary producers or smaller prey. Competitive relationships may shift as former prey species increase. Biodiversity may decline if one species dominates (competitive exclusion) or increase temporarily before re-equilibration.",
            "Marking guide: (1) First predicted change with mechanism — 3 marks. (2) Second predicted change with mechanism — 3 marks. Must reference ecological concepts (trophic cascade, competition, etc.).",
            "Students predict changes without linking to population or community interactions.",
            topic=TOPIC, outcome_code="D2.3k",
            skill_tested="Applying trophic cascade reasoning to ecosystem disturbance",
            difficulty="Hard", estimated_time_seconds=300,
        ),
    ]
    q += _supplement()
    return q


def _supplement():
    s = []
    items = [
        ("Biotic potential refers to", "the maximum reproductive capacity under ideal conditions", ["the number of predators in an ecosystem only", "the rate of soil formation on bare rock", "the total biomass of decomposers exclusively"], "Biotic potential is theoretical maximum growth rate with unlimited resources.", "Carrying capacity is environmental limit, not biotic potential.", "D3.1k", "Defining biotic potential", "Easy", 65),
        ("Density-dependent factors regulating population include", "competition for food and disease transmission", ["volcanic eruptions affecting all populations equally regardless of size", "random lightning strikes on individual trees scattered sparsely", "solar flares with no biological interaction"], "Density-dependent factors intensify as population density increases.", "Catastrophic abiotic events are often density-independent.", "D3.3k", "Identifying density-dependent factors", "Medium", 85),
        ("Density-independent factors include", "severe drought or wildfire affecting population regardless of size", ["territorial aggression increasing with crowding", "parasite spread proportional to host density", "competition for nesting sites as population grows"], "Density-independent factors impact proportionally at any population size.", "Territoriality increases with density — density-dependent.", "D3.3k", "Identifying density-independent factors", "Medium", 85),
        ("Immigration and emigration affect population size by", "changing the number of individuals entering or leaving the population", ["altering mutation rates in DNA polymerase", "changing chromosome number during meiosis", "eliminating the need for carrying capacity"], "Population change: births + immigration − deaths − emigration.", "Demographics affect N; they do not change meiotic chromosome number.", "D3.2k", "Explaining immigration and emigration effects", "Easy", 65),
        ("A food web is more realistic than a food chain because it", "shows multiple interconnected feeding relationships", ["includes only producers and one herbivore", "ignores decomposers completely always", "assumes energy increases at each trophic level"], "Food webs depict complex feeding links among many species.", "Energy decreases (about 10% rule) at higher trophic levels.", "D2.2k", "Comparing food webs and food chains", "Easy", 70),
        ("Approximately 10% of energy transfers between trophic levels because", "most energy is lost as heat through cellular respiration and incomplete consumption", ["producers create energy de novo from nothing", "all energy is recycled with 100% efficiency", "decomposers return 90% energy to carnivores directly"], "Second law of thermodynamics: energy dissipates as heat at each transfer.", "Energy is not created by producers from nothing; it is converted from sunlight.", "D2.2k", "Explaining energy transfer efficiency between trophic levels", "Medium", 90),
        ("Biomagnification of DDT in apex predators occurs because", "persistent toxins accumulate at higher concentrations up the food chain", ["producers metabolize all toxins completely before any transfer", "toxins become less concentrated at each higher trophic level", "decomposers prevent any chemical from entering food webs"], "Lipophilic persistent pollutants concentrate in top consumers.", "Biomagnification increases, not decreases, concentration upward.", "D2.1sts", "Explaining biomagnification in food webs", "Medium", 95),
        ("Invasive species often disrupt communities because they", "lack natural predators and may outcompete native species", ["always increase biodiversity in every ecosystem", "immediately form mutualistic relationships with all natives", "reduce their own growth rate in new habitats voluntarily"], "Invasives can dominate resources and alter habitats, reducing native fitness.", "Invasives often decrease, not increase, native biodiversity.", "D2.3k", "Analyzing invasive species community impact", "Medium", 90),
        ("Edge effect in fragmented habitats can", "alter species composition and increase predation or parasitism along boundaries", ["have no impact on interior forest species ever", "only benefit deep-interior specialist species", "eliminate all abiotic factors from ecosystems"], "Habitat edges expose interior species to different microclimate and predators.", "Edge effects change community structure; they are not neutral.", "D2.3k", "Explaining habitat edge effects", "Hard", 110),
        ("Nitrogen fixation by bacteria benefits ecosystems by", "converting atmospheric N$_2$ to ammonia usable by plants", ["removing all nitrogen from soil permanently", "producing oxygen from nitrogen gas directly", "preventing any decomposition in soil"], "Nitrogen fixers (e.g., Rhizobium) enrich soil nitrogen for producers.", "Nitrogen fixation adds usable nitrogen; it does not remove it.", "D2.2k", "Describing nitrogen fixation ecological role", "Medium", 85),
        ("Mycorrhizal fungi form mutualistic associations with plant roots by", "extending nutrient absorption while receiving carbohydrates from the plant", ["killing root cells to parasitize all stored starch", "fixing atmospheric nitrogen without any plant involvement always", "preventing plants from absorbing any water"], "Fungi increase phosphorus uptake; plants supply sugars — mutualism.", "Mycorrhizae are mutualistic, not purely parasitic on roots.", "D2.1k", "Explaining mycorrhizal mutualism", "Easy", 75),
        ("Camouflage in prey species is an example of an adaptation resulting from", "natural selection favouring individuals matching their environment", ["genetic drift in infinitely large populations only", "Hardy-Weinberg equilibrium without any evolution", "commensalism where predators are unaffected"], "Predation pressure selects cryptic coloration in prey.", "Camouflage is adaptation from selection, not drift in infinite populations.", "D1.4k", "Relating camouflage to natural selection", "Easy", 70),
        ("Industrial melanism in peppered moths demonstrated", "directional selection favouring dark morphs on soot-covered trees", ["stabilizing selection for intermediate pink moths only", "no change in allele frequencies over time", "complete loss of all genetic variation in one generation"], "Dark moths had survival advantage during industrial pollution era — directional selection.", "This is classic directional, not stabilizing, selection.", "D1.4k", "Interpreting industrial melanism as selection example", "Medium", 85),
        ("Antibiotic resistance in bacteria spreading through a hospital illustrates", "natural selection acting on heritable variation in short time frames", ["Lamarckian inheritance of acquired traits without genes", "Hardy-Weinberg equilibrium in a closed system", "complete absence of mutation in bacterial populations"], "Resistant bacteria survive antibiotic treatment and reproduce preferentially.", "Resistance involves genetic variation and selection, not acquired inheritance only.", "D1.4k", "Applying natural selection to antibiotic resistance", "Medium", 90),
        ("Mark-recapture population estimation uses the proportion of marked individuals in a second sample to estimate total population size.", "proportion of marked in recapture sample equals proportion marked in total population", ["only birth rate divided by death rate", "carrying capacity multiplied by growth rate exclusively", "allele frequency times heterozygosity only"], "Lincoln-Petersen method: if 10% of recaptured animals are marked, marked release represents 10% of total population.", "Mark-recapture estimates population size, not allele frequency directly.", "D3.3s", "Applying mark-recapture population estimation", "Hard", 120),
        ("A J-shaped growth curve on a graph indicates", "exponential growth with resources not yet limiting", ["population at carrying capacity with zero growth", "immediate population crash to extinction always", "logistic growth leveling at K from the start"], "J-curve shows accelerating growth characteristic of exponential phase.", "S-curve indicates logistic approach to K.", "D3.1k", "Interpreting J-shaped population growth curve", "Easy", 70),
        ("An S-shaped growth curve indicates", "logistic growth approaching carrying capacity", ["exponential growth without limits forever", "population declining linearly to zero always", "no births occurring throughout the time period"], "S-curve: rapid growth slows as $N$ approaches $K$.", "J-curve, not S-curve, shows unchecked exponential growth.", "D3.1k", "Interpreting S-shaped logistic growth curve", "Easy", 70),
        ("Per capita growth rate $r$ is defined as", "birth rate minus death rate per individual per unit time", ["total population size divided by carrying capacity only", "number of species in a community", "energy transfer between trophic levels"], "$r$ measures per-individual contribution to population change.", "Per capita rate differs from absolute population change.", "D3.2k", "Defining per capita growth rate", "Medium", 80),
        ("A population at carrying capacity has growth rate approximately", "zero (births ≈ deaths)", ["maximally exponential with no limiting factors", "negative always leading to immediate extinction", "infinite due to unlimited resources"], "At $K$, environmental resistance balances reproduction; net growth nears zero.", "Exponential growth occurs far below $K$ with ample resources.", "D3.1k", "Describing population dynamics at carrying capacity", "Medium", 85),
        ("Ecological footprint measures", "human demand on ecosystem resources and waste absorption relative to Earth's capacity", ["only the number of species in a rainforest", "the rate of DNA replication in human cells", "action potential frequency in motor neurons"], "Footprint quantifies sustainability of consumption patterns.", "Ecological footprint is resource accounting, not cellular physiology.", "D2.1sts", "Defining ecological footprint STS concept", "Easy", 75),
        ("Sustainable resource management aims to", "meet present needs without compromising future generations' ability to meet theirs", ["exploit all resources immediately for maximum short-term profit only", "eliminate all human technology from ecosystems", "prevent any change in community composition ever"], "Sustainability balances use and regeneration for long-term ecosystem health.", "Unlimited exploitation contradicts sustainability principles.", "D2.1sts", "Explaining sustainable resource management principle", "Easy", 70),
    ]
    for qt, ans, dist, expl, mis, oc, skill, diff, time in items:
        s.append(mc(qt, ans, dist, expl, mis, topic=TOPIC, outcome_code=oc,
                    skill_tested=skill, difficulty=diff, estimated_time_seconds=time))

    s += [
        nr("Order ecological succession stages on bare rock: (1) lichens and mosses, (2) climax forest, (3) grasses and shrubs, (4) small trees. Record all four digits.", "1342",
           "Pioneer lichens/mosses (1), grasses/shrubs (3), small trees (4), climax forest (2).",
           "Climax placed before pioneer species.",
           topic=TOPIC, outcome_code="D2.3k", skill_tested="Sequencing primary succession stages",
           difficulty="Medium", estimated_time_seconds=80),
        nr("If $p=0.7$ for allele B, what is frequency of heterozygotes under Hardy-Weinberg? Express as decimal to two places.", "0.42",
           "$q=0.3$. $2pq = 2(0.7)(0.3) = 0.42$.",
           "Students calculate $p^2$ or $q^2$ instead.",
           topic=TOPIC, outcome_code="D1.2k", skill_tested="Calculating heterozygote frequency",
           difficulty="Medium", estimated_time_seconds=85),
        nr("Population $N_0=1200$, $N_1=1450$ after one year. Per capita growth rate $r$? Express as decimal to two places.", "0.21",
           "$r = (N_1 - N_0)/N_0 = 250/1200 = 0.208 \\approx 0.21$.",
           "Students divide $N_1/N_0$ without subtracting 1.",
           topic=TOPIC, outcome_code="D3.2k", skill_tested="Calculating per capita growth rate",
           difficulty="Hard", estimated_time_seconds=110),
        wr("Describe three ways human activities can reduce biodiversity in Alberta ecosystems and propose one scientifically sound mitigation strategy for each.",
           "Habitat fragmentation from agriculture/urbanization reduces gene flow and increases edge effects — mitigate with wildlife corridors. Pollution (e.g., nutrient runoff) causes eutrophication — mitigate with buffer zones and wastewater treatment. Overexploitation of species (overfishing/hunting) — mitigate with quotas based on population surveys.",
           "Marking guide: (1) Three distinct human impacts — 3 marks. (2) One valid mitigation per impact — 3 marks. Strategies must be scientifically plausible.",
           "Students list impacts without feasible mitigation strategies.",
           topic=TOPIC, outcome_code="D2.1sts", skill_tested="Analyzing human impact and mitigation on biodiversity",
           difficulty="Hard", estimated_time_seconds=300),
    ]
    return s
