"""Unit B: Reproduction and Development — original Biology 30 questions."""

from .helpers import mc, nr, wr

TOPIC = "Reproduction and Development"


def questions():
    q = [
        mc(
            "Spermatogenesis occurs in the",
            "seminiferous tubules of the testes",
            ["epididymis only", "prostate gland", "urethra lining"],
            "Primary spermatocytes divide in seminiferous tubules; mature sperm are stored and mature in the epididymis.",
            "The epididymis stores sperm but is not the primary site of spermatogenesis.",
            topic=TOPIC, outcome_code="B1.1k",
            skill_tested="Locating site of spermatogenesis",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "The role of Sertoli cells in the testes is to",
            "nourish developing sperm and form the blood-testis barrier",
            ["produce testosterone directly as Leydig cells do", "transport mature sperm to the urethra by peristalsis", "secrete FSH from the testes into the bloodstream"],
            "Sertoli cells support spermatogenesis and create a protected environment; Leydig cells produce testosterone.",
            "Testosterone production is attributed to Leydig cells, not Sertoli cells.",
            topic=TOPIC, outcome_code="B1.1k",
            skill_tested="Describing Sertoli cell function",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Leydig cells in the testes respond to LH by secreting",
            "testosterone",
            ["FSH", "estrogen exclusively without androgens", "progesterone for uterine lining maintenance"],
            "LH stimulates Leydig (interstitial) cells to produce testosterone, essential for sperm development and secondary sex characteristics.",
            "FSH acts on Sertoli cells, not Leydig cells.",
            topic=TOPIC, outcome_code="B1.2k",
            skill_tested="Linking LH to testosterone production",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "Oogenesis differs from spermatogenesis because oogenesis",
            "produces one functional ovum and polar bodies with unequal cytoplasmic division",
            ["produces four functional gametes of equal size", "occurs continuously from puberty throughout life in males and females equally", "does not involve meiosis"],
            "Oogenesis yields one large ovum and small polar bodies; spermatogenesis yields four functional sperm.",
            "Four equal gametes are produced in spermatogenesis, not oogenesis.",
            topic=TOPIC, outcome_code="B1.1k",
            skill_tested="Comparing oogenesis and spermatogenesis outcomes",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "The corpus luteum forms after ovulation and primarily secretes",
            "progesterone (and some estrogen)",
            ["FSH and LH from the ovary", "testosterone for endometrial shedding", "oxytocin for milk ejection"],
            "The corpus luteum maintains the uterine lining by producing progesterone during the luteal phase.",
            "FSH and LH are pituitary hormones, not ovarian corpus luteum products.",
            topic=TOPIC, outcome_code="B2.1k",
            skill_tested="Identifying corpus luteum hormone products",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "A surge in LH mid-cycle triggers",
            "ovulation",
            ["menstrual flow", "implantation of the blastocyst", "menopause"],
            "The LH surge causes the Graafian follicle to rupture and release the secondary oocyte.",
            "Menstrual flow follows progesterone drop if fertilization does not occur.",
            topic=TOPIC, outcome_code="B2.1k",
            skill_tested="Linking LH surge to ovulation",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "FSH in females stimulates",
            "follicle development and estrogen production from developing follicles",
            ["uterine contractions during labour exclusively", "corpus luteum degeneration at ovulation", "implantation of the embryo in the oviduct"],
            "FSH acts on ovarian follicles to promote maturation and estradiol secretion.",
            "Uterine contractions during labour involve oxytocin, not FSH.",
            topic=TOPIC, outcome_code="B2.1k",
            skill_tested="Describing FSH role in ovarian cycle",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "If fertilization does not occur, the corpus luteum degenerates, causing",
            "a drop in progesterone and onset of menstruation",
            ["an immediate LH surge and ovulation", "increased endometrial thickness indefinitely", "implantation in the fallopian tube"],
            "Without hCG from a blastocyst, the corpus luteum breaks down, progesterone falls, and the endometrium sloughs.",
            "LH surge occurs before ovulation, not after failed fertilization.",
            topic=TOPIC, outcome_code="B2.2k",
            skill_tested="Explaining menstrual cycle hormonal changes",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Human chorionic gonadotropin (hCG) is produced by",
            "the developing blastocyst after implantation",
            ["the anterior pituitary during the follicular phase", "the corpus luteum before ovulation", "Sertoli cells in the testes"],
            "Embryonic trophoblast cells secrete hCG, which maintains the corpus luteum in early pregnancy.",
            "Pituitary gonadotropins are FSH and LH, not hCG.",
            topic=TOPIC, outcome_code="B2.2k",
            skill_tested="Identifying source of hCG",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "The placenta functions to",
            "exchange gases and nutrients between maternal and fetal blood without direct mixing",
            ["produce sperm for subsequent pregnancies", "generate action potentials for fetal movement directly", "replace the function of all fetal organs permanently"],
            "The placenta facilitates diffusion of O$_2$, nutrients, and wastes across closely apposed maternal and fetal circulations.",
            "Fetal gonads develop independently; the placenta does not produce sperm.",
            topic=TOPIC, outcome_code="B2.2k",
            skill_tested="Describing placental exchange function",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "Barrier methods of contraception such as condoms primarily prevent pregnancy by",
            "blocking sperm from reaching the egg",
            ["inhibiting ovulation through hormone feedback", "destroying sperm DNA in the epididymis surgically", "preventing implantation after fertilization only"],
            "Barrier methods physically prevent sperm-egg contact. Hormonal methods inhibit ovulation.",
            "Hormonal contraception is confused with barrier mechanisms.",
            topic=TOPIC, outcome_code="B2.3k",
            skill_tested="Explaining barrier contraception mechanism",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "Oral contraceptives containing estrogen and progesterone primarily prevent pregnancy by",
            "inhibiting FSH and LH release to suppress ovulation",
            ["destroying all ovarian follicles permanently", "blocking fallopian tube peristalsis only without hormonal effects", "increasing testosterone in females to stop menstruation"],
            "Combined hormonal contraceptives use negative feedback on the pituitary to prevent the LH surge needed for ovulation.",
            "Permanent follicle destruction does not occur with standard oral contraceptives.",
            topic=TOPIC, outcome_code="B2.3k",
            skill_tested="Explaining hormonal contraception mechanism",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "In vitro fertilization (IVF) involves fertilizing an egg outside the body. A major STS consideration is that",
            "embryo selection and multiple implantations raise ethical questions about viability and resource access",
            ["IVF eliminates all genetic disorders in every embryo automatically", "IVF requires no hormonal stimulation of the ovaries", "IVF guarantees successful pregnancy in every cycle"],
            "IVF raises ethical issues about embryo status, selective implantation, and equitable access to expensive technology.",
            "IVF does not automatically correct all genetic conditions.",
            topic=TOPIC, outcome_code="B2.3k",
            skill_tested="Evaluating STS implications of reproductive technology",
            difficulty="Medium", estimated_time_seconds=95,
        ),
        mc(
            "Stem cells are significant in developmental biology because they",
            "can differentiate into specialized cell types",
            ["cannot divide after the embryonic stage", "always remain totipotent in adult tissues", "block all gene expression permanently"],
            "Stem cells divide and differentiate, giving rise to the diverse tissues of the developing organism.",
            "Adult stem cells are typically multipotent, not totipotent.",
            topic=TOPIC, outcome_code="B3.1k",
            skill_tested="Defining stem cell developmental significance",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Totipotent cells in early embryonic development can",
            "give rise to all embryonic and extraembryonic cell types",
            ["only form one specific tissue such as skin", "not divide after the morula stage", "only produce hormones of the endocrine system"],
            "Totipotent zygote and early blastomeres can form the entire organism including placental tissues.",
            "Pluripotent and multipotent cells have more restricted fates than totipotent cells.",
            topic=TOPIC, outcome_code="B3.1k",
            skill_tested="Distinguishing totipotency from other potency levels",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Cell differentiation during development is regulated by",
            "selective gene expression in response to internal and external signals",
            ["loss of all DNA from non-expressed cells", "random assignment without genetic control", "fusion of all embryonic cells into one cell type"],
            "Differentiation involves turning specific genes on or off, guided by transcription factors, hormones, and environmental cues.",
            "Differentiating cells retain the same genome; they do not lose DNA.",
            topic=TOPIC, outcome_code="B3.2k",
            skill_tested="Explaining gene regulation in differentiation",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Homeobox (Hox) genes are critical in development because they",
            "control the body plan along the anterior-posterior axis",
            ["determine blood type antigens on red blood cells", "code for all enzymes in cellular respiration", "prevent any mutation during DNA replication"],
            "Hox genes regulate spatial organization of structures during embryogenesis.",
            "Blood type is determined by different gene loci, not Hox genes.",
            topic=TOPIC, outcome_code="B3.2k",
            skill_tested="Describing Hox gene role in development",
            difficulty="Hard", estimated_time_seconds=110,
        ),
        mc(
            "Teratogens such as certain drugs or viruses during pregnancy can cause birth defects by",
            "disrupting normal developmental processes during critical periods",
            ["increasing the number of chromosomes in all adult cells", "preventing meiosis in the mother's ovaries after birth", "eliminating all stem cells in the mother permanently"],
            "Teratogens interfere with differentiation and organogenesis during sensitive developmental windows.",
            "Teratogens affect the developing embryo/fetus, not maternal meiosis post-birth.",
            topic=TOPIC, outcome_code="B3.3k",
            skill_tested="Explaining teratogen effects on development",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "The neural tube forms during development and eventually gives rise to the",
            "brain and spinal cord",
            ["heart and lungs exclusively", "skeletal muscle of the limbs only", "placenta and umbilical cord"],
            "Neurulation produces the neural tube, which develops into the central nervous system.",
            "Heart and lungs arise from other germ layer derivatives.",
            topic=TOPIC, outcome_code="B3.3k",
            skill_tested="Identifying derivatives of the neural tube",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Folic acid supplementation before and during early pregnancy helps prevent",
            "neural tube defects such as spina bifida",
            ["Down syndrome from trisomy 21", "colour blindness on the X chromosome", "Huntington disease from CAG repeats"],
            "Adequate folate supports DNA synthesis and neural tube closure. Chromosomal and single-gene disorders are not prevented by folate.",
            "Folic acid prevents closure defects, not aneuploidy.",
            topic=TOPIC, outcome_code="B3.3k",
            skill_tested="Relating folic acid to neural tube defect prevention",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "Apoptosis during embryonic development serves to",
            "remove unnecessary cells and sculpt organs",
            ["increase the total chromosome number in survivors", "prevent all cell division after birth", "replace meiosis in gamete formation"],
            "Programmed cell death shapes structures (e.g., digit separation) by eliminating cells that are no longer needed.",
            "Apoptosis removes cells; it does not alter chromosome number.",
            topic=TOPIC, outcome_code="B3.2k",
            skill_tested="Explaining role of apoptosis in morphogenesis",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Identical twins result from",
            "splitting of one embryo after fertilization",
            ["two separate eggs fertilized by two sperm", "fusion of two zygotes into one", "parthenogenesis without fertilization"],
            "Monozygotic twins arise from one zygote that divides into two embryos sharing identical DNA.",
            "Fraternal twins come from two eggs and two sperm.",
            topic=TOPIC, outcome_code="B3.1k",
            skill_tested="Distinguishing monozygotic and dizygotic twin origins",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "The morula stage of embryonic development precedes the blastocyst and is characterized by",
            "a solid ball of cells from cleavage divisions",
            ["implantation in the uterine wall already completed", "gastrulation forming three germ layers", "full organogenesis of all systems"],
            "The morula is a compact mass of blastomeres before fluid accumulation forms the blastocyst cavity.",
            "Gastrulation follows blastocyst formation and implantation.",
            topic=TOPIC, outcome_code="B3.1k",
            skill_tested="Identifying morula stage characteristics",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Gastrulation is a critical developmental process because it",
            "establishes the three primary germ layers",
            ["completes fertilization in the uterus", "produces four polar bodies", "duplicates the maternal mitochondrial genome only"],
            "Gastrulation forms ectoderm, mesoderm, and endoderm, which give rise to all tissues.",
            "Fertilization occurs before cleavage and morula stages.",
            topic=TOPIC, outcome_code="B3.2k",
            skill_tested="Explaining significance of gastrulation",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Ectoderm gives rise to tissues including",
            "epidermis and nervous system",
            ["lining of the digestive tract", "bone and muscle", "liver and pancreas"],
            "Ectoderm forms skin epidermis and neural tissue. Endoderm forms gut lining; mesoderm forms muscle and bone.",
            "Germ layer derivatives are commonly confused on exams.",
            topic=TOPIC, outcome_code="B3.2k",
            skill_tested="Matching germ layers to tissue derivatives",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Premature infants born at 24 weeks gestation face high risk because",
            "lungs and other organs may be insufficiently developed for extrauterine life",
            ["they have not yet undergone fertilization", "all stem cells have already differentiated irreversibly in the mother", "the placenta continues all fetal functions after birth without change"],
            "Extreme prematurity often involves immature surfactant production and incomplete organ maturation.",
            "A 24-week infant has long completed fertilization and early cleavage.",
            topic=TOPIC, outcome_code="B3.2k",
            skill_tested="Relating prematurity to organ development",
            difficulty="Easy", estimated_time_seconds=80,
        ),
        mc(
            "Surfactant produced by type II alveolar cells is essential for neonatal breathing because it",
            "reduces surface tension in alveoli to prevent collapse",
            ["increases blood glucose for muscle contraction", "blocks all gas exchange until adolescence", "stimulates closure of the foramen ovale immediately at birth"],
            "Surfactant lowers alveolar surface tension, enabling lung expansion. Premature infants may lack adequate surfactant.",
            "Gas exchange is essential from birth; surfactant enables it.",
            topic=TOPIC, outcome_code="B3.2k",
            skill_tested="Explaining surfactant role in lung function",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Menopause occurs when",
            "ovarian follicles are depleted and estrogen production declines significantly",
            ["the pituitary permanently stops producing all hormones", "the uterus is surgically removed in all females at age 50", "spermatogenesis ceases in females"],
            "Menopause reflects ovarian follicle exhaustion; FSH rises due to reduced estrogen feedback.",
            "Spermatogenesis is a male process; menopause is female-specific.",
            topic=TOPIC, outcome_code="B2.2k",
            skill_tested="Explaining physiological basis of menopause",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "Endometriosis involves",
            "endometrial tissue growing outside the uterus",
            ["failure of spermatogenesis in the testes", "trisomy of chromosome 21 in the embryo", "complete absence of progesterone from birth"],
            "Endometrial implants outside the uterus respond to hormones and cause pain and inflammation.",
            "Endometriosis is a uterine lining condition, not a chromosomal disorder.",
            topic=TOPIC, outcome_code="B2.2k",
            skill_tested="Defining endometriosis",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        nr(
            "Order sperm pathway structures after production: (1) epididymis, (2) seminiferous tubule, (3) vas deferens, (4) urethra. Record all four digits.",
            "2134",
            "Sperm form in seminiferous tubules (2), mature in epididymis (1), travel through vas deferens (3), exit via urethra (4).",
            "Students place epididymis before seminiferous tubules.",
            topic=TOPIC, outcome_code="B1.2k",
            skill_tested="Sequencing male reproductive tract pathway",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        nr(
            "Order menstrual cycle phases: (1) follicular, (2) ovulation, (3) luteal, (4) menstruation (if no pregnancy). Record all four digits.",
            "1234",
            "Follicular phase (1) precedes ovulation (2), followed by luteal phase (3), then menstruation (4) if no implantation.",
            "Menstruation is placed before ovulation in some incorrect sequences.",
            topic=TOPIC, outcome_code="B2.2k",
            skill_tested="Sequencing menstrual cycle phases",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        wr(
            "Describe the hormonal regulation of the ovarian cycle from the follicular phase through ovulation. "
            "Include the roles of FSH, estrogen, LH, and the corpus luteum.",
            "FSH stimulates follicle growth; developing follicles secrete increasing estrogen. Rising estrogen initially inhibits LH/FSH, then at high levels triggers a positive feedback LH surge causing ovulation. The ruptured follicle becomes the corpus luteum, secreting progesterone and estrogen to maintain the endometrium. If pregnancy does not occur, corpus luteum degenerates, progesterone drops, and a new cycle begins.",
            "Marking guide: (1) FSH and follicle development — 1 mark. (2) Estrogen rise and feedback — 2 marks. (3) LH surge and ovulation — 2 marks. (4) Corpus luteum progesterone role — 1 mark.",
            "Students omit the LH surge or confuse negative and positive feedback timing.",
            topic=TOPIC, outcome_code="B2.1k",
            skill_tested="Tracing hormonal control of ovarian cycle",
            difficulty="Hard", estimated_time_seconds=300,
        ),
        wr(
            "Explain how cell differentiation and development are influenced by genetic, endocrine, and environmental factors. "
            "Provide one specific example for each factor type.",
            "Genetic: Hox genes establish body segment identity along the anterior-posterior axis. Endocrine: maternal and fetal hormones (e.g., testosterone) direct development of reproductive structures. Environmental: teratogens such as alcohol during critical periods can disrupt neural tube closure, causing developmental abnormalities. All three interact — genotype provides the blueprint, hormones regulate timing, and environment can modify expression.",
            "Marking guide: (1) Genetic example with mechanism — 2 marks. (2) Endocrine example — 2 marks. (3) Environmental example — 2 marks. (4) Integration statement — 1 mark.",
            "Students provide only one factor type or list factors without specific examples.",
            topic=TOPIC, outcome_code="B3.2k",
            skill_tested="Integrating factors regulating development",
            difficulty="Hard", estimated_time_seconds=300,
        ),
    ]
    q += _unit_b_supplement()
    return q


def _unit_b_supplement():
    s = []
    items = [
        ("Progesterone during pregnancy is important primarily because it", "maintains the uterine lining and suppresses uterine contractions", ["triggers ovulation in the fetus", "stimulates spermatogenesis in the mother", "blocks all estrogen production completely"], "Progesterone supports endometrial maintenance and quiescence of myometrial contractions.", "Ovulation is inhibited, not triggered, during pregnancy.", "B2.2k", "Explaining progesterone role in pregnancy", "Easy", 70),
        ("The acrosome of a sperm cell contains enzymes that", "help penetrate the zona pellucida", ["generate ATP for flagellar movement only", "produce progesterone for the egg", "digest the sperm's own nucleus"], "Acrosomal enzymes digest glycoproteins of the zona pellucida during fertilization.", "Mitochondria in the midpiece supply energy, not the acrosome.", "B1.1k", "Describing acrosome function", "Medium", 85),
        ("The zona pellucida surrounding an egg", "triggers the cortical reaction after sperm binding to prevent polyspermy", ["produces testosterone for sperm motility", "is identical to the placenta in function", "prevents all contact between sperm and egg always"], "Sperm binding induces cortical granule release, hardening the zona to block additional sperm.", "Polyspermy prevention is an active post-fertilization response.", "B1.1k", "Explaining zona pellucida and cortical reaction", "Medium", 90),
        ("Implantation of the blastocyst normally occurs in the", "endometrium of the uterus", ["oviduct lining only", "cervical canal", "ovarian follicle wall"], "The blastocyst embeds in the uterine endometrium around day 6–7 post-fertilization.", "Ectopic pregnancy involves abnormal implantation outside the uterus.", "B2.2k", "Locating normal implantation site", "Easy", 65),
        ("The umbilical cord connects the fetus to the placenta and contains", "umbilical vessels carrying blood between fetus and placenta", ["maternal and fetal blood mixed in one vessel", "only nerves without any blood supply", "amniotic fluid for fetal breathing"], "Two umbilical arteries carry deoxygenated blood to the placenta; one vein returns oxygenated blood. Blood does not mix directly.", "Maternal and fetal blood are separated by placental barriers.", "B2.2k", "Describing umbilical cord structure", "Easy", 75),
        ("Amniotic fluid functions include", "cushioning the fetus and allowing movement for musculoskeletal development", ["providing oxygen through fetal lungs before birth", "replacing the placenta in the third trimester", "digesting waste in the fetal stomach"], "Amniotic fluid protects against mechanical injury and supports development; gas exchange is placental.", "Fetal lungs do not function for gas exchange before birth.", "B3.2k", "Explaining amniotic fluid functions", "Easy", 70),
        ("Parturition (birth) is initiated in part by", "oxytocin-stimulated uterine contractions with positive feedback", ["a permanent drop in all maternal hormones to zero", "implantation of the blastocyst in the cervix", "completion of spermatogenesis in the fetus"], "Oxytocin increases contractions, which stimulate more oxytocin release until delivery.", "Hormones coordinate birth; they do not all drop to zero before labour.", "B2.2k", "Explaining hormonal initiation of labour", "Medium", 90),
        ("Lactation after birth is maintained primarily by", "prolactin stimulating milk production and oxytocin enabling milk ejection", ["FSH stimulating milk ducts in the infant", "testosterone from the placenta permanently", "absence of all pituitary hormones"], "Prolactin promotes milk synthesis; oxytocin causes let-down reflex.", "FSH does not control lactation.", "B2.2k", "Describing hormonal control of lactation", "Medium", 85),
        ("A karyotype of a normal human female shows", "22 pairs of autosomes and XX sex chromosomes", ["22 pairs of autosomes and XY sex chromosomes", "23 pairs of autosomes only", "44 individual chromosomes without pairing"], "Females are 46,XX; males are 46,XY. Karyotypes display homologous pairs.", "XY is the male sex chromosome complement.", "B3.1k", "Interpreting female karyotype", "Easy", 65),
        ("Nondisjunction during meiosis can produce gametes with", "an abnormal number of chromosomes", ["always perfectly haploid sets only", "no functional genes on any chromosome", "mitochondrial DNA only"], "Failure of homologues or sister chromatids to separate causes aneuploidy (e.g., trisomy 21).", "Nondisjunction causes extra or missing chromosomes, not loss of all nuclear genes.", "B3.1k", "Explaining nondisjunction consequences", "Medium", 90),
        ("Assisted reproductive technology using donor eggs addresses infertility when", "the female cannot produce viable eggs but can carry a pregnancy", ["the male produces no sperm and no technology can help", "both partners have identical genetic disorders requiring no screening", "pregnancy is impossible with any uterus present"], "Donor oocytes allow gestation when ovarian function is absent but uterus is functional.", "Male factor infertility may use donor sperm or ICSI, not only donor eggs.", "B2.3k", "Evaluating donor egg technology application", "Medium", 95),
        ("Somatic cell nuclear transfer (cloning) raises STS concerns because", "it may blur ethical boundaries about personhood and identity", ["it has been proven to extend human lifespan to 200 years", "it requires no oocytes or surrogate uterus ever", "it eliminates all genetic variation in populations immediately"], "Cloning debates involve identity, consent, and societal implications beyond pure science.", "Cloning does not guarantee dramatic lifespan extension.", "B3.5k", "Analyzing STS issues in reproductive cloning", "Hard", 110),
        ("Induced pluripotent stem (iPS) cells are produced by", "reprogramming differentiated cells with specific transcription factors", ["fertilizing eggs with multiple sperm simultaneously", "removing all DNA from embryonic cells", "blocking apoptosis in cancer cells only"], "iPS technology resets differentiated cells to a pluripotent state using factors like Oct4 and Sox2.", "iPS cells are reprogrammed somatic cells, not products of polyspermy.", "B3.1k", "Describing iPS cell technology", "Hard", 115),
        ("The extraembryonic membrane called the chorion contributes to", "placenta formation and production of hCG early in pregnancy", ["spermatogenesis in the testes", "action potential conduction in neurons", "Hardy-Weinberg equilibrium in populations"], "Chorionic tissue forms the fetal portion of the placenta and secretes hCG.", "Extraembryonic membranes support embryonic development, not gametogenesis in adults.", "B2.2k", "Identifying chorion function", "Medium", 85),
        ("Syphilis during pregnancy is a concern because the pathogen can", "cross the placenta and infect the fetus", ["only affect maternal somatic cells without any fetal contact", "cure itself automatically at implantation", "stimulate extra chromosome segregation in sperm"], "Treponema pallidum can cause congenital syphilis with severe developmental consequences.", "Some pathogens cross placental barriers; syphilis is a classic example.", "B3.3k", "Explaining teratogenic infection risk", "Medium", 90),
        ("The process of capacitation of sperm occurs in the", "female reproductive tract and enables fertilization ability", ["seminiferous tubules before any sperm are produced", "placenta after implantation", "hypothalamus during puberty"], "Sperm must undergo membrane changes in the female tract before they can fertilize an egg.", "Sperm are produced inseminiferous tubules but capacitate after ejaculation.", "B1.1k", "Explaining sperm capacitation", "Medium", 85),
        ("Fraternal twins are genetically", "as similar as typical siblings (about 50% shared DNA on average)", ["100% genetically identical always", "unrelated with 0% shared DNA", "haploid like gametes"], "Dizygotic twins share the same average genetic similarity as ordinary siblings.", "100% identity describes monozygotic twins.", "B3.1k", "Comparing genetic relatedness of twin types", "Easy", 70),
        ("The enzyme telomerase is active in some stem cells and germ cells, which helps by", "maintaining chromosome end integrity during repeated divisions", ["removing all introns from every mRNA immediately", "converting RNA genomes to DNA in all somatic cells", "preventing any apoptosis during development"], "Telomerase extends telomeres, supporting continued division in stem and germ line cells.", "Telomerase does not process mRNA splicing.", "B3.1k", "Explaining telomerase role in cell division", "Hard", 110),
        ("Environmental factors such as maternal nutrition during pregnancy can", "influence fetal growth and long-term health outcomes", ["change the fetal chromosome number in all cells", "prevent all gene expression in the embryo", "eliminate the need for the placenta"], "Nutrient availability affects development and can predispose to adult conditions (developmental origins of health).", "Nutrition modulates expression and growth; it does not rewrite karyotype.", "B3.3k", "Relating maternal environment to fetal development", "Medium", 85),
    ]
    for qt, ans, dist, expl, mis, oc, skill, diff, time in items:
        s.append(mc(qt, ans, dist, expl, mis, topic=TOPIC, outcome_code=oc,
                    skill_tested=skill, difficulty=diff, estimated_time_seconds=time))

    s += [
        nr("A follicle measures $18$ mm when ovulation-ready and $6$ mm during early follicular phase. What is the increase in diameter in mm? Record the two-digit answer.", "12",
           "Increase = $18 - 6 = 12$ mm.", "Students record final size instead of difference.",
           topic=TOPIC, outcome_code="B2.1k", skill_tested="Calculating follicle growth", difficulty="Easy", estimated_time_seconds=60),
        nr("Embryonic development days: fertilization day $0$, implantation day $6$, heartbeat detectable day $22$. Record implantation day as one digit and heartbeat day as two digits (three digits total).", "622",
           "Implantation = $6$, heartbeat = $22$, combined $622$.", "Digit order reversed.",
           topic=TOPIC, outcome_code="B3.1k", skill_tested="Recording developmental milestone timing", difficulty="Medium", estimated_time_seconds=80),
        wr("Compare spermatogenesis and oogenesis in terms of timing of completion, number of functional gametes produced per meiosis, and cytoplasmic distribution.",
           "Spermatogenesis begins at puberty and continues throughout life, producing four functional sperm per primary spermatocyte with equal cytoplasmic division. Oogenesis begins before birth (arrested at prophase I), completes one ovum per month after puberty, yielding one functional ovum and polar bodies due to unequal cytokinesis that concentrates cytoplasm in the egg.",
           "Marking guide: (1) Timing contrast — 2 marks. (2) Gamete number per meiosis — 2 marks. (3) Cytoplasmic distribution — 2 marks.",
           "Students claim oogenesis produces four functional gametes like spermatogenesis.",
           topic=TOPIC, outcome_code="B1.1k", skill_tested="Comparing gametogenesis processes", difficulty="Medium", estimated_time_seconds=260),
        wr("Discuss one ethical, one economic, and one ecological consideration related to the use of hormonal contraceptives in society.",
           "Ethical: personal reproductive choice vs. cultural or religious objections to artificial hormone use. Economic: cost and accessibility of prescriptions and healthcare compared to potential savings from reduced unintended pregnancies. Ecological: trace hormones in wastewater may affect aquatic organism reproduction, raising environmental monitoring concerns.",
           "Marking guide: (1) Valid ethical consideration — 2 marks. (2) Economic consideration — 2 marks. (3) Ecological consideration — 2 marks. Each must be explained, not just named.",
           "Students list considerations without explaining the biology-STS connection.",
           topic=TOPIC, outcome_code="B2.3k", skill_tested="Analyzing STS dimensions of contraception", difficulty="Hard", estimated_time_seconds=280),
    ]
    return s
