"""Unit A: Nervous and Endocrine Systems — original Biology 30 questions."""

from .helpers import mc, nr, wr

TOPIC = "Nervous and Endocrine Systems"


def questions():
    q = []

    # --- A1: Nervous system structure and function ---
    q += [
        mc(
            "During an action potential in a myelinated axon, the rapid jumping of the impulse between nodes of Ranvier is called",
            "saltatory conduction",
            ["continuous conduction", "synaptic transmission", "refractory summation"],
            "Myelin insulates the axon except at nodes of Ranvier, forcing depolarization to jump between nodes. This saltatory conduction increases conduction speed.",
            "Students confuse saltatory conduction with continuous conduction along unmyelinated fibres.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Identifying mechanisms of nerve impulse transmission",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "A drug that blocks voltage-gated sodium channels in axon membranes would most directly prevent",
            "depolarization of the axon membrane",
            ["reuptake of neurotransmitter", "release of acetylcholine from vesicles", "hyperpolarization during repolarization"],
            "Voltage-gated sodium channels allow Na$^+$ influx during depolarization. Blocking them stops the rising phase of the action potential.",
            "Students may choose neurotransmitter release, which occurs at synapses rather than along the axon during depolarization.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Predicting effects of ion channel blockers on action potentials",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "The resting membrane potential of a typical neuron is maintained primarily by",
            "the sodium-potassium pump and selective membrane permeability",
            ["continuous action potentials along dendrites", "myelin preventing all ion movement", "equal permeability to Na$^+$ and K$^+$"],
            "The Na$^+$/K$^+$ pump actively transports ions while the membrane is more permeable to K$^+$ at rest, maintaining a negative interior near $-70$ mV.",
            "Students sometimes attribute resting potential to myelin alone or to equal ion permeability.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Explaining maintenance of resting membrane potential",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Which event occurs immediately after the peak of an action potential during repolarization?",
            "Potassium ions move out of the axon",
            ["Sodium ions move into the axon", "Calcium ions enter the synaptic knob", "Neurotransmitter is released into the synaptic cleft"],
            "During repolarization, voltage-gated K$^+$ channels open and K$^+$ exits the axon, restoring the negative membrane potential.",
            "Sodium influx occurs during depolarization, not repolarization.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Identifying ion movements during action potential phases",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "A competitive inhibitor at a synapse binds to the active site of an enzyme that breaks down neurotransmitter. The most likely effect is",
            "prolonged presence of neurotransmitter in the synaptic cleft",
            ["faster breakdown of neurotransmitter", "blocked release of neurotransmitter from vesicles", "prevented binding of neurotransmitter to receptors"],
            "Blocking the enzyme that degrades neurotransmitter (such as acetylcholinesterase) leaves more neurotransmitter available in the cleft, prolonging the signal.",
            "Students may confuse competitive enzyme inhibition with receptor blocking.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Applying enzyme inhibition concepts to synaptic transmission",
            difficulty="Medium", estimated_time_seconds=100,
        ),
        mc(
            "The absolute refractory period of a neuron ensures that",
            "action potentials travel in one direction along the axon",
            ["the neuron can fire continuously without limit", "neurotransmitters are always excitatory", "the resting potential becomes more positive over time"],
            "During the absolute refractory period, voltage-gated Na$^+$ channels cannot reopen, preventing backward propagation and limiting firing frequency.",
            "Students may think the refractory period increases firing rate rather than limiting it.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Explaining functional significance of refractory periods",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "A patient with damaged myelin sheaths on peripheral sensory neurons would most likely experience",
            "slower nerve impulse conduction",
            ["inability to produce neurotransmitters", "loss of resting membrane potential", "elimination of all reflex arcs"],
            "Myelin increases conduction velocity via saltatory conduction. Demyelination slows impulse transmission along affected neurons.",
            "Myelin damage affects conduction speed, not the fundamental ability to maintain resting potential.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Relating myelin damage to physiological symptoms",
            difficulty="Easy", estimated_time_seconds=80,
        ),
        mc(
            "At a chemical synapse, the arrival of an action potential at the presynaptic terminal triggers",
            "calcium influx and vesicle fusion with the presynaptic membrane",
            ["sodium influx into the postsynaptic neuron only", "immediate electrical current flow through gap junctions", "breakdown of receptors on the postsynaptic membrane"],
            "Depolarization opens voltage-gated Ca$^{2+}$ channels; calcium entry causes synaptic vesicles to fuse and release neurotransmitter.",
            "Students may confuse electrical synapses (gap junctions) with chemical synapses requiring vesicle release.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Describing events at a chemical synapse",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "An excitatory postsynaptic potential (EPSP) moves the membrane potential",
            "closer to threshold",
            ["below the resting potential further", "to exactly the resting potential always", "above threshold in every case"],
            "EPSPs are graded depolarizations that bring the membrane closer to the $-55$ mV threshold needed to trigger an action potential.",
            "Students may assume every EPSP always produces a full action potential regardless of summation.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Interpreting postsynaptic potentials",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Temporal summation occurs when",
            "multiple EPSPs from the same synapse arrive in rapid succession",
            ["EPSPs from different synapses arrive at the same time", "inhibitory signals cancel all excitatory signals", "myelin is removed from the axon"],
            "Temporal summation integrates signals from one synapse over a short time window; spatial summation integrates signals from multiple synapses simultaneously.",
            "Spatial summation from different synapses is often confused with temporal summation.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Distinguishing temporal and spatial summation",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        nr(
            "A neuron has a resting membrane potential of $-72$ mV and reaches a peak depolarization of $+35$ mV during an action potential. "
            "Express the resting potential as a two-digit positive value (ignore the sign) and the peak as a two-digit positive value. "
            "Record all four digits of your answer.",
            "7235",
            "Resting potential $-72$ mV gives digits $72$. Peak depolarization $+35$ mV gives digits $35$. Combined answer: $7235$.",
            "Students may include negative signs or reverse the order of the two values.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Extracting numerical values from membrane potential data",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        nr(
            "During a knee-jerk reflex, place the following events in the correct chronological order: "
            "(1) motor neuron fires, (2) muscle contracts, (3) stretch receptor detects change, (4) sensory impulse reaches spinal cord. "
            "Record all four digits of your answer.",
            "3412",
            "The stretch receptor fires first (3), the sensory signal reaches the spinal cord (4), the motor neuron responds (1), and the effector muscle contracts (2).",
            "Students often place muscle contraction before motor neuron activation.",
            topic=TOPIC, outcome_code="A1.3k",
            skill_tested="Sequencing events in a monosynaptic reflex arc",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "The correct pathway through a reflex arc is",
            "receptor $\\rightarrow$ sensory neuron $\\rightarrow$ interneuron $\\rightarrow$ motor neuron $\\rightarrow$ effector",
            ["effector $\\rightarrow$ motor neuron $\\rightarrow$ sensory neuron $\\rightarrow$ receptor", "sensory neuron $\\rightarrow$ receptor $\\rightarrow$ interneuron $\\rightarrow$ effector", "receptor $\\rightarrow$ motor neuron $\\rightarrow$ sensory neuron $\\rightarrow$ effector"],
            "A reflex arc begins with a receptor detecting a stimulus, continues through sensory and interneurons in the CNS, and ends with a motor neuron activating an effector.",
            "The direction of impulse flow in reflex arcs is commonly reversed.",
            topic=TOPIC, outcome_code="A1.3k",
            skill_tested="Identifying correct reflex arc pathway",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Withdrawal from a hot surface before pain is consciously perceived demonstrates that",
            "interneurons in the spinal cord can process reflexes without cerebrum involvement",
            ["pain receptors do not send signals to the brain", "the parasympathetic system controls voluntary movement", "motor neurons originate in the cerebrum for all reflexes"],
            "Spinal reflex arcs allow rapid motor responses processed locally; conscious pain perception follows separately via ascending pathways.",
            "Students may think the brain must process all responses before any movement occurs.",
            topic=TOPIC, outcome_code="A1.3k",
            skill_tested="Explaining spinal reflex processing vs conscious perception",
            difficulty="Medium", estimated_time_seconds=95,
        ),
        mc(
            "The autonomic nervous system differs from the somatic nervous system because autonomic pathways",
            "involuntarily regulate glands and smooth muscle",
            ["only control skeletal muscle for voluntary movement", "do not use motor neurons", "function only in the peripheral nervous system without CNS input"],
            "The autonomic division controls involuntary functions via two-neuron chains to cardiac muscle, smooth muscle, and glands.",
            "Voluntary skeletal muscle control is a somatic, not autonomic, function.",
            topic=TOPIC, outcome_code="A1.2k",
            skill_tested="Comparing somatic and autonomic nervous systems",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Stimulation of the sympathetic division during exercise would most likely cause",
            "increased heart rate and decreased blood flow to digestive organs",
            ["decreased heart rate and increased digestion", "pupil constriction and increased salivation", "decreased blood glucose and bronchial constriction"],
            "Sympathetic activation prepares the body for activity: heart rate rises, blood shifts from digestion to muscles, pupils dilate, and glycogenolysis increases blood glucose.",
            "Parasympathetic responses are often incorrectly attributed to sympathetic stimulation.",
            topic=TOPIC, outcome_code="A1.2k",
            skill_tested="Predicting sympathetic nervous system responses",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "The parasympathetic nervous system is sometimes called the 'rest and digest' system because it",
            "promotes digestion and conserves energy",
            ["prepares the body for fight-or-flight responses", "increases heart rate during stress", "dilates bronchioles for maximum oxygen intake"],
            "Parasympathetic activity dominates during rest, stimulating digestion, reducing heart rate, and promoting energy storage.",
            "Fight-or-flight responses belong to the sympathetic division.",
            topic=TOPIC, outcome_code="A1.2k",
            skill_tested="Identifying parasympathetic physiological effects",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "The hypothalamus coordinates both nervous and endocrine responses primarily by",
            "regulating the pituitary gland and autonomic centres",
            ["producing all hormones in the body directly", "filtering blood before it reaches the brain", "generating conscious voluntary movement"],
            "The hypothalamus links the nervous and endocrine systems by controlling pituitary hormone release and autonomic function.",
            "Students may think the hypothalamus produces every hormone or controls voluntary skeletal movement.",
            topic=TOPIC, outcome_code="A1.2k",
            skill_tested="Describing hypothalamus integrative role",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Damage to the cerebellum would most likely impair",
            "coordination and balance",
            ["regulation of breathing rate", "interpretation of visual images", "long-term memory formation"],
            "The cerebellum fine-tunes motor coordination, balance, and posture. Breathing is regulated by the medulla; vision by the occipital lobe.",
            "Brain structure functions are frequently confused on diploma-style questions.",
            topic=TOPIC, outcome_code="A1.2k",
            skill_tested="Matching brain regions to physiological functions",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "The medulla oblongata is essential for survival because it controls",
            "involuntary functions such as breathing and heart rate",
            ["conscious decision-making and reasoning", "storage of procedural memories only", "secretion of all digestive enzymes"],
            "The medulla contains vital centres for respiration, cardiovascular regulation, and other autonomic functions.",
            "Conscious reasoning is a cerebrum function, not medulla.",
            topic=TOPIC, outcome_code="A1.2k",
            skill_tested="Identifying medulla oblongata functions",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "The occipital lobe of the cerebrum is primarily responsible for processing",
            "visual information",
            ["auditory signals", "touch and temperature", "voluntary motor commands"],
            "Primary visual cortex in the occipital lobe interprets signals from the retina. Auditory processing occurs in the temporal lobe.",
            "Students confuse occipital (vision) with temporal (hearing) lobe functions.",
            topic=TOPIC, outcome_code="A1.4k",
            skill_tested="Associating cerebrum lobes with sensory processing",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Rods and cones are located in the",
            "retina",
            ["cornea", "lens", "optic nerve"],
            "Photoreceptors (rods for low light, cones for colour) are embedded in the retinal layer at the back of the eye.",
            "The lens focuses light; photoreceptors detect it in the retina.",
            topic=TOPIC, outcome_code="A1.4k",
            skill_tested="Locating photoreceptors in the eye",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "Cones are concentrated in the fovea and are most responsible for",
            "colour vision and high visual acuity in bright light",
            ["night vision in very dim light", "detecting only black and white without detail", "maintaining balance during head movement"],
            "Cones detect colour and fine detail in bright conditions; rods dominate peripheral and low-light vision.",
            "Rods, not cones, are primarily responsible for dim-light vision.",
            topic=TOPIC, outcome_code="A1.4k",
            skill_tested="Distinguishing rod and cone functions",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "The bending of light as it passes through the cornea and lens is called",
            "refraction",
            ["accommodation only", "transduction", "depolarization"],
            "Refraction changes the path of light to focus an image on the retina. Accommodation specifically refers to lens shape changes for near focus.",
            "Transduction refers to converting light to neural signals in photoreceptors.",
            topic=TOPIC, outcome_code="A1.4k",
            skill_tested="Defining optical processes in the eye",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "After light passes through the lens, it strikes photoreceptors in the correct order through these structures: lens $\\rightarrow$ vitreous humour $\\rightarrow$ retina. "
            "Which structure converts light energy into neural impulses?",
            "photoreceptors in the retina",
            ["the cornea", "the iris", "the optic nerve sheath"],
            "Photoreceptors in the retina transduce light into electrochemical signals that travel via bipolar and ganglion cells to the optic nerve.",
            "The optic nerve transmits signals but does not perform initial transduction.",
            topic=TOPIC, outcome_code="A1.4k",
            skill_tested="Identifying site of visual transduction",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "The semicircular canals of the inner ear detect",
            "rotational acceleration of the head",
            ["sound frequency and pitch", "linear air pressure changes only", "blood pressure in cerebral arteries"],
            "Semicircular canals contain fluid and hair cells that detect angular head movements for dynamic equilibrium.",
            "Sound detection occurs in the cochlea, not semicircular canals.",
            topic=TOPIC, outcome_code="A1.5k",
            skill_tested="Identifying vestibular system functions",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Sound vibrations are converted to neural impulses primarily in the",
            "organ of Corti within the cochlea",
            ["tympanic membrane only", "auditory canal only", "ossicles without cochlear involvement"],
            "Mechanical vibrations are transmitted through ossicles to the cochlea, where hair cells in the organ of Corti transduce them into nerve impulses.",
            "The eardrum vibrates but does not generate neural impulses directly.",
            topic=TOPIC, outcome_code="A1.5k",
            skill_tested="Locating auditory transduction site",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "The ossicles (malleus, incus, stapes) function to",
            "amplify and transmit vibrations from the eardrum to the cochlea",
            ["produce cerebrospinal fluid for the brain", "detect changes in head position", "filter blood entering the inner ear"],
            "Ossicles form a lever system that amplifies sound vibrations and delivers them to the oval window of the cochlea.",
            "Ossicles transmit sound; they do not detect balance.",
            topic=TOPIC, outcome_code="A1.5k",
            skill_tested="Describing middle ear ossicle function",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        nr(
            "Place the following auditory pathway structures in the order sound travels through them from the environment to the cochlea: "
            "(1) tympanic membrane, (2) auditory canal, (3) cochlea, (4) ossicles. Record all four digits.",
            "2413",
            "Sound enters the auditory canal (2), strikes the tympanic membrane (4), passes through ossicles (1), and reaches the cochlea (3).",
            "Students may place the cochlea before the ossicles.",
            topic=TOPIC, outcome_code="A1.5k",
            skill_tested="Sequencing structures in the auditory pathway",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Taste receptors on the tongue are examples of",
            "chemoreceptors",
            ["photoreceptors", "mechanoreceptors", "nociceptors"],
            "Taste receptors detect dissolved chemical stimuli, classifying them as chemoreceptors.",
            "Mechanoreceptors respond to pressure; photoreceptors to light.",
            topic=TOPIC, outcome_code="A1.6k",
            skill_tested="Classifying sensory receptor types",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "Adaptation of sensory receptors explains why a person stops noticing the feeling of a watch on the wrist after several minutes because",
            "receptor firing frequency decreases despite constant stimulus",
            ["the stimulus is no longer present", "motor neurons stop functioning", "the brain permanently deletes the sensory pathway"],
            "Sensory adaptation reduces perceived intensity when a stimulus remains constant, even though the stimulus persists.",
            "Students may think the stimulus itself disappears rather than neural response adapting.",
            topic=TOPIC, outcome_code="A1.6k",
            skill_tested="Explaining sensory adaptation",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "The minimum stimulus intensity required to trigger a nerve impulse is called the",
            "threshold",
            ["refractory period", "resting potential", "synaptic delay"],
            "Threshold is the level of depolarization (about $-55$ mV) needed to initiate an action potential.",
            "Resting potential is the baseline state, not the trigger level.",
            topic=TOPIC, outcome_code="A1.6k",
            skill_tested="Defining threshold in sensory physiology",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "A patient with a lesion affecting the optic chiasm may lose vision in the",
            "temporal (lateral) visual fields of both eyes",
            ["entire left eye only", "entire right eye only", "central foveal vision only"],
            "At the optic chiasm, nasal retinal fibres cross. Damage here classically produces bitemporal hemianopia.",
            "Complete monocular blindness suggests damage posterior to the chiasm on one side.",
            topic=TOPIC, outcome_code="A1.4k",
            skill_tested="Predicting visual field defects from pathway damage",
            difficulty="Hard", estimated_time_seconds=120,
        ),
        mc(
            "Glial cells in the nervous system are important because they",
            "support, insulate, and protect neurons",
            ["transmit action potentials to muscles directly", "secrete all hormones of the endocrine system", "replace neurons after every action potential"],
            "Glial cells (oligodendrocytes, Schwann cells, astrocytes, microglia) maintain the environment for neurons, including myelination and support.",
            "Neurons, not glia, conduct action potentials.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Describing roles of glial cells",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Multiple sclerosis involves immune attack on myelin in the CNS. Affected neurons would show",
            "decreased conduction velocity and possible signal loss",
            ["increased neurotransmitter production in all synapses", "permanent inability to maintain ATP levels", "conversion of sensory neurons to motor neurons"],
            "Demyelination disrupts saltatory conduction, slowing or blocking impulses along CNS pathways.",
            "MS affects myelin, not the fundamental identity of neuron types.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Applying myelin biology to disease context",
            difficulty="Medium", estimated_time_seconds=95,
        ),
        mc(
            "Which neurotransmitter is most directly associated with neuromuscular junction transmission to skeletal muscle?",
            "acetylcholine",
            ["dopamine", "serotonin", "gABA"],
            "Motor neurons release acetylcholine at the neuromuscular junction, binding nicotinic receptors on muscle fibres.",
            "Dopamine and serotonin are primarily CNS neurotransmitters, not the main NMJ transmitter.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Identifying neurotransmitters at neuromuscular junctions",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "A muscarinic antagonist blocking acetylcholine receptors on the sinoatrial node would most likely",
            "increase heart rate by reducing parasympathetic slowing",
            ["decrease heart rate by enhancing parasympathetic tone", "block all pain perception permanently", "increase digestive enzyme secretion via sympathetic nerves"],
            "Parasympathetic ACh slows the SA node; blocking muscarinic receptors reduces this braking effect, allowing heart rate to rise.",
            "Students confuse receptor blockade effects with agonist stimulation.",
            topic=TOPIC, outcome_code="A1.2k",
            skill_tested="Predicting autonomic drug effects on heart rate",
            difficulty="Hard", estimated_time_seconds=120,
        ),
    ]

    # --- A2: Endocrine system and homeostasis ---
    q += [
        mc(
            "Hormones differ from neurotransmitters in that hormones typically",
            "travel through the bloodstream to reach target cells",
            ["only function across synaptic clefts", "are always lipid-insoluble and cannot enter cells", "are released only by neurons in the spinal cord"],
            "Endocrine hormones are secreted into blood and act on distant targets, whereas neurotransmitters act locally across synapses.",
            "Some hormones are lipid-soluble and can enter cells; the key distinction is transport distance and mechanism.",
            topic=TOPIC, outcome_code="A2.1k",
            skill_tested="Comparing endocrine and nervous signalling",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "The anterior pituitary is classified as a true endocrine gland because it",
            "secretes hormones directly into the bloodstream",
            ["only stores hormones made by the hypothalamus without secretion", "connects directly to neurons in the cerebrum", "produces only digestive enzymes"],
            "The anterior pituitary synthesizes and releases tropic hormones (TSH, ACTH, FSH, LH, GH, prolactin) into circulation.",
            "Hormone storage without secretion describes the posterior pituitary's role for ADH and oxytocin.",
            topic=TOPIC, outcome_code="A2.1k",
            skill_tested="Identifying anterior pituitary endocrine function",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Negative feedback in hormone regulation means that",
            "rising hormone levels suppress further hormone release",
            ["hormone levels always increase without limit", "target organs stop responding after one signal", "the nervous system is not involved in any hormonal control"],
            "Negative feedback loops (e.g., thyroid hormone inhibiting TSH) maintain homeostasis by counteracting changes.",
            "Positive feedback (e.g., LH surge) is confused with the more common negative feedback.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Explaining negative feedback in endocrine regulation",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "In the regulation of blood glucose, insulin and glucagon demonstrate",
            "antagonistic hormonal control",
            ["identical effects on all target tissues", "positive feedback without set point", "control only by the sympathetic nervous system alone"],
            "Insulin lowers blood glucose by promoting uptake and storage; glucagon raises it by stimulating glycogenolysis — opposing actions.",
            "Both hormones are endocrine, not purely sympathetic responses.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Describing antagonistic hormone pairs",
            difficulty="Easy", estimated_time_seconds=75,
        ),
        mc(
            "Type 1 diabetes results primarily from",
            "destruction of pancreatic beta cells and insufficient insulin secretion",
            ["target cell resistance to insulin only", "excessive glucagon production with normal insulin", "overproduction of insulin causing hypoglycemia"],
            "Type 1 is autoimmune beta-cell destruction leading to insulin deficiency. Type 2 involves insulin resistance.",
            "Insulin resistance characterizes Type 2, not Type 1 diabetes.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Distinguishing Type 1 and Type 2 diabetes mechanisms",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "The thyroid gland requires dietary iodine because iodine is used to synthesize",
            "thyroxine (T4) and triiodothyronine (T3)",
            ["insulin and glucagon", "adrenaline and noradrenaline", "estrogen and progesterone"],
            "Thyroid hormones contain iodine atoms. Iodine deficiency impairs T3/T4 production and can cause goiter.",
            "Adrenal catecholamines and pancreatic hormones do not require iodine.",
            topic=TOPIC, outcome_code="A2.3k",
            skill_tested="Relating iodine to thyroid hormone synthesis",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "A person with hypothyroidism would most likely experience",
            "decreased metabolic rate and fatigue",
            ["excessive sweating and rapid weight loss", "chronically elevated blood calcium", "hyperglycemia from excess insulin"],
            "Low thyroid hormone reduces metabolic rate, causing fatigue, cold intolerance, and weight gain.",
            "Hyperthyroid symptoms (weight loss, heat intolerance) are often reversed in hypo cases.",
            topic=TOPIC, outcome_code="A2.3k",
            skill_tested="Predicting symptoms of hypothyroidism",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Adrenaline (epinephrine) release during stress is an example of",
            "a rapid hormonal response coordinated with the sympathetic nervous system",
            ["parasympathetic rest-and-digest activity", "a long-term growth response mediated by GH only", "negative feedback that lowers blood glucose immediately"],
            "The adrenal medulla releases adrenaline during sympathetic activation, quickly increasing heart rate and blood glucose.",
            "Adrenaline raises, not lowers, blood glucose during stress.",
            topic=TOPIC, outcome_code="A2.4k",
            skill_tested="Connecting adrenal medulla to stress response",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Cortisol secretion by the adrenal cortex helps the body respond to prolonged stress by",
            "mobilizing energy reserves and suppressing non-essential immune responses",
            ["permanently increasing bone density", "stimulating immediate pupil constriction", "blocking all action potentials in sensory neurons"],
            "Cortisol increases gluconeogenesis and modulates immune function during chronic stress.",
            "Pupil constriction is not a primary cortisol effect.",
            topic=TOPIC, outcome_code="A2.4k",
            skill_tested="Describing cortisol physiological effects",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Steroid hormones such as cortisol exert their effects by",
            "binding intracellular receptors and altering gene transcription",
            ["binding only ion-channel receptors on the cell surface", "functioning exclusively as second messengers in the cytoplasm", "digesting target cell DNA directly"],
            "Lipid-soluble steroid hormones enter cells and bind receptors that regulate gene expression.",
            "Peptide hormones typically use membrane receptors and second messengers.",
            topic=TOPIC, outcome_code="A2.5k",
            skill_tested="Comparing steroid and peptide hormone mechanisms",
            difficulty="Medium", estimated_time_seconds=95,
        ),
        mc(
            "Peptide hormones such as insulin typically act through",
            "membrane receptors and second messenger pathways",
            ["direct diffusion through the membrane without receptors", "binding DNA in the nucleus without intermediates", "permanent alteration of the cell's chromosome number"],
            "Insulin binds cell-surface receptors, triggering phosphorylation cascades (second messengers) without entering the nucleus directly.",
            "Steroid hormone mechanisms are incorrectly applied to peptide hormones.",
            topic=TOPIC, outcome_code="A2.5k",
            skill_tested="Describing peptide hormone signal transduction",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "The hypothalamic-pituitary-adrenal (HPA) axis regulates cortisol through",
            "CRH from hypothalamus $\\rightarrow$ ACTH from pituitary $\\rightarrow$ cortisol from adrenal cortex",
            ["TSH from pituitary $\\rightarrow$ insulin from pancreas", "ADH from posterior pituitary $\\rightarrow$ aldosterone from liver", "FSH from adrenal $\\rightarrow$ estrogen from hypothalamus"],
            "The HPA axis uses CRH and ACTH as tropic signals culminating in cortisol release, with negative feedback at each level.",
            "TSH and insulin belong to different endocrine axes.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Tracing the HPA axis pathway",
            difficulty="Medium", estimated_time_seconds=100,
        ),
        mc(
            "Aldosterone acts on kidney tubules to",
            "increase sodium reabsorption and water retention",
            ["decrease blood volume during dehydration", "excrete all potassium regardless of body needs", "block ADH release from the hypothalamus"],
            "Aldosterone promotes Na$^+$ reabsorption, indirectly conserving water and maintaining blood pressure.",
            "Aldosterone conserves sodium and water; it does not promote dehydration.",
            topic=TOPIC, outcome_code="A2.4k",
            skill_tested="Explaining aldosterone role in fluid balance",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Antidiuretic hormone (ADH) is released when blood osmolarity increases. Its primary effect is to",
            "increase water reabsorption in the collecting ducts of the kidney",
            ["stimulate glucose release from the liver only", "decrease sweat production in the skin exclusively", "increase filtration rate in the glomerulus without reabsorption"],
            "ADH inserts aquaporins in collecting duct cells, increasing water reabsorption and concentrating urine.",
            "ADH targets water reabsorption, not primarily hepatic glucose release.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Describing ADH role in osmoregulation",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "Calcium homeostasis involves parathyroid hormone (PTH), which",
            "increases blood calcium by stimulating bone resorption and renal reabsorption",
            ["lowers blood calcium by depositing it in bone exclusively", "functions identically to calcitonin from the thyroid", "blocks vitamin D production permanently"],
            "PTH raises blood Ca$^{2+}$ by releasing calcium from bone and increasing renal reabsorption. Calcitonin lowers blood calcium.",
            "PTH and calcitonin have opposing effects on blood calcium.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Explaining PTH role in calcium homeostasis",
            difficulty="Medium", estimated_time_seconds=95,
        ),
        mc(
            "A negative feedback loop maintaining body temperature on a cold day involves",
            "shivering increasing heat production until temperature rises to set point",
            ["continuous shivering regardless of core temperature", "sweating to cool the body while core temperature drops", "permanent shutdown of the hypothalamus"],
            "Thermoregulation uses negative feedback: cold triggers shivering; when core temperature returns to set point, shivering decreases.",
            "Sweating cools the body during overheating, not during cold exposure.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Applying negative feedback to thermoregulation",
            difficulty="Easy", estimated_time_seconds=80,
        ),
        nr(
            "A patient's fasting blood glucose is $4.2$ mmol/L. After a glucose challenge, it rises to $9.8$ mmol/L. "
            "Express the fasting value as a one-digit integer (round to nearest whole number) and the peak value as a one-digit integer. "
            "Record both digits.",
            "410",
            "Fasting $4.2$ rounds to $4$. Peak $9.8$ rounds to $10$ — but NR format uses digits: fasting $4$, peak $10$ requires recording as $4$ and $10$ = four digits $410$? "
            "Actually: 4 and 10 → record as 4, 1, 0 — that's 3 digits. Let me use simpler values.",
            "Students may forget to round or record digits in the wrong order.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Interpreting blood glucose monitoring data",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Diabetes insipidus involving insufficient ADH would cause",
            "excessive dilute urine production and dehydration risk",
            ["concentrated urine with low water loss", "complete inability to filter blood in kidneys", "permanent hyperglycemia identical to diabetes mellitus"],
            "Without ADH, collecting ducts reabsorb little water, producing large volumes of dilute urine.",
            "Diabetes insipidus affects water balance, not blood glucose like diabetes mellitus.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Distinguishing diabetes insipidus from mellitus",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "The lock-and-key model best describes how",
            "a hormone binds specifically to its receptor",
            ["all hormones enter all cells without specificity", "DNA replicates during mitosis", "action potentials jump between any adjacent cells"],
            "Hormone-receptor binding is highly specific, like a key fitting a particular lock.",
            "The lock-and-key model applies to molecular binding, not action potential propagation.",
            topic=TOPIC, outcome_code="A2.5k",
            skill_tested="Applying lock-and-key model to hormone-receptor binding",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "Up-regulation of hormone receptors on target cells would most likely occur when",
            "hormone concentration has been chronically low",
            ["hormone concentration is chronically very high", "the target tissue is permanently removed", "all feedback loops are eliminated"],
            "Cells increase receptor number (up-regulation) when hormone signals are weak; down-regulation occurs with chronic excess.",
            "Chronic high hormone levels typically cause down-regulation, not up-regulation.",
            topic=TOPIC, outcome_code="A2.5k",
            skill_tested="Explaining receptor up-regulation and down-regulation",
            difficulty="Hard", estimated_time_seconds=110,
        ),
        mc(
            "Oxytocin release during childbirth is an example of",
            "positive feedback amplifying uterine contractions",
            ["negative feedback maintaining constant hormone levels", "a reflex arc involving only somatic motor neurons", "hormonal control without any nervous system involvement"],
            "Oxytocin stimulates stronger contractions, which trigger more oxytocin — a positive feedback loop until birth completes.",
            "Most endocrine homeostasis uses negative, not positive, feedback.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Identifying positive feedback in endocrine regulation",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        mc(
            "Growth hormone (GH) from the anterior pituitary directly stimulates",
            "protein synthesis and cell growth in many tissues",
            ["melanin production in skin only", "sperm production in the testes without any intermediates", "reabsorption of glucose in the kidney exclusively"],
            "GH promotes growth via direct effects and by stimulating IGF-1 production in the liver.",
            "GH has broad metabolic effects, not limited to a single tissue.",
            topic=TOPIC, outcome_code="A2.1k",
            skill_tested="Describing growth hormone physiological effects",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        mc(
            "A goiter visible as neck swelling may develop when dietary iodine is insufficient because",
            "TSH stimulation increases thyroid gland size while hormone synthesis remains low",
            ["the pituitary stops producing all tropic hormones", "the adrenal cortex overproduces cortisol", "parathyroid hormone destroys thyroid follicles"],
            "Low T3/T4 triggers increased TSH, which hypertrophies the thyroid (goiter) without adequate hormone output.",
            "Goiter is thyroid enlargement from TSH overstimulation, not adrenal dysfunction.",
            topic=TOPIC, outcome_code="A2.3k",
            skill_tested="Explaining goiter formation from iodine deficiency",
            difficulty="Medium", estimated_time_seconds=95,
        ),
        mc(
            "The posterior pituitary stores and releases hormones that are actually synthesized in the",
            "hypothalamus",
            ["anterior pituitary", "thyroid gland", "adrenal medulla"],
            "ADH and oxytocin are produced by hypothalamic neurons and transported axonally to the posterior pituitary for release.",
            "Anterior pituitary synthesizes its own hormones; posterior pituitary only stores hypothalamic hormones.",
            topic=TOPIC, outcome_code="A2.1k",
            skill_tested="Tracing origin of posterior pituitary hormones",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        mc(
            "Homeostasis in the human body is best defined as",
            "maintenance of stable internal conditions despite external changes",
            ["elimination of all hormonal feedback loops", "keeping all body variables identical at all times without fluctuation", "preventing any response to environmental stimuli"],
            "Homeostasis involves dynamic regulation around set points, not rigid constancy with zero fluctuation.",
            "Homeostasis requires feedback responses, not elimination of all change.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Defining homeostasis",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        wr(
            "Describe how the nervous and endocrine systems work together to regulate blood glucose levels after a person eats a large carbohydrate meal. "
            "Include at least one hormone, one gland, and one nervous system component in your answer.",
            "After eating, blood glucose rises. Beta cells in the pancreas detect the increase and secrete insulin. Insulin promotes glucose uptake into cells and storage as glycogen in liver and muscle, lowering blood glucose. The parasympathetic nervous system supports digestive activity during the meal. If glucose drops too low later, alpha cells release glucagon, stimulating glycogen breakdown and gluconeogenesis. The hypothalamus monitors energy status and coordinates autonomic responses. Negative feedback on insulin and glucagon maintains glucose near the set point.",
            "Marking guide: (1) Identify blood glucose rise after eating — 1 mark. (2) Name insulin, pancreatic beta cells, and a target effect (uptake/storage) — 2 marks. (3) Include glucagon or counter-regulation — 1 mark. (4) Link nervous system component (parasympathetic or hypothalamic monitoring) — 1 mark. (5) Reference negative feedback/homeostasis — 1 mark.",
            "Students describe only insulin without mentioning feedback, or omit nervous system involvement entirely.",
            topic=TOPIC, outcome_code="A2.2k",
            skill_tested="Integrating nervous and endocrine glucose regulation",
            difficulty="Medium", estimated_time_seconds=240,
        ),
        wr(
            "Explain the events of synaptic transmission at a cholinergic synapse, from the arrival of an action potential at the presynaptic terminal to the response in the postsynaptic cell. "
            "Your answer should include at least four distinct steps.",
            "An action potential arrives at the presynaptic terminal, depolarizing the membrane. Voltage-gated calcium channels open and Ca$^{2+}$ enters the terminal. Calcium triggers synaptic vesicles containing acetylcholine to fuse with the presynaptic membrane, releasing ACh into the synaptic cleft by exocytosis. ACh diffuses across the cleft and binds to receptors on the postsynaptic membrane. Binding opens ion channels, producing an EPSP or IPSP. Acetylcholinesterase in the cleft breaks down ACh to prevent continuous stimulation. Choline is recycled into the presynaptic neuron.",
            "Marking guide: (1) Ca$^{2+}$ influx and vesicle fusion/exocytosis — 2 marks. (2) ACh diffusion and receptor binding — 1 mark. (3) Postsynaptic potential change — 1 mark. (4) Enzymatic breakdown/recycling — 1 mark. Clear sequence earns communication mark.",
            "Students skip calcium's role or fail to mention termination of the signal by enzymatic breakdown.",
            topic=TOPIC, outcome_code="A1.1k",
            skill_tested="Describing complete synaptic transmission sequence",
            difficulty="Hard", estimated_time_seconds=300,
        ),
        wr(
            "Compare the sympathetic and parasympathetic divisions of the autonomic nervous system in terms of general function, one physiological effect on the heart, and one physiological effect on digestion.",
            "Both divisions are part of the autonomic nervous system controlling involuntary functions. Sympathetic: fight-or-flight — increases heart rate, dilates bronchioles, diverts blood from digestion to muscles, inhibits digestive secretions. Parasympathetic: rest-and-digest — decreases heart rate, constricts bronchioles slightly, stimulates digestive gland secretion and peristalsis. The two divisions provide antagonistic control maintaining homeostasis.",
            "Marking guide: (1) General functional contrast (fight-or-flight vs rest-and-digest) — 2 marks. (2) One correct cardiac effect for each division — 2 marks. (3) One correct digestive effect for each division — 2 marks. Integration or homeostasis comment — 1 mark.",
            "Students list effects but do not pair them correctly with the proper division.",
            topic=TOPIC, outcome_code="A1.2k",
            skill_tested="Comparing sympathetic and parasympathetic effects",
            difficulty="Medium", estimated_time_seconds=240,
        ),
    ]

    # Fix the NR question with bad answer - replace with cleaner version
    for i, item in enumerate(q):
        if item.get("question_text", "").startswith("A patient's fasting blood glucose"):
            q[i] = nr(
                "A patient has a resting heart rate of $68$ beats/min before exercise and $142$ beats/min immediately after sprinting. "
                "Record the resting rate as a two-digit value followed by the exercise rate as a three-digit value (all five digits).",
                "68142",
                "Resting rate $68$ is recorded as $68$. Exercise rate $142$ is recorded as $142$. Combined: $68142$.",
                "Students may record digits without padding or reverse the order.",
                topic=TOPIC, outcome_code="A2.2k",
                skill_tested="Recording physiological measurement data",
                difficulty="Easy", estimated_time_seconds=75,
            )
            break

    # Add more NR and MC to reach target count
    q += _unit_a_supplement()
    return q


def _unit_a_supplement():
    """Additional Unit A questions to complete topic coverage."""
    s = []
    # Pupillary reflex sequence
    s.append(nr(
        "During the pupillary light reflex, order these events: (1) pupil diameter changes, (2) motor neuron depolarizes, "
        "(3) light receptors stimulated, (4) sensory neuron depolarizes. Record all four digits.",
        "3421",
        "Light stimulates receptors (3), sensory neuron fires (4), motor neuron fires (2), pupil changes (1).",
        "Event 1 is the effector response and must come last.",
        topic=TOPIC, outcome_code="A1.3k",
        skill_tested="Sequencing pupillary reflex events",
        difficulty="Easy", estimated_time_seconds=70,
    ))
    # Additional nervous system MC
    topics_mc = [
        ("The all-or-none principle states that once threshold is reached, an action potential of constant magnitude is produced regardless of stimulus strength beyond threshold.", "true principle", ["each stronger stimulus produces a larger action potential", "subthreshold stimuli produce partial action potentials", "threshold varies randomly for each impulse"], "All-or-none means action potentials are full-sized once triggered; stronger stimuli only increase frequency, not amplitude.", "Students think larger stimuli increase action potential amplitude.", "A1.1k", "Applying the all-or-none principle", "Easy", 65),
        ("Grey matter in the CNS consists primarily of", "neuron cell bodies, dendrites, and unmyelinated axons", ["myelinated axon tracts only", "cerebrospinal fluid reservoirs", "collagen connective tissue without neurons"], "Grey matter contains cell bodies and dendrites; white matter is predominantly myelinated axons.", "White matter composition is attributed to grey matter.", "A1.2k", "Distinguishing grey and white matter", "Easy", 60),
        ("The blood-brain barrier protects the CNS by", "restricting passage of many blood-borne substances into brain tissue", ["preventing all nutrients from reaching neurons", "eliminating the need for glial cells", "blocking action potentials between hemispheres"], "Tight junctions in capillary endothelial cells limit entry of toxins and pathogens while allowing essential nutrients.", "The barrier is selective, not a total block of all substances.", "A1.2k", "Explaining blood-brain barrier function", "Medium", 85),
        ("A nociceptor is specialized to detect", "painful or potentially damaging stimuli", ["sound waves in the cochlea", "balance changes in semicircular canals", "aroma molecules in the nasal epithelium only"], "Nociceptors are pain receptors that respond to intense mechanical, thermal, or chemical stimuli.", "Chemoreceptors in the nose detect smell, not nociceptors.", "A1.6k", "Identifying nociceptor function", "Easy", 55),
        ("The blind spot in the eye occurs where", "the optic nerve exits the retina and no photoreceptors are present", ["the lens attaches to the ciliary body", "only rods are concentrated", "the cornea meets the sclera"], "At the optic disc, ganglion cell axons exit, leaving an area without photoreceptors — the blind spot.", "The blind spot is retinal anatomy, not a lens attachment point.", "A1.4k", "Explaining blind spot anatomy", "Easy", 65),
        ("Presbyopia in older adults results primarily from", "reduced lens elasticity affecting near focus", ["loss of all rod cells in the retina", "damage to the optic chiasm", "excessive production of aqueous humour"], "Aging reduces lens flexibility, impairing accommodation for close objects.", "Presbyopia is a lens accommodation problem, not retinal degeneration.", "A1.4k", "Relating presbyopia to lens changes", "Medium", 80),
        ("Olfactory receptors in the nasal epithelium are", "chemoreceptors that detect odorant molecules", ["mechanoreceptors detecting air pressure only", "photoreceptors adapted from cone cells", "thermoreceptors measuring brain temperature"], "Smell depends on chemoreceptors binding volatile chemical molecules.", "Olfaction is chemical detection, not mechanical vibration sensing.", "A1.6k", "Classifying olfactory receptors", "Easy", 55),
        ("The thalamus functions primarily as a", "relay station for sensory information to the cerebrum", ["centre that directly controls digestive enzyme secretion", "structure producing cerebrospinal fluid exclusively", "region generating all spinal reflex arcs without CNS input"], "Most sensory pathways (except olfaction) synapse in the thalamus before reaching the cortex.", "CSF production is mainly by choroid plexus, not thalamus.", "A1.2k", "Identifying thalamus relay function", "Medium", 80),
        ("A lesion destroying Wernicke's area would most likely impair", "language comprehension", ["voluntary motor control of legs only", "hormone storage in posterior pituitary", "reflexive withdrawal from pain"], "Wernicke's area in the temporal lobe is critical for understanding spoken and written language.", "Motor speech production involves Broca's area, not Wernicke's.", "A1.2k", "Associating brain areas with language function", "Hard", 110),
        ("Broca's area damage would most likely cause difficulty with", "producing fluent speech", ["detecting bitter tastes", "regulating blood calcium", "transducing sound in the cochlea"], "Broca's area controls speech production and articulation; comprehension may remain intact.", "Language production and comprehension involve different cortical areas.", "A1.2k", "Associating Broca's area with speech production", "Hard", 110),
        ("Cerebrospinal fluid (CSF) primarily functions to", "cushion and nourish CNS tissues", ["generate action potentials in motor neurons", "produce all neurotransmitters for synapses", "replace blood in cerebral capillaries completely"], "CSF provides mechanical protection and helps remove metabolic wastes from the CNS.", "Neurotransmitters are synthesized in neurons, not by CSF.", "A1.2k", "Describing cerebrospinal fluid functions", "Medium", 80),
        ("The meningeal layers protecting the CNS include the dura mater, arachnoid mater, and", "pia mater", ["cornea", "retina", "pericardium"], "The three meninges are dura, arachnoid, and pia mater surrounding brain and spinal cord.", "Retina and cornea are eye structures, not meninges.", "A1.2k", "Identifying meningeal layers", "Easy", 60),
        ("During accommodation for near vision, the ciliary muscles contract causing the lens to", "become more rounded and increase refractive power", ["flatten and decrease refractive power", "detach from the suspensory ligaments permanently", "stop all light from entering the pupil"], "Near vision requires a thicker, more curved lens for stronger refraction.", "Distance vision involves a flatter lens, not near vision.", "A1.4k", "Explaining lens accommodation", "Medium", 85),
        ("Glaucoma involving increased intraocular pressure primarily damages", "the optic nerve", ["the tympanic membrane", "the olfactory bulb", "the spinal cord white matter"], "Elevated intraocular pressure compresses the optic nerve head, impairing vision.", "Glaucoma is an eye disorder, not an ear or spinal condition.", "A1.4k", "Relating glaucoma to optic nerve damage", "Medium", 85),
        ("Vestibular hair cells in the utricle and saccule detect", "linear acceleration and head position relative to gravity", ["chemical composition of blood", "sound frequency in the cochlea", "light intensity in the fovea"], "Utricle and saccule detect static equilibrium and linear movement.", "Rotational movement is detected by semicircular canals.", "A1.5k", "Distinguishing utricle/saccule from semicircular canal function", "Medium", 85),
        ("Sensorineural hearing loss differs from conductive hearing loss because sensorineural loss involves", "damage to cochlear hair cells or auditory nerve", ["blockage of the auditory canal by wax only", "a perforated tympanic membrane exclusively", "ossicles that are too large but intact"], "Sensorineural loss affects transduction or neural transmission; conductive loss affects sound conduction to the cochlea.", "Conductive loss can often be corrected mechanically; sensorineural typically cannot.", "A1.5k", "Distinguishing types of hearing loss", "Medium", 90),
        ("Melatonin secretion by the pineal gland is influenced by", "light levels detected via retinal pathways", ["blood glucose concentration exclusively", "stretch receptors in skeletal muscle", "aldosterone levels in the kidney"], "Light suppresses melatonin; darkness stimulates its release, regulating circadian rhythms.", "Melatonin is tied to light-dark cycles, not blood glucose.", "A2.1k", "Explaining pineal gland regulation", "Medium", 85),
        ("Estrogen and testosterone are examples of", "steroid hormones derived from cholesterol", ["peptide hormones stored in the posterior pituitary", "enzymes that digest proteins in the stomach", "neurotransmitters released at all somatic synapses"], "Sex hormones are lipid-soluble steroids that bind intracellular receptors.", "Peptide hormones are not synthesized from cholesterol.", "A2.5k", "Classifying steroid sex hormones", "Easy", 65),
        ("The zona fasciculata of the adrenal cortex primarily secretes", "glucocorticoids such as cortisol", ["catecholamines such as adrenaline", "thyroxine", "insulin"],
         "Zona fasciculata produces cortisol; zona reticularis makes androgens; zona glomerulosa makes aldosterone. Adrenaline comes from the medulla.", "Adrenal medulla catecholamines are confused with cortex zones.", "A2.4k", "Identifying adrenal cortex zones and products", "Hard", 115),
    ]
    for qtext, ans, dist, expl, mis, oc, skill, diff, time in topics_mc:
        s.append(mc(qtext, ans, dist, expl, mis, topic=TOPIC, outcome_code=oc,
                    skill_tested=skill, difficulty=diff, estimated_time_seconds=time))

    # More NR
    s.append(nr(
        "Match receptor type to stimulus: (1) photoreceptor, (2) mechanoreceptor in cochlea, (3) chemoreceptor for taste, (4) nociceptor. "
        "Which receptor detects light? Record the single digit.",
        "1",
        "Photoreceptors (1) in the retina detect light energy.",
        "Cochlear hair cells are mechanoreceptors, not photoreceptors.",
        topic=TOPIC, outcome_code="A1.6k",
        skill_tested="Matching receptors to stimuli",
        difficulty="Easy", estimated_time_seconds=55,
    ))
    s.append(nr(
        "A neuron fires at $25$ Hz at rest stimulation and $85$ Hz under strong stimulation. "
        "What is the increase in firing frequency in Hz? Record the two-digit answer.",
        "60",
        "Increase = $85 - 25 = 60$ Hz.",
        "Students record the final frequency instead of the difference.",
        topic=TOPIC, outcome_code="A1.1k",
        skill_tested="Calculating change in neuronal firing frequency",
        difficulty="Easy", estimated_time_seconds=60,
    ))
    s.append(wr(
        "Explain how negative feedback maintains thyroid hormone levels in the body. "
        "Include the roles of the hypothalamus, pituitary, thyroid, and at least one hormone in your answer.",
        "The hypothalamus releases TRH, stimulating the anterior pituitary to secrete TSH. TSH stimulates the thyroid to produce T3 and T4. When blood levels of T3/T4 rise sufficiently, they inhibit TRH and TSH release (negative feedback), reducing further thyroid stimulation. If thyroid hormone drops, inhibition decreases and the axis increases production, returning levels toward the set point.",
        "Marking guide: (1) TRH and TSH named with correct source glands — 2 marks. (2) T3/T4 from thyroid — 1 mark. (3) Negative feedback inhibition described — 2 marks. (4) Dynamic return to set point — 1 mark.",
        "Students describe the axis but omit the inhibitory feedback step.",
        topic=TOPIC, outcome_code="A2.2k",
        skill_tested="Tracing thyroid negative feedback loop",
        difficulty="Medium", estimated_time_seconds=240,
    ))
    s.append(wr(
        "A researcher measures pupil diameter in dim light ($6$ mm) and bright light ($2$ mm). "
        "Explain the reflex pathway responsible for the change and identify which division of the autonomic nervous system mediates the response in bright light.",
        "In bright light, retinal photoreceptors send signals via the optic nerve to brainstem centres that activate parasympathetic neurons. Parasympathetic fibres release acetylcholine at the iris sphincter muscle, causing constriction (pupil diameter decreases from $6$ mm to $2$ mm). This pupillary light reflex protects the retina from excess light. Afferent: optic nerve; efferent: oculomotor parasympathetic pathway.",
        "Marking guide: (1) Sensory input from retina/optic nerve — 1 mark. (2) Brainstem integration — 1 mark. (3) Parasympathetic efferent to iris — 2 marks. (4) Pupil constriction as effector response — 1 mark.",
        "Students attribute pupil constriction to sympathetic rather than parasympathetic activation.",
        topic=TOPIC, outcome_code="A1.3k",
        skill_tested="Explaining pupillary light reflex pathway",
        difficulty="Hard", estimated_time_seconds=280,
    ))
    return s
