"""Additional original Science 10 questions for production pool expansion."""

from .helpers import mc, nr

TOPIC_A = "Energy and Matter in Chemical Change"
TOPIC_B = "Energy Flow in Technological Systems"
TOPIC_C = "Cycling of Matter in Living Systems"
TOPIC_D = "Energy Flow in Global Systems"


def _batch_mc(topic, items):
    return [
        mc(q, a, d, e, m, topic=topic, outcome_code=oc, skill_tested=s,
           difficulty=diff, estimated_time_seconds=t)
        for q, a, d, e, m, oc, s, diff, t in items
    ]


def expansion() -> list[dict]:
    """Return ~120 unique original Science 10 questions across four topics."""
    items = []

    # --- Unit A: Energy and Matter in Chemical Change (~35) ---
    items += _batch_mc(TOPIC_A, [
        (
            "A neutral atom of magnesium-24 has 12 protons. How many neutrons does it contain?",
            "12",
            ["24", "12 electrons only with zero neutrons", "36"],
            "Mass number 24 minus 12 protons gives 12 neutrons.",
            "Students use mass number as neutron count without subtracting protons.",
            "A1.1k", "Calculating neutron number from mass and atomic numbers", "Easy", 60,
        ),
        (
            "Which particle has negligible mass compared with protons and neutrons?",
            "electron",
            ["proton", "neutron", "nucleus as a whole"],
            "Electrons have approximately 1/1836 the mass of a proton.",
            "Students think electrons contribute significantly to atomic mass.",
            "A1.1k", "Comparing relative masses of subatomic particles", "Easy", 55,
        ),
        (
            "Alkali metals in Group 1 typically form ions with a charge of",
            "+1",
            ["−1", "+2", "0"],
            "Alkali metals lose one valence electron to achieve a stable octet.",
            "Students confuse Group 1 with Group 2 charge or halogen −1 charge.",
            "A1.3k", "Predicting ion charge for alkali metals", "Easy", 55,
        ),
        (
            "Halogens in Group 17 typically gain one electron to form ions with charge",
            "−1",
            ["+1", "+2", "−2"],
            "Halogens need one electron to complete an octet in their valence shell.",
            "Students assign +1 charge by confusing gain with loss of electrons.",
            "A1.3k", "Predicting halogen ion charge from valence electrons", "Easy", 55,
        ),
        (
            "A chemical inventory list before a lab investigation is used primarily to",
            "record quantities and identities of reactants and products for safety and analysis",
            ["replace the need for balanced chemical equations entirely", "determine the colour of flame tests without reading labels", "calculate Earth's albedo from classroom chemicals"],
            "Inventories track substances used, supporting safe disposal and stoichiometric planning.",
            "Students think inventories eliminate equation writing or unrelated global calculations.",
            "A1.1sts", "Explaining purpose of chemical inventories in school labs", "Easy", 60,
        ),
        (
            "In a fair test of reaction rate, the dependent variable could be",
            "the time required for a measurable colour change to appear",
            ["the fixed concentration of acid held constant by design", "the type of safety goggles worn by all students", "the periodic table group number of sodium"],
            "Dependent variables are outcomes measured after changing conditions.",
            "Students label controlled variables or safety equipment as dependent variables.",
            "A1.2s", "Identifying dependent variables in reaction-rate investigations", "Medium", 80,
        ),
        (
            "A student measures temperature change when dissolving salts in water. "
            "Appropriate WHMIS review before starting ensures",
            "known hazards are identified and spill cleanup procedures are ready",
            ["equations balance themselves without student effort", "all solutions are guaranteed neutral pH", "calorimeter insulation becomes unnecessary"],
            "WHMIS supports hazard-aware planning; it does not replace experimental technique.",
            "Students assume WHMIS eliminates measurement or calorimetry requirements.",
            "A1.3s", "Integrating WHMIS review into calorimetry lab planning", "Easy", 65,
        ),
        (
            "Metallic bonding is best described as",
            "positive metal ions surrounded by a delocalized 'sea' of valence electrons",
            ["shared electron pairs between two non-metal atoms only", "complete transfer of all electrons to a noble gas", "static positive charges with no moving electrons"],
            "Delocalized electrons explain conductivity and malleability of metals.",
            "Students describe covalent or ionic models when asked about metals.",
            "A2.1k", "Describing metallic bonding with delocalized electrons", "Medium", 75,
        ),
        (
            "Which substance is classified as a molecular compound?",
            "PCl$_3$",
            ["KBr", "MgCl$_2$", "Li$_2$O"],
            "PCl$_3$ forms discrete molecules by electron sharing between non-metals.",
            "Students pick ionic metal–non-metal compounds for molecular examples.",
            "A2.1k", "Classifying molecular versus ionic compounds", "Easy", 55,
        ),
        (
            "The correct name for K$_2$SO$_4$ is",
            "potassium sulfate",
            ["potassium sulfide", "dipotassium sulfur tetroxide", "potassium(I) sulfate"],
            "K$^+$ and SO$_4^{2-}$ combine in a 2:1 ratio; no Roman numerals are needed for potassium.",
            "Students confuse sulfate with sulfide or add unnecessary prefixes.",
            "A2.2k", "Naming ionic compounds with polyatomic anions", "Easy", 60,
        ),
        (
            "The formula for iron(II) sulfide is",
            "FeS",
            ["Fe$_2$S", "FeS$_2$", "Fe$_2$S$_3$"],
            "Iron(II) is Fe$^{2+}$ and sulfide is S$^{2-}$; charges balance 1:1.",
            "Students double subscripts unnecessarily or confuse sulfide with sulfate.",
            "A2.2k", "Writing formulas from Roman numeral cation names", "Medium", 70,
        ),
        (
            "The prefix 'di-' in carbon dioxide (CO$_2$) indicates",
            "two oxygen atoms bonded to the central carbon atom",
            ["two carbon atoms in every molecule", "a double ionic charge on oxygen only", "a diatomic metal lattice"],
            "Molecular prefixes count atoms of each non-metal in covalent compounds.",
            "Students think 'di-' refers to carbon atoms rather than oxygen.",
            "A2.3k", "Interpreting Greek prefixes in molecular compound names", "Easy", 55,
        ),
        (
            "The correct name for P$_4$O$_10$ is",
            "tetraphosphorus decoxide",
            ["phosphorus oxide", "phosphorus(IV) oxide", "tetraphosphorus oxide"],
            "Covalent compounds of two non-metals require Greek prefixes for both elements.",
            "Students omit the tetra- prefix or use ionic Roman numeral naming.",
            "A2.3k", "Naming molecular compounds with multiple atoms of each element", "Medium", 70,
        ),
        (
            "A double covalent bond between two atoms contains",
            "four shared electrons in two pairs",
            ["two shared electrons in one pair only", "six shared electrons in three pairs", "no shared electrons; only ionic attraction"],
            "Each bond line represents two shared electrons; a double bond has two lines.",
            "Students count bond lines as single electrons or confuse with triple bonds.",
            "A2.4k", "Describing electron sharing in double covalent bonds", "Easy", 60,
        ),
        (
            "Lewis structures for representative elements often show a maximum of",
            "eight valence electrons around each atom (octet rule)",
            ["two valence electrons for every element including carbon", "eighteen electrons around hydrogen always", "no electrons around halogens"],
            "The octet rule guides dot diagrams for C, N, O, F and many main-group elements.",
            "Students apply the octet rule to hydrogen, which needs only two electrons.",
            "A2.5k", "Applying the octet rule in Lewis structures", "Medium", 75,
        ),
        (
            "Polar covalent bonds form when",
            "electrons are shared unequally between atoms with different electronegativity",
            ["electrons transfer completely from metal to non-metal", "atoms share electrons equally in all cases", "noble gases donate valence electrons to metals"],
            "Unequal sharing creates partial charges across the bond.",
            "Students label all covalent bonds as non-polar or call them ionic.",
            "A2.6k", "Distinguishing polar covalent bonding", "Medium", 75,
        ),
        (
            "Intermolecular forces are generally weaker than intramolecular bonds, which explains why",
            "molecular substances often have lower melting points than ionic compounds",
            ["ionic compounds evaporate faster than all molecular gases", "covalent bonds break when ice melts at 0 °C", "metals cannot conduct electricity"],
            "Melting disrupts intermolecular attractions, not covalent bonds within molecules.",
            "Students think ice melting breaks O–H bonds inside each water molecule.",
            "A2.7k", "Relating intermolecular forces to melting point trends", "Medium", 80,
        ),
        (
            "A synthesis reaction is characterized by",
            "two or more reactants combining to form a single product",
            ["one reactant splitting into two or more products", "an element replacing another in a compound", "an exchange of ions between two compounds"],
            "A + B → AB represents synthesis (combination).",
            "Students confuse synthesis with decomposition or double replacement.",
            "A3.1k", "Identifying synthesis reaction patterns", "Easy", 55,
        ),
        (
            "An example of a decomposition reaction is",
            "2H$_2$O$_2$ → 2H$_2$O + O$_2$",
            ["2Mg + O$_2$ → 2MgO", "Zn + 2HCl → ZnCl$_2$ + H$_2$", "AgNO$_3$ + NaCl → AgCl + NaNO$_3$"],
            "Hydrogen peroxide breaks down into water and oxygen gas.",
            "Students select combination, single replacement, or double replacement examples.",
            "A3.1k", "Recognizing decomposition reaction examples", "Easy", 60,
        ),
        (
            "In the activity series, a metal higher in the list will",
            "displace a metal lower in the list from its aqueous compound",
            ["always dissolve in water without any reaction", "never react with acids under any conditions", "convert lower metals into noble gases"],
            "Single replacement requires a more reactive metal to replace a less reactive one.",
            "Students think any metal replaces any other metal regardless of reactivity.",
            "A3.2k", "Applying the activity series to single replacement", "Medium", 80,
        ),
        (
            "A double replacement reaction in aqueous solution often produces a solid when",
            "two soluble ions combine to form an insoluble precipitate",
            ["all products remain dissolved as ions only", "only synthesis products can form", "covalent molecules cannot exchange partners"],
            "Precipitation occurs when the product has low solubility in water.",
            "Students think double replacement never forms solids.",
            "A3.2k", "Explaining precipitate formation in double replacement", "Medium", 75,
        ),
        (
            "Complete combustion of a hydrocarbon in excess oxygen produces",
            "carbon dioxide and water",
            ["carbon monoxide and solid carbon only", "hydrogen gas and metal oxides", "nitrogen gas and ammonia exclusively"],
            "Complete combustion oxidizes carbon to CO$_2$ and hydrogen to H$_2$O.",
            "Students report incomplete combustion products for complete combustion cases.",
            "A3.3k", "Predicting products of complete hydrocarbon combustion", "Easy", 60,
        ),
        (
            "Balancing the equation C$_3$H$_8$ + O$_2$ → CO$_2$ + H$_2$O requires coefficients that",
            "conserve atom counts of C, H, and O on both sides",
            ["change the identity of elements from carbon to oxygen", "ignore oxygen because it is a gas", "double only hydrogen atoms on the product side"],
            "Balancing adjusts coefficients; subscripts and element identities stay fixed.",
            "Students change subscripts or balance only one element.",
            "A3.4k", "Applying atom conservation when balancing combustion", "Medium", 85,
        ),
        (
            "A chemical change is best evidenced by",
            "formation of a new substance with different properties, such as a gas from two liquids",
            ["a change in state from solid ice to liquid water only", "crushing chalk into smaller pieces", "sorting a mixture by magnetism without reaction"],
            "New chemical bonds and substances indicate chemical change.",
            "Students classify physical changes or mechanical separation as chemical change.",
            "A3.5k", "Distinguishing chemical change evidence from physical change", "Easy", 55,
        ),
        (
            "According to the law of conservation of mass, the total mass of reactants in a closed system",
            "equals the total mass of products after the reaction",
            ["decreases whenever energy is released as heat", "increases when gases are produced", "is unrelated to atom rearrangement"],
            "Atoms are rearranged but not created or destroyed in chemical reactions.",
            "Students think mass is lost when heat or gas is released.",
            "A3.5k", "Applying conservation of mass to closed reactions", "Easy", 60,
        ),
        (
            "An acid–base neutralization reaction between an acid and a metal hydroxide typically produces",
            "water and a salt",
            ["only hydrogen gas and oxygen gas", "a pure metal and an oxide exclusively", "no water because hydroxides lack hydrogen"],
            "H$^+$ from acid and OH$^-$ from base form water; remaining ions form a salt.",
            "Students predict only gas products or omit salt formation.",
            "A3.6k", "Predicting products of acid–base neutralization", "Easy", 60,
        ),
        (
            "A solution with pH 3 is",
            "acidic",
            ["neutral", "basic", "devoid of all ions"],
            "pH below 7 indicates acidic conditions at standard temperature.",
            "Students think low pH numbers mean basic because the number is 'low'.",
            "A3.6k", "Classifying solutions by pH value", "Easy", 50,
        ),
        (
            "Phenolphthalein in a basic solution appears",
            "pink",
            ["colourless", "bright blue only in all bases", "metallic grey"],
            "Phenolphthalein is colourless in acid and pink in base (above ~pH 8.2).",
            "Students reverse acid and base indicator colours.",
            "A3.6k", "Interpreting phenolphthalein colour in basic media", "Easy", 55,
        ),
        (
            "In a calorimeter experiment, the heat absorbed by water is calculated using q = mcΔT. "
            "The specific heat capacity c represents",
            "energy required to raise 1 g of the substance by 1 °C",
            ["total mass of water in the calorimeter cup", "change in temperature only with no energy meaning", "the number of moles of solute dissolved"],
            "Specific heat is an intensive property used in q = mcΔT.",
            "Students confuse c with mass m or treat it as temperature change.",
            "A3.3k", "Defining specific heat capacity in calorimetry", "Medium", 75,
        ),
        (
            "An exothermic neutralization reaction between an acid and a base is characterized by",
            "a temperature increase in the solution as energy is released to the surroundings",
            ["a permanent decrease in total mass of atoms in the calorimeter", "absorption of heat causing the solution to cool steadily", "no energy transfer between reactants and surroundings"],
            "Exothermic reactions release thermal energy, often detected as warming in calorimetry.",
            "Students confuse exothermic warming with endothermic cooling or mass loss.",
            "A3.2k", "Identifying exothermic neutralization from temperature rise", "Easy", 65,
        ),
    ])

    items.extend([
        nr(
            "What is the molar mass of MgO in g/mol? Use Mg = 24 g/mol and O = 16 g/mol. "
            "Express your answer as a whole number.",
            "40",
            "Molar mass = 24 + 16 = 40 g/mol.",
            "Students add incorrect atomic values or report 24 g/mol only.",
            topic=TOPIC_A, outcome_code="A3.9k",
            skill_tested="Calculating molar mass of a binary ionic compound",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        nr(
            "How many moles are in 88 g of CO$_2$? Use molar mass CO$_2$ = 44 g/mol. "
            "Express your answer to one decimal place.",
            "2.0",
            "Moles = 88 / 44 = 2.0 mol.",
            "Students multiply mass by molar mass instead of dividing.",
            topic=TOPIC_A, outcome_code="A3.9k",
            skill_tested="Converting mass of CO₂ to moles",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        nr(
            "A calorimeter contains 200 g of water (c = 4.18 J/g·°C). Temperature rises 5.0 °C. "
            "How much heat energy q in joules did the water absorb? Express to zero decimal places.",
            "4180",
            "q = mcΔT = 200 × 4.18 × 5.0 = 4180 J.",
            "Students omit mass, use ΔT only, or forget to multiply by specific heat.",
            topic=TOPIC_A, outcome_code="A3.3k",
            skill_tested="Calculating heat absorbed using q equals mcΔT",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        nr(
            "According to 2Na + Cl$_2$ → 2NaCl, how many moles of NaCl form from 3.0 mol of Na? "
            "Express your answer to one decimal place.",
            "3.0",
            "Coefficient ratio Na : NaCl is 2 : 2 (1 : 1); 3.0 mol Na yields 3.0 mol NaCl.",
            "Students halve the answer because of the coefficient 2 on both sides.",
            topic=TOPIC_A, outcome_code="A3.7k",
            skill_tested="Applying mole ratio from balanced synthesis equation",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        nr(
            "A neutralization reaction releases 4500 J of heat to 150 g of water (c = 4.18 J/g·°C). "
            "What is the temperature increase in degrees Celsius? Express to one decimal place.",
            "7.2",
            "ΔT = q/(mc) = 4500/(150 × 4.18) ≈ 7.2 °C.",
            "Students multiply q × m × c instead of dividing q by mc.",
            topic=TOPIC_A, outcome_code="A1.4s",
            skill_tested="Calculating temperature change from heat and water mass",
            difficulty="Hard", estimated_time_seconds=100,
        ),
    ])

    # --- Unit B: Energy Flow in Technological Systems (~32) ---
    items += _batch_mc(TOPIC_B, [
        (
            "Electrical energy in a household circuit is most directly converted to thermal energy in a",
            "baseboard heater",
            ["solar photovoltaic panel generating electricity", "wind turbine blade rotating in air", "hydroelectric dam storing gravitational water energy only"],
            "Resistive heaters convert electrical energy to heat with high intentional thermal output.",
            "Students pick generation devices rather than end-use conversion appliances.",
            "B2.1k", "Identifying electrical-to-thermal conversion in heaters", "Easy", 55,
        ),
        (
            "Light energy from the Sun is converted to chemical energy during",
            "photosynthesis in producers",
            ["friction between brake pads on a bicycle", "elastic compression of a steel spring", "nuclear fission in a uranium fuel rod"],
            "Photosynthesis stores solar energy in glucose and other organic molecules.",
            "Students confuse biological energy storage with mechanical or nuclear processes.",
            "B2.1k", "Linking photosynthesis to light-to-chemical energy conversion", "Easy", 60,
        ),
        (
            "Nuclear energy in a fission reactor is ultimately converted to electrical energy through",
            "thermal energy heating steam that drives a turbine connected to a generator",
            ["direct emission of visible light into transmission lines only", "gravitational collapse of the reactor building", "chemical combustion of uranium metal in open air"],
            "Fission heats water/steam; mechanical rotation of turbines produces electricity.",
            "Students think nuclear plants send radiation directly into power lines.",
            "B2.1k", "Tracing nuclear-to-electrical energy conversion chain", "Medium", 80,
        ),
        (
            "A 1200 kg car travelling at 20 m/s has kinetic energy because",
            "both its mass and speed contribute to $E_k = \\frac{1}{2}mv^2$",
            ["only height above the road determines kinetic energy", "kinetic energy depends on colour of the vehicle", "mass cancels speed in the kinetic energy formula"],
            "Kinetic energy increases with mass and with the square of speed.",
            "Students ignore the v² term or think only mass matters.",
            "B2.2k", "Relating car kinetic energy to mass and speed", "Medium", 75,
        ),
        (
            "Raising a 50 kg crate vertically 4.0 m increases its gravitational potential energy. "
            "Using g = 9.8 m/s², the gain is closest to",
            "1960 J",
            ["200 J", "9800 J", "20 J"],
            "ΔE_p = mgh = 50 × 9.8 × 4.0 = 1960 J.",
            "Students forget to multiply by g or use horizontal distance instead of height.",
            "B2.2k", "Calculating gravitational potential energy change", "Medium", 85,
        ),
        (
            "A position-time graph with a straight line of positive slope indicates",
            "constant velocity in the positive direction",
            ["constant acceleration throughout the motion", "the object is stationary at a fixed position", "velocity is zero because the line is straight"],
            "Slope of a position-time graph equals velocity for uniform motion.",
            "Students confuse p-t slope with a-t slope or think straight means zero velocity.",
            "B2.3k", "Interpreting slope on a position-time graph", "Medium", 75,
        ),
        (
            "On a velocity-time graph, the area under the curve between two times represents",
            "displacement during that interval",
            ["instantaneous acceleration at one moment only", "total distance only when velocity is always negative", "the mass of the moving object"],
            "Area under v-t graph gives displacement; distance requires path consideration.",
            "Students think area gives acceleration or mass.",
            "B2.4k", "Interpreting area under a velocity-time graph", "Medium", 85,
        ),
        (
            "A truck moves 300 m north in 25 s. Its average velocity is",
            "12 m/s north",
            ["12 m/s south", "7500 m/s north", "0.08 m/s north"],
            "Average velocity = displacement/time = 300/25 = 12 m/s north.",
            "Students divide time by distance or omit direction on a vector answer.",
            "B2.5k", "Calculating average velocity from displacement and time", "Easy", 70,
        ),
        (
            "An athlete accelerates from rest to 8.0 m/s in 4.0 s. The average acceleration is",
            "2.0 m/s²",
            ["32 m/s²", "0.5 m/s²", "12 m/s²"],
            "a = Δv/Δt = 8.0/4.0 = 2.0 m/s².",
            "Students multiply velocity and time instead of dividing change by time.",
            "B2.6k", "Calculating average acceleration from velocity change", "Easy", 70,
        ),
        (
            "On a velocity-time graph, uniform acceleration appears as",
            "a straight line with non-zero slope",
            ["a horizontal line at zero velocity only", "a curved parabola opening downward always", "a vertical line at one instant only"],
            "Constant acceleration produces linear v-t relationships with constant slope equal to a.",
            "Students confuse v-t slope with d-t graph curvature or horizontal lines.",
            "B2.6k", "Interpreting uniform acceleration on velocity-time graphs", "Easy", 55,
        ),
        (
            "A ball thrown straight upward slows as it rises because",
            "gravitational force acts opposite to the upward velocity",
            ["gravity reverses to push the ball upward at the top", "air completely removes all kinetic energy instantly", "mass of the ball becomes zero at maximum height"],
            "Acceleration due to gravity opposes upward motion, reducing speed.",
            "Students think gravity disappears at the top or acts in the direction of motion.",
            "B2.7k", "Explaining deceleration of upward projectile motion", "Medium", 75,
        ),
        (
            "At the highest point of vertical toss (ignoring air resistance), the ball's velocity is",
            "zero momentarily while acceleration remains downward",
            ["zero and acceleration is also zero", "maximum upward velocity", "equal to launch speed upward"],
            "Velocity passes through zero at the peak; gravity still acts downward.",
            "Students think acceleration is zero whenever speed is zero.",
            "B2.7k", "Distinguishing zero velocity from zero acceleration at peak height", "Medium", 80,
        ),
        (
            "Positive work is done on an object when",
            "the applied force has a component in the direction of displacement",
            ["force is perpendicular to displacement throughout", "the object moves but no force acts on it", "displacement is zero while force is large"],
            "W = Fd cos θ; work is positive when force and displacement align.",
            "Students think any force near a moving object does positive work.",
            "B2.8k", "Identifying conditions for positive mechanical work", "Medium", 75,
        ),
        (
            "Carrying a heavy backpack horizontally at constant speed at shoulder height results in",
            "no work done by the upward support force on the pack (force perpendicular to motion)",
            ["large positive work because the pack moves a long distance", "negative work because gravity pulls downward", "work equal to mass times horizontal distance only"],
            "Vertical support force is perpendicular to horizontal displacement, so W = 0.",
            "Students equate effort or motion with work regardless of force direction.",
            "B2.8k", "Explaining zero work when force is perpendicular to displacement", "Hard", 90,
        ),
        (
            "A motor rated at 500 W running for 10 s transfers energy equal to",
            "5000 J",
            ["50 J", "50000 J", "5 J"],
            "Energy = power × time = 500 W × 10 s = 5000 J.",
            "Students divide power by time instead of multiplying.",
            "B2.9k", "Calculating energy transferred from power and time", "Easy", 55,
        ),
        (
            "A 60 W light bulb operating for 120 s transfers energy equal to",
            "7200 J",
            ["0.5 J", "7200 W", "180 J"],
            "E = Pt = 60 × 120 = 7200 J.",
            "Students report power units or divide instead of multiply.",
            "B2.10k", "Calculating energy from power and time", "Medium", 80,
        ),
        (
            "A machine with mechanical advantage greater than 1",
            "increases force but requires greater input distance for the same work ideal case",
            ["creates more output energy than input energy without losses", "eliminates all friction in every real system", "reduces input force while reducing input distance proportionally in ideal cases"],
            "Ideal MA trades force for distance; work input equals work output neglecting friction.",
            "Students think MA allows free energy gain or ignore distance trade-off.",
            "B2.11k", "Explaining mechanical advantage force–distance trade-off", "Medium", 80,
        ),
        (
            "A single fixed pulley changes",
            "the direction of the applied force without changing ideal mechanical advantage",
            ["both force magnitude and direction while doubling energy output", "only the mass of the load attached", "gravitational field strength at the ceiling"],
            "A fixed pulley redirects force; ideal MA ≈ 1.",
            "Students think one fixed pulley halves the required force.",
            "B2.12k", "Describing function of a fixed pulley", "Easy", 60,
        ),
        (
            "A block and tackle with ideal mechanical advantage 4 allows a worker to lift a load using",
            "one-quarter the force over four times the rope pull distance",
            ["one-quarter the energy input with no distance change", "four times the force with less rope pulled", "no change in force or distance compared with direct lift"],
            "MA = 4 reduces required force by factor 4 while increasing rope pulled.",
            "Students think MA reduces both force and distance simultaneously.",
            "B2.12k", "Applying block-and-tackle mechanical advantage", "Medium", 85,
        ),
        (
            "In a closed roller coaster car on a frictionless track, as the car descends a hill",
            "gravitational potential energy decreases while kinetic energy increases",
            ["total mechanical energy increases because height adds energy from nothing", "kinetic energy stays zero until the bottom", "potential energy and kinetic energy both increase together"],
            "Energy converts between forms; total mechanical energy remains constant ideally.",
            "Students think PE and KE both rise or that energy is created on descent.",
            "B3.1k", "Tracing PE–KE exchange on frictionless coaster descent", "Medium", 80,
        ),
        (
            "Real roller coasters never reach the original hill height on a subsequent hill because",
            "friction and air resistance convert some mechanical energy to thermal energy",
            ["conservation of energy does not apply to moving cars", "mass of the car increases during the ride", "gravity becomes weaker at lower elevation"],
            "Non-conservative forces remove mechanical energy as heat and sound.",
            "Students think energy violation occurs rather than transfer to thermal forms.",
            "B3.2k", "Explaining height loss from friction on roller coasters", "Medium", 80,
        ),
        (
            "A solar panel on a calculator converts",
            "light energy to electrical energy",
            ["electrical energy to nuclear energy in the case", "thermal energy to chemical fuel inside buttons", "sound energy to gravitational potential energy"],
            "Photovoltaic cells transform incident light into usable electric current.",
            "Students reverse the energy conversion direction.",
            "B3.2k", "Identifying light-to-electrical conversion in solar cells", "Easy", 55,
        ),
        (
            "A microphone in a public address system converts",
            "sound energy to electrical energy",
            ["electrical energy to nuclear binding energy", "gravitational energy to chemical energy in wires", "thermal energy to visible light in the cable"],
            "Microphones transduce pressure waves into electrical signals for amplification.",
            "Students confuse microphone input with speaker output conversion.",
            "B3.2k", "Describing sound-to-electrical transduction in microphones", "Medium", 75,
        ),
        (
            "Sankey diagrams are used to",
            "visualize energy inputs, useful outputs, and waste energy in a system",
            ["measure the mass of moving objects directly", "plot position versus time for projectiles only", "balance chemical equations by atom count"],
            "Sankey arrows show proportional energy flows including losses.",
            "Students think Sankey diagrams are motion graphs or chemical tools.",
            "B3.3k", "Explaining purpose of Sankey energy diagrams", "Easy", 60,
        ),
        (
            "Lubricating moving parts in an engine improves efficiency by",
            "reducing friction and therefore thermal energy losses",
            ["increasing friction to generate more heat intentionally", "adding mass to pistons so they store more energy", "eliminating the need for any fuel combustion"],
            "Less friction means more input energy becomes useful mechanical work.",
            "Students think lubrication increases friction or replaces fuel entirely.",
            "B3.4k", "Relating lubrication to reduced frictional energy loss", "Easy", 65,
        ),
        (
            "A natural gas furnace rated 80% efficient delivers 8.0 MJ of useful heat from an input of",
            "10 MJ",
            ["6.4 MJ", "12.5 MJ", "8.0 MJ input with 10 MJ output"],
            "Useful output = efficiency × input; 0.80 × 10 MJ = 8.0 MJ, so input was 10 MJ.",
            "Students multiply 8.0 by 0.80 or invert efficiency ratio.",
            "B3.5k", "Inferring energy input from efficiency and useful output", "Medium", 85,
        ),
    ])

    for ein, eout in [
        (400, 160),
        (750, 300),
        (1500, 900),
        (320, 96),
        (2000, 1100),
        (500, 425),
    ]:
        eff = round(100 * eout / ein, 1)
        items.append(nr(
            f"A device receives {ein} J of energy and produces {eout} J of useful output. "
            f"What is the efficiency as a percentage? Record to one decimal place.",
            f"{eff:.1f}",
            f"Efficiency = ({eout}/{ein}) × 100% = {eff}%.",
            "Students divide input by output instead of output by input.",
            topic=TOPIC_B, outcome_code="B1.3s",
            skill_tested="Calculating device efficiency from energy values",
            difficulty="Medium", estimated_time_seconds=80,
        ))

    # --- Unit C: Cycling of Matter in Living Systems (~32) ---
    items += _batch_mc(TOPIC_C, [
        (
            "The cell theory principle that all living things are composed of cells implies that",
            "multicellular organisms are built from many cooperating cells",
            ["only microscopic organisms qualify as alive", "cells can spontaneously form from non-living broth today", "viruses are complete living cells"],
            "Multicellular life organizes specialized cells into tissues and organs.",
            "Students think cell theory applies only to single-celled microbes.",
            "C1.1k", "Applying cell theory to multicellular organisms", "Easy", 55,
        ),
        (
            "Transmission electron microscopy (TEM) differs from scanning electron microscopy (SEM) because TEM",
            "passes electrons through an ultra-thin specimen to show internal structure",
            ["uses only visible light reflected from metal-coated surfaces", "cannot magnify structures smaller than 1 mm", "requires living unstained tissues only"],
            "TEM reveals internal ultrastructure; SEM images 3D surface topography.",
            "Students confuse TEM transmission with SEM surface imaging.",
            "C1.2k", "Distinguishing TEM from SEM techniques", "Medium", 85,
        ),
        (
            "Stem cell research may lead to therapies that",
            "replace damaged tissues by differentiating cells into needed cell types",
            ["convert all adult cells into viruses for vaccines only", "eliminate the need for membrane transport proteins", "stop photosynthesis in all plant leaves globally"],
            "Stem cells can specialize into various lineages for regenerative medicine.",
            "Students propose unrelated or impossible global biological changes.",
            "C1.3k", "Linking stem cell research to regenerative medicine", "Medium", 75,
        ),
        (
            "Prokaryotic cells differ from eukaryotic cells because prokaryotes",
            "lack a membrane-bound nucleus and membrane-bound organelles",
            ["always contain mitochondria and chloroplasts", "are only found in multicellular animals", "have DNA packaged with histone proteins in nucleosomes always"],
            "Prokaryotes have circular DNA in the nucleoid region without a nuclear envelope.",
            "Students think all cells have nuclei and membrane-bound organelles.",
            "C2.1k", "Contrasting prokaryotic and eukaryotic cell organization", "Easy", 60,
        ),
        (
            "The cell membrane's phospholipid bilayer forms because",
            "hydrophilic heads face water while hydrophobic tails avoid water",
            ["proteins repel all lipids from the cell surface", "cellulose fibres dissolve in the cytoplasm", "DNA strands anchor lipids to the nucleus only"],
            "Amphipathic phospholipids self-assemble into bilayers in aqueous environments.",
            "Students describe plant cell wall materials or unrelated DNA arrangements.",
            "C2.2k", "Explaining phospholipid bilayer formation", "Medium", 75,
        ),
        (
            "When a red blood cell swells in distilled water, the surrounding solution is",
            "hypotonic relative to the cell cytoplasm",
            ["hypertonic relative to the cell cytoplasm", "isotonic with no net water movement", "dehydrated with zero water potential always"],
            "Distilled water has lower solute concentration than cytoplasm, so water enters the cell.",
            "Students label hypotonic and hypertonic relationships from the cell's perspective incorrectly.",
            "C2.3k", "Classifying tonicity when cells swell in distilled water", "Easy", 55,
        ),
        (
            "A plant cell placed in a hypertonic solution will likely",
            "lose water and plasmolyze as the membrane pulls away from the cell wall",
            ["swell and burst because water enters rapidly", "begin photosynthesizing faster in the dark", "convert its cell wall into a nucleus"],
            "Water leaves the cell toward higher external solute concentration.",
            "Students predict swelling in hypertonic rather than hypotonic conditions.",
            "C2.3k", "Predicting plasmolysis in hypertonic conditions", "Medium", 80,
        ),
        (
            "Mitochondria are described as the 'powerhouse' because they",
            "carry out aerobic cellular respiration producing ATP",
            ["capture light energy to build glucose from CO₂", "synthesize proteins from amino acids on ribosomes", "store genetic information for the whole organism"],
            "Mitochondria release energy from glucose through respiration.",
            "Students assign photosynthesis or protein synthesis roles to mitochondria.",
            "C2.4k", "Identifying mitochondrial role in ATP production", "Easy", 55,
        ),
        (
            "Chloroplasts contain chlorophyll used to",
            "absorb light energy for photosynthesis",
            ["digest worn-out organelles in animal cells", "pump sodium ions against a gradient using ATP", "replicate DNA during mitosis in all cells"],
            "Chlorophyll captures light for carbon fixation in producers.",
            "Students think chloroplasts function in animal digestion or mitosis.",
            "C2.4k", "Describing chlorophyll function in chloroplasts", "Easy", 55,
        ),
        (
            "The nucleus of a eukaryotic cell primarily",
            "stores DNA and coordinates activities such as growth and reproduction",
            ["breaks down fatty acids in all plant roots exclusively", "builds cell walls from chitin in bacteria", "filters blood like the human spleen"],
            "Nuclear DNA directs protein synthesis and cell division control.",
            "Students assign digestive or immune organ functions to the nucleus.",
            "C2.5k", "Describing nuclear control of cell activities", "Easy", 60,
        ),
        (
            "Ribosomes function in all living cells to",
            "synthesize proteins by assembling amino acids",
            ["replicate DNA during interphase only in plants", "photosynthesize glucose using sunlight", "transport water in xylem vessels"],
            "Ribosomes translate mRNA into polypeptide chains.",
            "Students confuse ribosomes with chloroplasts or vascular tissue.",
            "C2.5k", "Identifying ribosome role in protein synthesis", "Easy", 55,
        ),
        (
            "Active transport across a membrane requires",
            "cellular energy (ATP) to move substances against a concentration gradient",
            ["only random thermal motion with no proteins involved", "water movement down its concentration gradient only", "gravity pulling ions through open windows"],
            "Pumps use ATP to move ions or molecules from low to high concentration.",
            "Students label passive diffusion or osmosis as active transport.",
            "C2.6k", "Distinguishing active transport from passive diffusion", "Medium", 75,
        ),
        (
            "Enzymes speed up metabolic reactions by",
            "lowering the activation energy required for the reaction to proceed",
            ["increasing the overall energy released so it violates conservation", "being consumed completely in every catalytic cycle", "raising activation energy to make reactions slower"],
            "Catalysts provide alternative pathways with lower activation barriers.",
            "Students think enzymes are used up or increase activation energy.",
            "C2.7k", "Explaining enzyme action on activation energy", "Medium", 80,
        ),
        (
            "Each enzyme is specific largely because",
            "its active site shape complements a particular substrate",
            ["it catalyzes every biochemical reaction in the cell equally", "it denatures at all temperatures above 0 °C instantly", "it stores sunlight as permanent chemical bonds only"],
            "Lock-and-key or induced-fit models explain substrate selectivity.",
            "Students think one enzyme handles all reactions or stores solar energy.",
            "C2.7k", "Relating active site shape to enzyme specificity", "Medium", 75,
        ),
        (
            "In photosynthesis, the light-dependent reactions produce",
            "ATP and NADPH used in the Calvin cycle",
            ["glucose directly with no intermediate carriers", "only carbon dioxide as the main energy-rich product", "oxygen consumed to build chlorophyll exclusively"],
            "Light reactions split water, release O₂, and generate ATP/NADPH.",
            "Students think glucose forms immediately in thylakoids without Calvin cycle.",
            "C2.8k", "Identifying products of light-dependent photosynthesis reactions", "Medium", 80,
        ),
        (
            "The overall photosynthesis equation shows that",
            "carbon dioxide and water combine using light energy to produce glucose and oxygen",
            ["glucose decomposes into CO₂ and water in bright light", "oxygen is consumed while CO₂ is released in producers", "only minerals from soil are converted to proteins without gases"],
            "6CO₂ + 6H₂O + light → C₆H₁₂O₆ + 6O₂ summarizes net photosynthesis.",
            "Students reverse the equation as respiration or omit gas exchange.",
            "C2.8k", "Interpreting net photosynthesis equation", "Easy", 65,
        ),
        (
            "Cellular respiration in aerobic organisms releases stored energy by",
            "breaking down glucose with oxygen to produce ATP, CO₂, and water",
            ["building glucose from CO₂ without any oxygen present", "converting ATP permanently into light in the cytoplasm only", "storing oxygen in cell walls for future photosynthesis"],
            "Aerobic respiration oxidizes glucose: C₆H₁₂O₆ + 6O₂ → 6CO₂ + 6H₂O + ATP.",
            "Students describe photosynthesis or claim ATP becomes light directly.",
            "C2.9k", "Summarizing aerobic cellular respiration products", "Easy", 65,
        ),
        (
            "Decomposers are essential in nutrient cycling because they",
            "break down dead organic matter returning minerals to soil and atmosphere",
            ["produce all atmospheric oxygen without any plants", "remove all carbon from Earth permanently", "prevent any energy flow between trophic levels"],
            "Decomposers mineralize organic nutrients for reuse by producers.",
            "Students think decomposers eliminate carbon or create all atmospheric O₂.",
            "C3.1k", "Explaining decomposer role in matter cycling", "Easy", 60,
        ),
        (
            "Nitrogen fixation is performed mainly by",
            "certain bacteria that convert atmospheric N₂ into usable ammonia compounds",
            ["all animals during cellular respiration in mitochondria", "chloroplasts when absorbing green light only", "decomposers that release only CO₂ from wood"],
            "Nitrogen-fixing bacteria incorporate N₂ into forms plants can assimilate.",
            "Students assign nitrogen fixation to animals or chloroplasts.",
            "C3.2k", "Identifying biological nitrogen fixation agents", "Medium", 75,
        ),
        (
            "Nitrification in the nitrogen cycle involves",
            "bacteria converting ammonium ions to nitrite and then nitrate",
            ["plants absorbing only gaseous N₂ through stomata directly", "lightning turning all nitrate into noble gases", "animals storing nitrate in bones permanently"],
            "Nitrifying bacteria oxidize ammonia species to nitrate usable by plants.",
            "Students think plants absorb N₂ gas directly as their main nitrogen source.",
            "C3.2k", "Describing nitrification steps in the nitrogen cycle", "Medium", 80,
        ),
        (
            "Denitrification returns nitrogen to the atmosphere when",
            "bacteria convert nitrates back to nitrogen gas (N₂)",
            ["plants release pure nitrogen from photosynthesis", "combustion of coal fixes all nitrogen into proteins", "animals exhale N₂ as their primary waste gas"],
            "Denitrifying bacteria complete the cycle by producing N₂ from soil nitrates.",
            "Students think photosynthesis or respiration directly emits N₂ from plants.",
            "C3.2k", "Explaining denitrification in the nitrogen cycle", "Medium", 80,
        ),
        (
            "In the carbon cycle, combustion of fossil fuels",
            "releases stored carbon as CO₂ into the atmosphere",
            ["removes CO₂ from air and stores it only in oceans permanently", "converts carbon into nitrogen gas in the troposphere", "prevents plants from using any carbon compounds"],
            "Burning hydrocarbons oxidizes carbon that was stored underground for millions of years.",
            "Students think fossil fuel use sequesters carbon or creates nitrogen.",
            "C3.3k", "Linking fossil fuel combustion to atmospheric CO₂ increase", "Easy", 60,
        ),
        (
            "Ocean uptake of CO₂ helps moderate atmospheric carbon levels but can also",
            "lower seawater pH through formation of carbonic acid (ocean acidification)",
            ["eliminate all greenhouse gases from the atmosphere instantly", "prevent any carbon from entering food webs", "increase seawater pH to strongly basic levels always"],
            "Dissolved CO₂ forms acidic species, threatening calcifying marine organisms.",
            "Students think ocean CO₂ uptake always raises pH or removes all CO₂.",
            "C3.3k", "Describing ocean acidification from CO₂ absorption", "Medium", 85,
        ),
        (
            "Transpiration in plants contributes to the water cycle by",
            "releasing water vapour from leaves into the atmosphere",
            ["condensing groundwater into rocks underground only", "filtering salt from oceans through roots exclusively", "preventing evaporation from lakes entirely"],
            "Stomatal water loss humidifies air and feeds cloud formation.",
            "Students think transpiration removes water from the atmosphere.",
            "C3.4k", "Explaining transpiration in the water cycle", "Easy", 60,
        ),
        (
            "Groundwater aquifers recharge when",
            "precipitation and surface water infiltrate permeable soil and rock",
            ["all rivers flow backward into clouds", "plants absorb water and destroy it chemically forever", "evaporation removes water from underground pores only"],
            "Infiltration percolates water downward to refill aquifers.",
            "Students think groundwater never replenishes or that water is destroyed in plants.",
            "C3.4k", "Describing aquifer recharge by infiltration", "Medium", 75,
        ),
        (
            "A trophic pyramid with a broad producer base and narrow top carnivore level illustrates",
            "energy loss between levels limits the number of top predators supported",
            ["energy is created anew at each higher trophic level", "decomposers receive more energy than producers always", "all energy remains available with no metabolic cost"],
            "Roughly 90% of energy is lost as heat between trophic transfers.",
            "Students think energy amplifies up the food chain.",
            "C3.5k", "Interpreting trophic pyramid energy limitation", "Medium", 80,
        ),
        (
            "Bioaccumulation of a persistent pesticide in a lake ecosystem means",
            "concentration increases in organisms at higher trophic levels over time",
            ["the pesticide dissolves instantly and harms only producers once", "top predators always have lower toxin levels than phytoplankton", "matter is destroyed so nutrients cannot cycle"],
            "Fat-soluble toxins magnify along food chains.",
            "Students think toxins dilute at higher levels or destroy matter.",
            "C3.6k", "Explaining bioaccumulation along food chains", "Medium", 85,
        ),
        (
            "Invasive species often disrupt ecosystems because they",
            "lack natural predators and may outcompete native species",
            ["always increase biodiversity in every habitat they enter", "immediately form balanced mutualisms with all native organisms", "speed up nitrogen fixation in ways that never harm natives"],
            "Without controls, invasives can dominate resources and reduce native populations.",
            "Students assume invasives always improve ecosystem diversity.",
            "C3.1sts", "Analyzing ecological impact of invasive species", "Medium", 80,
        ),
        (
            "A student measures dissolved oxygen downstream of a sewage outfall compared with upstream. "
            "Lower downstream oxygen suggests",
            "decomposers are using oxygen while breaking down added organic waste",
            ["photosynthesis stopped globally in the river", "oxygen molecules were converted to nitrogen gas only", "fish created extra oxygen by respiring faster"],
            "Bacterial decomposition of organic pollution consumes dissolved O₂.",
            "Students think respiring fish add net oxygen or that O becomes N.",
            "C1.4s", "Interpreting dissolved oxygen data near pollution sources", "Hard", 95,
        ),
    ])

    items.extend([
        nr(
            "A microscope magnifies an object 400× with a 10× eyepiece. What is the objective lens magnification? "
            "Express your answer as a whole number.",
            "40",
            "Total magnification = eyepiece × objective; 400/10 = 40× objective.",
            "Students add magnifications or multiply 400 by 10.",
            topic=TOPIC_C, outcome_code="C1.2s",
            skill_tested="Calculating objective magnification from total and eyepiece",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        nr(
            "During photosynthesis, a plant fixes 0.30 mol of CO₂ per hour. How many moles of CO₂ are fixed in 5.0 hours? "
            "Express your answer to one decimal place.",
            "1.5",
            "Moles = rate × time = 0.30 × 5.0 = 1.5 mol CO₂.",
            "Students divide by 5 or confuse moles with grams.",
            topic=TOPIC_C, outcome_code="C2.8k",
            skill_tested="Calculating total CO₂ fixed over elapsed time",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        nr(
            "A food chain transfers 10% of energy between trophic levels. If producers contain 8000 kJ/m², "
            "how much energy in kJ/m² is available to primary consumers? Express as a whole number.",
            "800",
            "Primary consumers receive 10% of 8000 = 800 kJ/m².",
            "Students use 90% transfer or multiply by 10 instead of 0.10.",
            topic=TOPIC_C, outcome_code="C3.5k",
            skill_tested="Calculating energy at next trophic level using ten percent rule",
            difficulty="Medium", estimated_time_seconds=80,
        ),
    ])

    # --- Unit D: Energy Flow in Global Systems (~21) ---
    items += _batch_mc(TOPIC_D, [
        (
            "Solar energy absorbed at the equator compared with polar regions is greater because",
            "sunlight strikes equatorial surfaces at a more direct angle year-round",
            ["the equator is always closer to the Sun by millions of kilometres daily", "polar ice eliminates all incoming radiation completely", "Earth's core heats the equator exclusively"],
            "Higher solar angle concentrates energy per unit area at low latitudes.",
            "Students cite distance or core heat rather than angle of incidence.",
            "D1.2k", "Comparing equatorial and polar solar energy absorption", "Medium", 75,
        ),
        (
            "Water vapour is an important greenhouse gas because it",
            "absorbs and re-emits infrared radiation, contributing to atmospheric warming",
            ["reflects all incoming ultraviolet back to space without absorption", "exists only in the stratosphere and never near the surface", "has no interaction with electromagnetic waves"],
            "Water vapour concentration strongly influences infrared retention.",
            "Students think water vapour only reflects UV or is stratospheric only.",
            "D1.4k", "Describing water vapour greenhouse contribution", "Easy", 60,
        ),
        (
            "The stratospheric ozone layer protects life primarily by",
            "absorbing harmful ultraviolet (UV) radiation from the Sun",
            ["reflecting all infrared radiation back to space only", "producing oxygen for photosynthesis in trees directly", "preventing all convective storms in the troposphere"],
            "Ozone absorbs UV-B and UV-C, reducing surface exposure.",
            "Students confuse ozone UV shielding with infrared greenhouse trapping.",
            "D1.5k", "Explaining stratospheric ozone UV protection role", "Easy", 55,
        ),
        (
            "The Montreal Protocol was an international agreement primarily aimed at",
            "phasing out production of ozone-depleting substances such as CFCs",
            ["eliminating all fossil fuel combustion within one year", "banning all agricultural fertilizers globally", "replacing all hydroelectric dams with coal plants"],
            "Montreal Protocol targeted CFCs and related chemicals to protect stratospheric ozone.",
            "Students confuse ozone treaty goals with general greenhouse gas reduction only.",
            "D4.3k", "Identifying Montreal Protocol purpose for ozone protection", "Medium", 80,
        ),
        (
            "Hadley cells in the atmosphere circulate air by",
            "rising warm air at the equator and sinking cooler air near about 30° latitude",
            ["pulling air exclusively from the North Pole to the equator only at night", "eliminating all horizontal wind near the surface globally", "converting water vapour into ozone at the tropopause only"],
            "Convective loops redistribute heat from equator toward subtropics.",
            "Students describe unrealistic one-way polar flows or ozone-only processes.",
            "D2.1k", "Describing Hadley cell convection pattern", "Medium", 80,
        ),
        (
            "The Coriolis effect deflects moving air and water because",
            "Earth's rotation changes the apparent path of motion relative to the surface",
            ["the Moon's gravity reverses wind direction at the equator daily", "friction with mountains creates permanent east winds only", "solar flares push air masses westward every summer"],
            "Coriolis deflection arises from rotation; magnitude depends on latitude.",
            "Students blame lunar gravity or solar flares for Coriolis deflection.",
            "D2.2k", "Explaining Coriolis deflection of air masses", "Medium", 85,
        ),
        (
            "In the Northern Hemisphere, surface winds around a low-pressure centre spiral",
            "counterclockwise inward toward the centre",
            ["clockwise outward away from the centre only", "straight north with no curvature ever", "downward into the mantle as lava flow"],
            "Low-pressure systems draw air inward with counterclockwise rotation (NH).",
            "Students reverse cyclone rotation or confuse with high-pressure anticyclones.",
            "D2.3k", "Identifying Northern Hemisphere low-pressure wind rotation", "Medium", 85,
        ),
        (
            "A maritime polar (mP) air mass is characterized by",
            "cool, moist conditions formed over northern oceans",
            ["hot, dry air formed over subtropical deserts", "warm, humid air originating over tropical oceans only", "stationary air with no moisture or temperature traits"],
            "mP air masses develop over cold ocean surfaces, bringing cool damp weather.",
            "Students confuse mP with tropical maritime (mT) or continental tropical air.",
            "D2.4k", "Classifying maritime polar air mass properties", "Medium", 80,
        ),
        (
            "A cold front on a weather map typically brings",
            "a narrow band of rising air, clouds, and often heavy precipitation with temperature drop",
            ["weeks of calm clear skies with no wind shift", "only gradual warming without any cloud development", "permanent high pressure that stops the water cycle"],
            "Dense cold air wedges under warm air, forcing rapid uplift and storms.",
            "Students think cold fronts always bring calm warming conditions.",
            "D2.5k", "Predicting weather associated with cold fronts", "Medium", 80,
        ),
        (
            "Warm fronts generally produce",
            "widespread cloud layers and prolonged precipitation ahead of the surface boundary",
            ["instant dry lightning with no clouds forming", "immediate hail in all seasons at all latitudes", "complete cessation of wind for several years"],
            "Gradual overrunning of cool air by warm air creates layered clouds and steady rain/snow.",
            "Students expect abrupt hail-only events or multi-year wind calm.",
            "D2.5k", "Describing cloud and precipitation patterns of warm fronts", "Medium", 80,
        ),
        (
            "Isobars drawn close together on a weather map indicate",
            "strong pressure gradient and typically stronger winds",
            ["calm conditions with very light winds always", "equal temperature everywhere on the map", "zero humidity across the region"],
            "Tight isobars mean large pressure change over short distance, driving faster flow.",
            "Students think close isobars mean calm weather or uniform temperature.",
            "D2.6k", "Interpreting closely spaced isobars as strong winds", "Medium", 75,
        ),
        (
            "Climate differs from weather because climate describes",
            "long-term average patterns of temperature, precipitation, and wind in a region",
            ["the exact temperature at one moment in one town only", "daily cloud shapes without any statistics", "solar fusion rates inside the Sun each second"],
            "Climate is statistical long-term; weather is short-term state.",
            "Students use single-day observations to define climate.",
            "D3.1k", "Distinguishing climate from weather", "Easy", 55,
        ),
        (
            "Proxy climate data from tree rings (dendroclimatology) can reveal",
            "past variations in temperature or moisture inferred from annual growth width",
            ["real-time lightning strikes in the next forecast hour", "exact future hurricane paths ten years ahead always", "the current barometric pressure at student's desk only"],
            "Wide/narrow rings correlate with favorable/unfavorable growing conditions in past years.",
            "Students think tree rings forecast specific future storms or desk pressure.",
            "D3.2k", "Explaining tree ring use as climate proxy data", "Medium", 80,
        ),
        (
            "Milankovitch cycles influence climate over thousands of years by changing",
            "Earth's orbital eccentricity, axial tilt, and precession affecting seasonal insolation",
            ["the mass of the Moon each month only", "tidal bore heights in rivers without any solar input change", "instantaneous volcanic CO₂ emissions every day"],
            "Orbital variations alter distribution and timing of solar heating.",
            "Students attribute Milankovitch cycles to lunar mass or daily volcanism.",
            "D3.3k", "Linking Milankovitch cycles to insolation changes", "Hard", 90,
        ),
        (
            "Positive feedback in climate systems occurs when",
            "a warming change triggers processes that cause additional warming",
            ["every change automatically cancels itself to zero effect always", "cooling leads immediately to further cooling through unrelated factors only", "feedbacks eliminate the greenhouse effect entirely"],
            "Example: melting ice reduces albedo, absorbing more sunlight and warming further.",
            "Students think feedbacks always stabilize climate instantly.",
            "D3.4k", "Defining positive climate feedback loops", "Medium", 80,
        ),
        (
            "Ocean conveyor belt circulation (thermohaline circulation) helps distribute heat by",
            "moving warm surface water poleward and cold deep water toward the equator",
            ["stopping all evaporation from tropical seas permanently", "converting Atlantic water into stratospheric ozone", "eliminating salinity differences in all oceans instantly"],
            "Density-driven deep currents connect surface gyres globally.",
            "Students think conveyor belts halt evaporation or homogenize salinity instantly.",
            "D4.1k", "Describing thermohaline heat redistribution", "Medium", 85,
        ),
        (
            "El Niño conditions in the equatorial Pacific often lead to",
            "weakened trade winds and warm surface water shifting eastward, altering global weather",
            ["permanent freezing of all tropical oceans year-round", "complete stop of the water cycle over continents", "removal of all greenhouse gases from the atmosphere"],
            "El Niño rearranges Pacific heat distribution, affecting precipitation patterns worldwide.",
            "Students think El Niño freezes tropics or ends the water cycle globally.",
            "D4.2k", "Summarizing El Niño atmospheric and oceanic shifts", "Medium", 85,
        ),
    ])

    items.extend([
        nr(
            "Fresh snow reflects 85% of incoming solar radiation. What percentage is absorbed? "
            "Express your answer as a whole number.",
            "15",
            "Absorbed fraction = 100% − reflected 85% = 15%.",
            "Students report 85% as absorbed or add 85 + 100.",
            topic=TOPIC_D, outcome_code="D1.3k",
            skill_tested="Calculating absorbed solar fraction from albedo",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        nr(
            "A weather station records average temperature 12 °C for 5 days. "
            "What is the sum of daily average temperatures in degree-days (°C·days)? Express as a whole number.",
            "60",
            "Sum = 12 °C × 5 days = 60 °C·days (total temperature-days).",
            "Students divide 12 by 5 or report 12 only.",
            topic=TOPIC_D, outcome_code="D1.4s",
            skill_tested="Summing average daily temperatures over multiple days",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        nr(
            "Atmospheric CO₂ rose from 380 ppm to 420 ppm over a decade. What is the increase in ppm? "
            "Express as a whole number.",
            "40",
            "Increase = 420 − 380 = 40 ppm.",
            "Students add the values or report the final 420 only.",
            topic=TOPIC_D, outcome_code="D3.4k",
            skill_tested="Calculating ppm increase from initial and final concentrations",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        nr(
            "A climate model projects sea level rise of 3.2 mm per year. How many millimetres of rise "
            "are expected in 25 years? Express to zero decimal places.",
            "80",
            "Rise = 3.2 mm/y × 25 y = 80 mm.",
            "Students divide 3.2 by 25 or round to 8 mm.",
            topic=TOPIC_D, outcome_code="D4.5k",
            skill_tested="Projecting linear sea level rise over decades",
            difficulty="Medium", estimated_time_seconds=75,
        ),
    ])

    return items
