"""Unit A: Energy and Matter in Chemical Change — original Science 10 questions."""

from .helpers import mc, nr

TOPIC = "Energy and Matter in Chemical Change"


def _batch_mc(items):
    return [
        mc(q, a, d, e, m, topic=TOPIC, outcome_code=oc, skill_tested=s,
           difficulty=diff, estimated_time_seconds=t)
        for q, a, d, e, m, oc, s, diff, t in items
    ]


def questions():
    q = []

    # --- A1: Structure of Matter ---
    q += _batch_mc([
        (
            "In the modern atomic model, the three subatomic particles found in an atom are",
            "protons, neutrons, and electrons",
            ["protons, ions, and molecules only", "neutrons, compounds, and photons", "electrons, mixtures, and isotopes only"],
            "Atoms contain protons and neutrons in the nucleus and electrons in surrounding energy levels.",
            "Students confuse subatomic particles with larger chemical species like molecules.",
            "A1.1k", "Identifying subatomic particles in atoms", "Easy", 55,
        ),
        (
            "Which subatomic particle carries a positive charge and is located in the nucleus?",
            "proton",
            ["electron", "neutron", "ion"],
            "Protons are positively charged and reside in the atomic nucleus.",
            "Students select electron because it is the most familiar subatomic particle.",
            "A1.1k", "Locating charged subatomic particles", "Easy", 50,
        ),
        (
            "The mass of an atom is concentrated primarily in its",
            "nucleus",
            ["electron cloud", "outermost energy level only", "valence bond region"],
            "Protons and neutrons, which contain nearly all atomic mass, are found in the nucleus.",
            "Students think electrons contribute most of the mass because they occupy large volumes.",
            "A1.1k", "Relating atomic mass to nuclear structure", "Easy", 55,
        ),
        (
            "An atom of carbon-12 contains 6 protons. How many electrons does a neutral atom of carbon-12 contain?",
            "6",
            ["12", "6 neutrons only with no electrons", "18"],
            "A neutral atom has equal numbers of protons and electrons.",
            "Students use mass number (12) instead of atomic number (6).",
            "A1.1k", "Applying proton-electron balance in neutral atoms", "Easy", 60,
        ),
        (
            "Isotopes of the same element differ in their number of",
            "neutrons",
            ["protons", "electrons in a neutral atom", "energy levels only"],
            "Isotopes share the same atomic number (protons) but differ in neutron count.",
            "Students think isotopes differ in proton number, which would make them different elements.",
            "A1.1k", "Distinguishing isotopes by neutron count", "Medium", 70,
        ),
        (
            "Dalton's atomic theory proposed that atoms are",
            "indivisible, identical particles within a given element",
            ["mostly empty space with a dense nucleus", "composed of a positively charged sphere with embedded electrons", "arranged in fixed energy levels around a nucleus"],
            "Dalton viewed atoms as solid, indivisible units; later models refined this view.",
            "Students attribute Rutherford or Thomson models to Dalton.",
            "A1.2k", "Recalling Dalton's atomic model postulates", "Easy", 65,
        ),
        (
            "Thomson's plum pudding model described the atom as",
            "a positively charged sphere with electrons embedded throughout",
            ["a tiny dense nucleus surrounded by mostly empty space", "a planetary system of electrons in fixed orbits", "a solid indivisible sphere with no substructure"],
            "Thomson proposed electrons embedded in a uniform positive charge.",
            "Students confuse Thomson's model with Rutherford's nuclear model.",
            "A1.2k", "Describing Thomson's plum pudding model", "Easy", 65,
        ),
        (
            "Rutherford's gold foil experiment provided evidence that an atom",
            "has a small, dense, positively charged nucleus",
            ["is a uniform sphere of positive charge", "contains no empty space", "has electrons in fixed circular orbits"],
            "Most alpha particles passed through, but some deflected sharply, indicating a dense nuclear core.",
            "Students think the experiment proved electrons orbit like planets.",
            "A1.2k", "Interpreting Rutherford gold foil evidence", "Medium", 80,
        ),
        (
            "Bohr's model improved on Rutherford's model by proposing that electrons",
            "occupy specific energy levels at fixed distances from the nucleus",
            ["are embedded in a positive sphere", "have no defined location in the atom", "exist only inside the nucleus"],
            "Bohr assigned electrons to discrete energy levels, explaining line spectra.",
            "Students think Bohr's model removed the nucleus entirely.",
            "A1.2k", "Explaining Bohr energy level concept", "Medium", 75,
        ),
        (
            "On the periodic table, elements in the same vertical column (group) share",
            "the same number of valence electrons",
            ["the same total number of protons and neutrons", "identical atomic masses", "the same number of energy levels only"],
            "Group members have similar valence electron configurations and chemical properties.",
            "Students confuse group number with period number or mass number.",
            "A1.3k", "Relating periodic groups to valence electrons", "Medium", 75,
        ),
        (
            "The atomic number of an element equals the number of",
            "protons in each atom of that element",
            ["neutrons only", "electrons in every ion", "molecules in one mole"],
            "Atomic number uniquely identifies an element by its proton count.",
            "Students use mass number or neutron count as the atomic number.",
            "A1.3k", "Defining atomic number", "Easy", 55,
        ),
        (
            "Elements in the same horizontal row (period) of the periodic table have",
            "the same number of occupied energy levels",
            ["identical chemical properties in all cases", "the same number of valence electrons", "identical atomic numbers"],
            "Period number corresponds to the highest occupied principal energy level.",
            "Students think periods share valence electron count like groups do.",
            "A1.3k", "Relating periods to energy level count", "Medium", 70,
        ),
        (
            "WHMIS pictograms on a chemical container primarily communicate",
            "hazard types such as flammability, toxicity, or corrosivity",
            ["the molar mass of the substance", "balanced chemical equations for reactions", "the exact number of moles in the container"],
            "WHMIS symbols alert users to physical and health hazards before handling chemicals.",
            "Students confuse WHMIS with chemical formula or stoichiometry information.",
            "A1.1sts", "Interpreting WHMIS hazard pictograms", "Easy", 60,
        ),
        (
            "Knowledge of atomic structure has contributed to technologies such as",
            "medical imaging and semiconductor electronics",
            ["perpetual motion machines that create energy from nothing", "eliminating all chemical reactions in industry", "converting lead into gold in household kitchens"],
            "Understanding electrons and energy levels enables devices like MRI scanners and computer chips.",
            "Students select implausible or alchemical applications.",
            "A1.1sts", "Linking atomic theory to modern technology", "Medium", 75,
        ),
        (
            "A student plans to test whether heating copper metal in air changes its mass. "
            "The independent variable in this investigation is",
            "whether the copper is heated in air or left unheated",
            ["the final colour of the copper sample", "the balance used to measure mass", "the chemical formula of copper oxide formed"],
            "The independent variable is the condition deliberately changed by the investigator.",
            "Students confuse independent variables with measured outcomes (dependent variables).",
            "A1.1s", "Identifying independent variables in investigations", "Medium", 80,
        ),
        (
            "Before mixing an acid and a base in a lab, a Science 10 student consults WHMIS labels to",
            "determine required personal protective equipment and safe handling steps",
            ["calculate the exact enthalpy change without calorimetry", "predict every product without reading the equation", "skip ventilation requirements entirely"],
            "Safe lab practice requires hazard assessment before handling reactive chemicals.",
            "Students think WHMIS replaces the need for teacher instruction or PPE.",
            "A1.1s", "Applying WHMIS in lab planning", "Easy", 65,
        ),
    ])

    # --- A2: Compounds ---
    q += _batch_mc([
        (
            "An ionic compound is typically formed when",
            "a metal transfers electrons to a non-metal",
            ["two non-metals share electrons equally", "noble gases react with each other", "metals share electron pairs with other metals"],
            "Ionic bonding involves electron transfer from metal to non-metal, producing ions.",
            "Students think all compounds form by electron sharing (covalent bonding).",
            "A2.1k", "Describing ionic bond formation", "Easy", 60,
        ),
        (
            "A molecular (covalent) compound is best represented by",
            "CO$_2$",
            ["NaCl", "MgO", "CaCl$_2$"],
            "CO$_2$ consists of molecules formed by shared electrons between non-metals.",
            "Students select ionic examples when asked for molecular compounds.",
            "A2.1k", "Distinguishing molecular from ionic examples", "Easy", 55,
        ),
        (
            "The correct IUPAC name for NaCl is",
            "sodium chloride",
            ["sodium monochloride", "sodium(I) chloride", "natrium chlorine"],
            "Ionic compounds are named with the metal cation followed by the non-metal anion with -ide ending.",
            "Students use prefixes reserved for molecular compounds on ionic names.",
            "A2.2k", "Naming binary ionic compounds", "Easy", 50,
        ),
        (
            "The formula for calcium oxide is",
            "CaO",
            ["CaO$_2$", "Ca$_2$O", "CaOH"],
            "Calcium forms Ca$^{2+}$ and oxide is O$^{2-}$; charges balance in a 1:1 ratio.",
            "Students double both subscripts unnecessarily (Ca$_2$O$_2$ simplified incorrectly).",
            "A2.2k", "Writing formulas for binary ionic compounds", "Easy", 60,
        ),
        (
            "The IUPAC name for FeCl$_3$ is",
            "iron(III) chloride",
            ["iron chloride", "iron(3) chloric", "ferrous trichloride"],
            "Transition metals require Roman numerals to indicate ion charge: Fe$^{3+}$ in FeCl$_3$.",
            "Students omit Roman numerals for variable-charge metals.",
            "A2.2k", "Naming ionic compounds with transition metals", "Medium", 75,
        ),
        (
            "Which formula correctly represents aluminum sulfate?",
            "Al$_2$(SO$_4$)$_3$",
            ["AlSO$_4$", "Al$_2$SO$_4$", "Al(SO$_4$)$_2$"],
            "Al$^{3+}$ and SO$_4^{2-}$ require two aluminum ions and three sulfate ions for charge balance.",
            "Students fail to cross-charge balance with polyatomic ions.",
            "A2.2k", "Writing formulas with polyatomic ions", "Hard", 90,
        ),
        (
            "The correct name for N$_2$O$_5$ is",
            "dinitrogen pentoxide",
            ["nitrogen pentoxide", "dinitrogen pentaoxide", "nitrogen(V) oxide"],
            "Molecular compounds use prefixes to indicate atom counts: di- for 2, penta- for 5.",
            "Students omit prefixes or use ionic-style Roman numerals.",
            "A2.3k", "Naming binary molecular compounds with prefixes", "Medium", 70,
        ),
        (
            "The formula for diphosphorus pentachloride is",
            "P$_2$Cl$_5$",
            ["PCl$_5$", "P$_2$Cl$_5$O", "PCl"],
            "Prefix di- means 2 phosphorus atoms; penta- means 5 chlorine atoms.",
            "Students drop one prefix or swap subscript values.",
            "A2.3k", "Writing molecular formulas from prefixed names", "Medium", 75,
        ),
        (
            "The IUPAC name for HCl(aq) is",
            "hydrochloric acid",
            ["hydrogen chloride acid", "chloric acid", "hypochlorous acid"],
            "Binary acids use hydro- + non-metal root + -ic acid when dissolved in water.",
            "Students confuse binary acids with oxoacids like chloric acid.",
            "A2.4k", "Naming binary acids", "Easy", 60,
        ),
        (
            "The formula for sulfuric acid is",
            "H$_2$SO$_4$",
            ["HSO$_4$", "H$_2$S", "H$_2$SO$_3$"],
            "Sulfuric acid is a common oxoacid with formula H$_2$SO$_4$.",
            "Students confuse sulfuric acid (H$_2$SO$_4$) with sulfurous acid (H$_2$SO$_3$).",
            "A2.4k", "Recalling common acid formulas", "Medium", 70,
        ),
        (
            "The name of the base NaOH is",
            "sodium hydroxide",
            ["sodium oxide", "sodium hydrogen", "natrium hydroxide"],
            "Metal hydroxide bases are named as metal + hydroxide.",
            "Students confuse hydroxides with oxides.",
            "A2.4k", "Naming metal hydroxide bases", "Easy", 55,
        ),
        (
            "From the name potassium nitrate, the correct formula is",
            "KNO$_3$",
            ["K$_2$NO$_3$", "KNO$_2$", "K$_3$N"],
            "Potassium is K$^+$ and nitrate is NO$_3^-$; one of each ion gives KNO$_3$.",
            "Students confuse nitrate (NO$_3^-$) with nitrite (NO$_2^-$).",
            "A2.5k", "Translating compound names to formulas", "Medium", 70,
        ),
        (
            "Which property is most characteristic of ionic compounds at room temperature?",
            "high melting point and brittleness in solid form",
            ["low boiling point and gases at room temperature", "poor electrical conductivity when dissolved in water", "soft waxy solids that do not conduct in any state"],
            "Strong ionic lattice forces give high melting points; ionic solids shatter when stressed.",
            "Students think ionic compounds are always gases or never conduct when dissolved.",
            "A2.6k", "Comparing ionic compound physical properties", "Medium", 75,
        ),
        (
            "Distilled water does not conduct electricity well, but a solution of NaCl in water does because",
            "dissolved ions are free to move and carry charge",
            ["covalent molecules split into atoms that carry current", "water molecules become metallic when salt is added", "electrons from covalent bonds flow through the liquid"],
            "Ionic solutions conduct via mobile cations and anions; pure water has very few ions.",
            "Students think undissolved molecular compounds conduct electricity.",
            "A2.6k", "Explaining electrical conductivity of ionic solutions", "Medium", 80,
        ),
        (
            "The polyatomic ion sulfate has the formula",
            "SO$_4^{2-}$",
            ["SO$_3^{2-}$", "S$^{2-}$", "SO$_4^-$"],
            "Sulfate is SO$_4^{2-}$; sulfite is SO$_3^{2-}$.",
            "Students confuse sulfate and sulfite formulas.",
            "A2.7k", "Identifying common polyatomic ion formulas", "Easy", 60,
        ),
        (
            "The carbonate ion has the formula",
            "CO$_3^{2-}$",
            ["CO$_2^{2-}$", "HCO$_3^{2-}$", "C$^{4-}$"],
            "Carbonate is CO$_3^{2-}$; bicarbonate (hydrogen carbonate) is HCO$_3^-$.",
            "Students mix up carbonate with bicarbonate or carbon dioxide.",
            "A2.7k", "Distinguishing carbonate from related ions", "Easy", 60,
        ),
        (
            "Ammonium nitrate is used in fertilizers because it supplies plants with",
            "nitrogen in a soluble ionic form",
            ["inert noble gases for root growth", "metallic copper for chlorophyll synthesis", "pure carbon dioxide dissolved as a gas only"],
            "Ammonium and nitrate ions provide bioavailable nitrogen for plant proteins and growth.",
            "Students think fertilizers work by adding unrelated elements.",
            "A2.1sts", "Explaining fertilizer chemistry societal application", "Medium", 75,
        ),
        (
            "Household bleach contains compounds that can release toxic chlorine gas if mixed with certain acids. "
            "This illustrates why",
            "chemical products must be stored and used according to label directions",
            ["all household chemicals are inert and interchangeable", "WHMIS labels are optional for home products", "mixing cleaners always increases their effectiveness safely"],
            "Incompatible chemicals can produce hazardous gases; label warnings prevent dangerous combinations.",
            "Students underestimate risks of mixing common household chemicals.",
            "A2.1sts", "Evaluating safe use of household chemicals", "Easy", 65,
        ),
        (
            "While recording observations during a conductivity test, a student notes that a sugar solution "
            "does not light a bulb but a salt solution does. This record best supports the conclusion that",
            "ionic solutes produce mobile charged particles in solution",
            ["all molecular compounds are strong electrolytes", "sugar molecules carry electric current", "distilled water contains no molecules"],
            "Conductivity differences indicate presence or absence of ions in solution.",
            "Students conclude all dissolved substances conduct equally.",
            "A1.2s", "Recording evidence from conductivity investigations", "Medium", 75,
        ),
    ])

    # --- A3: Chemical Reactions ---
    q += _batch_mc([
        (
            "Which observation is evidence that a chemical change has occurred?",
            "a new gas is produced that was not present in the reactants",
            ["iron filings are separated from sand with a magnet", "water evaporates from a puddle on hot pavement", "salt dissolves and disappears in water with stirring"],
            "Gas formation from reactants indicates new substances have been created.",
            "Students classify physical changes (dissolving, evaporation) as chemical changes.",
            "A3.1k", "Identifying evidence of chemical change", "Easy", 55,
        ),
        (
            "A chemical reaction that feels cold to the touch because it absorbs energy from the surroundings is",
            "endothermic",
            ["exothermic", "combustion only", "always a physical change"],
            "Endothermic reactions draw thermal energy in, lowering surrounding temperature.",
            "Students reverse endothermic and exothermic definitions.",
            "A3.2k", "Classifying endothermic reactions", "Easy", 55,
        ),
        (
            "Burning natural gas in a furnace is an example of an",
            "exothermic reaction",
            ["endothermic reaction", "physical change only", "reaction that absorbs heat from the room"],
            "Combustion releases energy as heat and light — exothermic.",
            "Students think all reactions requiring ignition are endothermic overall.",
            "A3.2k", "Classifying exothermic combustion", "Easy", 55,
        ),
        (
            "The reaction $2Mg + O_2 \\rightarrow 2MgO$ is classified as",
            "formation (synthesis)",
            ["decomposition", "single replacement", "double replacement"],
            "Two reactants combine to form a single product — synthesis (formation).",
            "Students mislabel combination reactions as decomposition.",
            "A3.3k", "Classifying synthesis reactions", "Easy", 60,
        ),
        (
            "$2H_2O_2 \\rightarrow 2H_2O + O_2$ is best classified as",
            "decomposition",
            ["formation (synthesis)", "single replacement", "double replacement"],
            "One reactant breaks into two or more products — decomposition.",
            "Students classify any oxygen-producing reaction as combustion.",
            "A3.3k", "Classifying decomposition reactions", "Easy", 60,
        ),
        (
            "$Zn + 2HCl \\rightarrow ZnCl_2 + H_2$ is an example of",
            "single replacement",
            ["double replacement", "formation (synthesis)", "hydrocarbon combustion"],
            "One element (Zn) replaces another (H) in a compound — single replacement.",
            "Students confuse single and double replacement patterns.",
            "A3.3k", "Classifying single replacement reactions", "Medium", 70,
        ),
        (
            "$AgNO_3 + NaCl \\rightarrow AgCl + NaNO_3$ is an example of",
            "double replacement",
            ["single replacement", "decomposition", "formation (synthesis)"],
            "Two compounds exchange ions to form two new compounds — double replacement.",
            "Students label any precipitation reaction as single replacement.",
            "A3.3k", "Classifying double replacement reactions", "Medium", 70,
        ),
        (
            "Complete combustion of propane ($C_3H_8$) in sufficient oxygen produces",
            "carbon dioxide and water",
            ["carbon monoxide and solid carbon only", "hydrogen gas and oxygen gas", "methane and ozone"],
            "Hydrocarbon combustion in excess O$_2$ yields CO$_2$ and H$_2$O.",
            "Students think incomplete products (CO, C) form under complete combustion conditions.",
            "A3.3k", "Identifying hydrocarbon combustion products", "Medium", 75,
        ),
        (
            "The word equation for iron reacting with oxygen to form iron(III) oxide is",
            "iron + oxygen $\\rightarrow$ iron(III) oxide",
            ["iron(III) oxide $\\rightarrow$ iron + oxygen", "iron + water $\\rightarrow$ iron(III) oxide + hydrogen", "iron + oxygen $\\rightarrow$ iron(II) chloride"],
            "Word equations show reactants on the left and products on the right.",
            "Students reverse reactant and product sides or introduce incorrect products.",
            "A3.4k", "Writing word equations for rust formation", "Easy", 65,
        ),
        (
            "Which balanced chemical equation correctly represents the synthesis of water?",
            "$2H_2 + O_2 \\rightarrow 2H_2O$",
            ["$H_2 + O_2 \\rightarrow H_2O$", "$H_2 + O \\rightarrow H_2O$", "$2H_2 + O_2 \\rightarrow H_2O$"],
            "Two moles of H$_2$ react with one mole of O$_2$ to produce two moles of H$_2$O; atoms must balance.",
            "Students write unbalanced equations with unequal atom counts.",
            "A3.5k", "Balancing a synthesis equation", "Medium", 80,
        ),
        (
            "When aluminum reacts with copper(II) chloride, the products are",
            "aluminum chloride and copper metal",
            ["aluminum oxide and hydrogen gas", "copper(II) oxide and aluminum metal", "no reaction because aluminum is less reactive"],
            "Aluminum replaces copper in the compound: $2Al + 3CuCl_2 \\rightarrow 2AlCl_3 + 3Cu$.",
            "Students predict no reaction or incorrect products for active metal replacements.",
            "A3.6k", "Predicting single replacement products", "Hard", 95,
        ),
        (
            "Lavoisier's law of conservation of mass states that in a closed system",
            "the total mass of reactants equals the total mass of products",
            ["mass is always lost as heat energy", "atoms can be created during chemical reactions", "the number of molecules always increases"],
            "Atoms are rearranged in chemical reactions but not created or destroyed.",
            "Students think mass decreases in all reactions because gases escape.",
            "A3.7k", "Stating the law of conservation of mass", "Easy", 60,
        ),
        (
            "One mole of any substance contains approximately",
            "$6.02 \\times 10^{23}$ representative particles",
            ["$6.02 \\times 10^{22}$ atoms only for gases", "one gram of that substance always", "Avogadro's number of grams"],
            "The mole links macroscopic mass to particle count via Avogadro's number.",
            "Students confuse moles with grams or misremember the exponent.",
            "A3.8k", "Defining the mole and Avogadro's number", "Easy", 60,
        ),
        (
            "In the balanced equation $N_2 + 3H_2 \\rightarrow 2NH_3$, the mole ratio of H$_2$ to NH$_3$ is",
            "3 : 2",
            ["1 : 2", "3 : 1", "2 : 3"],
            "Coefficients show 3 mol H$_2$ produce 2 mol NH$_3$.",
            "Students invert the ratio or use subscripts instead of coefficients.",
            "A3.7k", "Interpreting mole ratios from balanced equations", "Medium", 80,
        ),
        (
            "Industrial production of ammonia via the Haber process is significant to society because ammonia is used to",
            "manufacture fertilizers that support global food production",
            ["eliminate all nitrogen from the atmosphere", "replace all ionic compounds in medicine", "produce noble gases for lighting only"],
            "Ammonia is a key feedstock for nitrogen-based fertilizers.",
            "Students select unrelated or ecologically impossible applications.",
            "A3.1k", "Identifying societal importance of chemical reactions", "Medium", 70,
        ),
        (
            "A student analyzes lab data showing mass increased when magnesium ribbon was burned in a crucible with the lid on. "
            "The best interpretation is that",
            "oxygen from air combined with magnesium to form magnesium oxide",
            ["atoms were created during heating", "the balance measured neutron mass only", "magnesium decomposed into lighter elements"],
            "Mass gain in a closed system indicates reactant mass (O$_2$) was added from the air.",
            "Students think burning always decreases mass because ash looks smaller.",
            "A1.3s", "Interpreting mass change in combustion experiments", "Hard", 90,
        ),
        (
            "When communicating lab results about an exothermic reaction, a student should include",
            "observed temperature increase, balanced equation, and safety precautions used",
            ["only the final colour with no equation", "personal opinions unrelated to data", "a list of unrelated physical changes from other units"],
            "Scientific communication ties observations, symbolic representations, and methodology together.",
            "Students report isolated facts without connecting evidence to conclusions.",
            "A1.4s", "Communicating chemical investigation findings", "Medium", 75,
        ),
        (
            "A class discusses whether biodegradable plastics reduce long-term landfill waste. "
            "This discussion best connects chemistry to",
            "science, technology, and society (STS) decision making",
            ["memorizing polyatomic ion lists only", "naming molecular compounds without context", "recalling atomic model history dates exclusively"],
            "STS outcomes link chemical knowledge to societal and environmental choices.",
            "Students treat chemistry as isolated from real-world consequences.",
            "A1.4s", "Connecting chemistry concepts to societal issues", "Easy", 65,
        ),
    ])

    # --- Numerical response (moles, molar mass, stoichiometry) ---
    q += [
        nr(
            "What is the molar mass of CO$_2$ in g/mol? Use C = 12 g/mol and O = 16 g/mol. "
            "Express your answer as a whole number.",
            "44",
            "Molar mass = 12 + 2(16) = 44 g/mol.",
            "Students add only one oxygen atom or use molecular mass of CO instead.",
            topic=TOPIC, outcome_code="A3.9k",
            skill_tested="Calculating molar mass of a molecular compound",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        nr(
            "What is the molar mass of NaCl in g/mol? Use Na = 23 g/mol and Cl = 35.5 g/mol. "
            "Express your answer to one decimal place.",
            "58.5",
            "Molar mass = 23 + 35.5 = 58.5 g/mol.",
            "Students forget to add both atomic masses.",
            topic=TOPIC, outcome_code="A3.9k",
            skill_tested="Calculating molar mass of an ionic compound",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        nr(
            "How many moles are in 36.0 g of water (H$_2$O)? "
            "Use molar mass H$_2$O = 18.0 g/mol. Express your answer to one decimal place.",
            "2.0",
            "Moles = mass / molar mass = 36.0 / 18.0 = 2.0 mol.",
            "Students multiply mass by molar mass instead of dividing.",
            topic=TOPIC, outcome_code="A3.9k",
            skill_tested="Converting mass to moles",
            difficulty="Easy", estimated_time_seconds=70,
        ),
        nr(
            "How many moles are in 12.0 g of carbon? Use molar mass C = 12.0 g/mol. "
            "Express your answer to one decimal place.",
            "1.0",
            "Moles = 12.0 / 12.0 = 1.0 mol.",
            "Students report grams instead of moles.",
            topic=TOPIC, outcome_code="A3.9k",
            skill_tested="Converting element mass to moles",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        nr(
            "What mass of NaCl is required to obtain 0.50 mol? Use molar mass NaCl = 58.5 g/mol. "
            "Express your answer to one decimal place in grams.",
            "29.3",
            "Mass = moles × molar mass = 0.50 × 58.5 = 29.25 ≈ 29.3 g.",
            "Students divide instead of multiply, or round incorrectly.",
            topic=TOPIC, outcome_code="A3.9k",
            skill_tested="Converting moles to mass",
            difficulty="Medium", estimated_time_seconds=80,
        ),
        nr(
            "How many moles of O atoms are in 2.0 mol of CO$_2$? "
            "Express your answer to one decimal place.",
            "4.0",
            "Each CO$_2$ contains 2 O atoms; 2.0 mol × 2 = 4.0 mol O atoms.",
            "Students report 2.0 mol by ignoring the subscript on oxygen.",
            topic=TOPIC, outcome_code="A3.7k",
            skill_tested="Determining moles of atoms from formula moles",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        nr(
            "A sample contains $3.01 \\times 10^{23}$ molecules of H$_2$O. "
            "How many moles of H$_2$O is this? Use Avogadro's number $6.02 \\times 10^{23}$ mol$^{-1}$. "
            "Express your answer to one decimal place.",
            "0.5",
            "Moles = particles / Avogadro's number = $3.01 \\times 10^{23} / 6.02 \\times 10^{23} = 0.5$ mol.",
            "Students multiply by Avogadro's number instead of dividing.",
            topic=TOPIC, outcome_code="A3.8k",
            skill_tested="Converting particle count to moles",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        nr(
            "How many moles are in $1.204 \\times 10^{24}$ molecules of CO$_2$? "
            "Use Avogadro's number $6.02 \\times 10^{23}$ mol$^{-1}$. Express your answer to one decimal place.",
            "2.0",
            "Moles = $1.204 \\times 10^{24} / 6.02 \\times 10^{23} = 2.0$ mol.",
            "Students multiply by Avogadro's number instead of dividing.",
            topic=TOPIC, outcome_code="A3.8k",
            skill_tested="Converting molecule count to moles",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        nr(
            "What is the molar mass of Ca(OH)$_2$ in g/mol? Use Ca = 40 g/mol, O = 16 g/mol, H = 1 g/mol. "
            "Express your answer as a whole number.",
            "74",
            "Molar mass = 40 + 2(16 + 1) = 40 + 34 = 74 g/mol.",
            "Students forget to multiply the OH group by 2.",
            topic=TOPIC, outcome_code="A3.9k",
            skill_tested="Calculating molar mass with parentheses in formula",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        nr(
            "According to $2H_2 + O_2 \\rightarrow 2H_2O$, how many moles of H$_2$O are produced from 4.0 mol of H$_2$? "
            "Express your answer to one decimal place.",
            "4.0",
            "Mole ratio H$_2$ : H$_2$O is 2 : 2 (or 1 : 1); 4.0 mol H$_2$ yields 4.0 mol H$_2$O.",
            "Students use a 2 : 1 ratio from subscripts instead of balanced coefficients.",
            topic=TOPIC, outcome_code="A3.7k",
            skill_tested="Using mole ratios from balanced equations",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        nr(
            "According to $N_2 + 3H_2 \\rightarrow 2NH_3$, how many moles of H$_2$ are needed to produce 2.0 mol of NH$_3$? "
            "Express your answer to one decimal place.",
            "3.0",
            "From coefficients, 2 mol NH$_3$ requires 3 mol H$_2$.",
            "Students use a 1 : 1 ratio ignoring the coefficient of 3 on H$_2$.",
            topic=TOPIC, outcome_code="A3.7k",
            skill_tested="Calculating required reactant moles from products",
            difficulty="Hard", estimated_time_seconds=100,
        ),
        nr(
            "What is the molar mass of (NH$_4$)$_2$SO$_4$ in g/mol? "
            "Use N = 14, H = 1, S = 32, O = 16. Express your answer as a whole number.",
            "132",
            "Molar mass = 2(14 + 4) + 32 + 4(16) = 36 + 32 + 64 = 132 g/mol.",
            "Students forget to multiply the ammonium group by 2.",
            topic=TOPIC, outcome_code="A3.9k",
            skill_tested="Calculating molar mass with polyatomic ions in formula",
            difficulty="Hard", estimated_time_seconds=110,
        ),
    ]

    # --- Additional mixed questions to reach ~70 ---
    q += _batch_mc([
        (
            "Which model of the atom first introduced the concept of a nucleus?",
            "Rutherford's nuclear model",
            ["Dalton's solid sphere model", "Thomson's plum pudding model", "Bohr's planetary model only without a nucleus"],
            "Rutherford concluded atoms have a small, dense, positive nucleus.",
            "Students credit Bohr with discovering the nucleus rather than refining electron placement.",
            "A1.2k", "Matching atomic models to key features", "Easy", 60,
        ),
        (
            "Neon (Ne) is unreactive mainly because its atoms have",
            "a full valence shell of electrons",
            ["no neutrons in the nucleus", "the largest atomic radius on the periodic table", "only one electron total"],
            "Noble gases have stable full outer shells, making them chemically inert under normal conditions.",
            "Students think noble gases lack electrons or protons.",
            "A1.3k", "Explaining noble gas chemical inactivity", "Medium", 70,
        ),
        (
            "The ion formed when a chlorine atom gains one electron is",
            "Cl$^-$",
            ["Cl$^+$", "Cl$_2$", "Cl$^{2-}$"],
            "Chlorine (group 17) gains one electron to achieve a stable octet, forming Cl$^-$.",
            "Students think non-metals lose electrons to form positive ions.",
            "A2.1k", "Predicting ion charge from group number", "Easy", 60,
        ),
        (
            "Which pair represents a metal and non-metal likely to form an ionic compound?",
            "sodium and chlorine",
            ["oxygen and nitrogen", "carbon and hydrogen", "chlorine and bromine"],
            "Metal + non-metal combinations typically form ionic compounds via electron transfer.",
            "Students select two non-metals that form molecular compounds.",
            "A2.1k", "Identifying ionic bond element pairs", "Easy", 55,
        ),
        (
            "The Stock system name for CuO is",
            "copper(II) oxide",
            ["copper(I) oxide", "copper oxide(II)", "cupric oxide only without Roman numeral"],
            "Oxygen is O$^{2-}$, so copper must be Cu$^{2+}$ — copper(II) oxide.",
            "Students assign the wrong Roman numeral for the metal ion.",
            "A2.2k", "Naming metal oxides with Roman numerals", "Medium", 75,
        ),
        (
            "CO is named using IUPAC prefix rules as",
            "carbon monoxide",
            ["carbon oxide", "monocarbon dioxide", "carbon(II) oxide"],
            "The prefix mono- (often shortened to none for first element) and -ide apply to CO.",
            "Students apply ionic Roman numeral naming to molecular CO.",
            "A2.3k", "Naming simple diatomic molecular compounds", "Easy", 55,
        ),
        (
            "An aqueous solution of an acid turns blue litmus paper",
            "red",
            ["blue (no change)", "green always", "purple regardless of pH"],
            "Acids turn blue litmus red; bases turn red litmus blue.",
            "Students reverse the litmus colour change rule.",
            "A2.4k", "Using litmus to identify acids", "Easy", 50,
        ),
        (
            "Which compound is molecular rather than ionic?",
            "CH$_4$",
            ["MgCl$_2$", "K$_2$O", "LiF"],
            "CH$_4$ (methane) is formed by covalent sharing between non-metals.",
            "Students choose ionic compounds containing metals.",
            "A2.6k", "Classifying compounds as molecular or ionic", "Easy", 55,
        ),
        (
            "The nitrite ion has the formula",
            "NO$_2^-$",
            ["NO$_3^-$", "N$^{3-}$", "NO$^-$"],
            "Nitrite is NO$_2^-$; nitrate is NO$_3^-$.",
            "Students swap nitrite and nitrate formulas.",
            "A2.7k", "Distinguishing nitrite from nitrate", "Easy", 55,
        ),
        (
            "Pharmaceutical companies must follow strict protocols when synthesizing new drugs because",
            "incorrect compounds can be ineffective or harmful to patients",
            ["all ionic compounds are automatically safe", "molecular compounds cannot enter the bloodstream", "chemical naming rules prevent all toxic effects"],
            "Accurate synthesis and testing are essential when compounds affect human health.",
            "Students think nomenclature rules alone guarantee safety.",
            "A2.1sts", "Evaluating chemistry in pharmaceutical development", "Medium", 75,
        ),
        (
            "A precipitate forming when two clear solutions are mixed is evidence of",
            "a chemical change producing an insoluble product",
            ["a physical mixture with no new substance", "only a temperature decrease always", "evaporation of the solvent exclusively"],
            "An insoluble solid (precipitate) indicates a new substance has formed in solution.",
            "Students think precipitates are undissolved reactants unchanged chemically.",
            "A3.1k", "Recognizing precipitate formation as chemical evidence", "Easy", 55,
        ),
        (
            "Photosynthesis overall is classified as",
            "endothermic",
            ["exothermic", "a nuclear reaction", "a physical phase change only"],
            "Photosynthesis stores solar energy in chemical bonds — net energy absorption.",
            "Students confuse photosynthesis with respiration energy flow.",
            "A3.2k", "Classifying photosynthesis energy change", "Medium", 70,
        ),
        (
            "Balancing the equation ___ Fe + ___ O$_2$ $\\rightarrow$ ___ Fe$_2$O$_3$ requires coefficients of",
            "4, 3, 2 respectively",
            ["2, 1, 1", "1, 1, 1", "2, 3, 2 respectively"],
            "4Fe + 3O$_2$ $\\rightarrow$ 2Fe$_2$O$_3$ balances Fe and O atoms.",
            "Students balance only one element and leave oxygen unbalanced.",
            "A3.5k", "Balancing combustion of iron equation", "Hard", 100,
        ),
        (
            "Predict the products of the decomposition of mercury(II) oxide with heat.",
            "mercury metal and oxygen gas",
            ["mercury(II) chloride and water", "mercury oxide and hydrogen", "no products because oxides never decompose"],
            "Heating HgO decomposes it to Hg(l) and O$_2$(g).",
            "Students predict replacement products instead of decomposition products.",
            "A3.6k", "Predicting decomposition products of a metal oxide", "Medium", 80,
        ),
        (
            "In a closed flask, 16 g of O$_2$ gas reacts completely with excess hydrogen to form water. "
            "The mass of water produced is closest to",
            "18 g",
            ["8 g", "32 g", "2 g"],
            "16 g O$_2$ = 0.5 mol; from $2H_2 + O_2 \\rightarrow 2H_2O$, 0.5 mol O$_2$ yields 1.0 mol H$_2$O = 18 g.",
            "Students forget the 2:1 mole ratio between O$_2$ and H$_2$O from the balanced equation.",
            "A3.7k", "Applying conservation of mass to reaction products", "Hard", 105,
        ),
    ])

    return q
