"""Unit D: Energy Flow in Global Systems — original Science 10 questions."""

from .helpers import mc, nr

TOPIC = "Energy Flow in Global Systems"


def questions():
    q = [
        # --- D1: Solar energy, albedo, greenhouse effect, ozone ---
        mc(
            "The primary source of energy driving Earth's weather, climate, and life processes is",
            "electromagnetic radiation from the Sun",
            ["geothermal heat from Earth's core only", "chemical energy stored in fossil fuels only", "nuclear fusion occurring in the atmosphere"],
            "Solar radiation provides the continuous energy input that powers atmospheric circulation, the water cycle, and photosynthesis.",
            "Geothermal and fossil fuels are secondary or stored energy; the Sun is the main external source.",
            topic=TOPIC, outcome_code="D1.1k",
            skill_tested="Identifying the Sun as Earth's primary energy source",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "Most of the Sun's energy reaching Earth arrives as",
            "visible and near-infrared radiation",
            ["gamma rays and X-rays only", "sound waves through the vacuum of space", "direct conduction through solid rock"],
            "The solar spectrum peaks in visible light, with significant near-infrared; high-energy radiation is largely filtered.",
            "Space cannot transmit sound; most solar energy is EM radiation, not conduction.",
            topic=TOPIC, outcome_code="D1.1k",
            skill_tested="Describing the form of incoming solar energy",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "In Earth's energy budget, incoming solar radiation is balanced over time by",
            "outgoing longwave (infrared) radiation to space",
            ["complete storage of all energy in ocean sediments permanently", "conversion of all sunlight into visible light reflected unchanged", "elimination of all heat transfer from the surface"],
            "Earth absorbs shortwave solar energy and radiates longwave infrared back to space at approximately the same average rate.",
            "Earth must radiate energy outward; it does not store all incoming solar energy indefinitely.",
            topic=TOPIC, outcome_code="D1.2k",
            skill_tested="Describing Earth's radiative energy balance",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "Clouds and ice caps affect Earth's energy budget mainly by",
            "reflecting a portion of incoming solar radiation back to space",
            ["absorbing all ultraviolet radiation and converting it to mass", "preventing any infrared radiation from leaving Earth", "generating solar energy through nuclear fission"],
            "High-albedo surfaces such as clouds and snow reflect shortwave radiation, reducing energy absorbed at the surface.",
            "Reflection reduces absorption; clouds do not create solar energy.",
            topic=TOPIC, outcome_code="D1.2k",
            skill_tested="Explaining how clouds and ice affect solar energy distribution",
            difficulty="Medium", estimated_time_seconds=70,
        ),
        mc(
            "Albedo is defined as the",
            "fraction of incoming radiation reflected by a surface",
            ["total amount of heat stored in an ocean current", "rate of evaporation from a tropical rainforest", "concentration of carbon dioxide in the troposphere"],
            "Albedo compares reflected radiation to incoming radiation for a surface or planet.",
            "Albedo is a reflectivity ratio, not a heat storage or gas concentration measure.",
            topic=TOPIC, outcome_code="D1.3k",
            skill_tested="Defining albedo",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "Fresh snow has a higher albedo than a dark asphalt road, which means snow",
            "reflects a greater percentage of incoming solar radiation",
            ["absorbs more solar energy and heats up faster always", "emits no infrared radiation at any temperature", "blocks all greenhouse gases from entering the atmosphere"],
            "Higher albedo means more reflection and less absorption of shortwave solar energy.",
            "High albedo surfaces reflect more; they do not absorb more solar energy.",
            topic=TOPIC, outcome_code="D1.3k",
            skill_tested="Comparing albedo effects on surface energy absorption",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "The natural greenhouse effect helps maintain Earth's habitability by",
            "trapping some outgoing infrared radiation and warming the lower atmosphere",
            ["blocking all solar radiation from reaching the surface", "eliminating convection in the troposphere entirely", "preventing water from evaporating from oceans"],
            "Greenhouse gases absorb and re-emit infrared radiation, reducing net energy loss to space and keeping surface temperatures warmer than they would otherwise be.",
            "The greenhouse effect involves infrared retention, not blocking all sunlight.",
            topic=TOPIC, outcome_code="D1.4k",
            skill_tested="Describing the natural greenhouse effect",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "Which gas is a major anthropogenic contributor to enhanced greenhouse warming?",
            "carbon dioxide (CO₂) from fossil fuel combustion",
            ["nitrogen (N₂) from the breakdown of inert rock only", "argon (Ar) released by lightning exclusively", "oxygen (O₂) produced by photosynthesis alone"],
            "CO₂ from burning coal, oil, and gas increases atmospheric concentration and enhances the greenhouse effect.",
            "N₂ and Ar are not significant greenhouse gases; O₂ increase from photosynthesis is not the main warming driver.",
            topic=TOPIC, outcome_code="D1.4k",
            skill_tested="Identifying anthropogenic greenhouse gas sources",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Methane (CH₄) is considered a potent greenhouse gas because it",
            "absorbs outgoing infrared radiation effectively despite lower atmospheric concentration than CO₂",
            ["reflects all incoming ultraviolet radiation back to space", "replaces oxygen in the stratosphere entirely", "has no interaction with electromagnetic radiation"],
            "Methane molecules absorb infrared wavelengths strongly; per molecule it has a higher warming potential than CO₂ over short time scales.",
            "Greenhouse gases absorb infrared, not reflect UV; methane does interact with radiation.",
            topic=TOPIC, outcome_code="D1.4k",
            skill_tested="Explaining methane's role in the greenhouse effect",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "The ozone layer in the stratosphere protects living organisms primarily by",
            "absorbing harmful ultraviolet (UV) radiation from the Sun",
            ["reflecting all visible light away from Earth", "producing oxygen through nuclear fusion", "preventing all infrared radiation from leaving Earth"],
            "Ozone (O₃) absorbs UV-B and UV-C, reducing DNA damage and other harmful effects at the surface.",
            "Ozone targets UV radiation, not all visible light or outgoing infrared.",
            topic=TOPIC, outcome_code="D1.5k",
            skill_tested="Describing ozone layer protective function",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Chlorofluorocarbons (CFCs) damaged the ozone layer because they",
            "release chlorine atoms in the stratosphere that catalytically destroy ozone molecules",
            ["directly reflect all solar radiation into space", "increase Earth's albedo by forming permanent cloud cover only", "convert ozone into visible light with no chemical change"],
            "UV radiation breaks down CFCs, freeing chlorine radicals that repeatedly destroy O₃ in catalytic cycles.",
            "CFC harm is chemical destruction of ozone, not simple reflection.",
            topic=TOPIC, outcome_code="D1.5k",
            skill_tested="Explaining CFC impact on stratospheric ozone",
            difficulty="Medium", estimated_time_seconds=80,
        ),
        mc(
            "Satellite monitoring of atmospheric gases illustrates that scientific understanding of climate is",
            "built from collected evidence and revised as new data become available",
            ["fixed permanently after a single experiment", "based only on opinions without measurement", "unrelated to technology or international cooperation"],
            "Modern climate science relies on long-term instrumental records and satellites, reflecting how science uses evidence over time.",
            "Scientific knowledge in this area evolves with better data and models.",
            topic=TOPIC, outcome_code="D1.1sts",
            skill_tested="Relating satellite monitoring to nature of scientific knowledge",
            difficulty="Easy", estimated_time_seconds=65,
        ),

        # --- D2: Weather vs climate, factors, climatographs, biomes ---
        mc(
            "Weather differs from climate because weather describes",
            "short-term atmospheric conditions at a specific time and place",
            ["average conditions over 30 years or more globally", "only the type of biome found at a latitude", "the total solar energy received by Earth in a year"],
            "Weather is immediate and local; climate is the long-term pattern of weather in a region.",
            "Long-term averages define climate, not weather.",
            topic=TOPIC, outcome_code="D2.1k",
            skill_tested="Distinguishing weather from climate",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "A region's climate is best described by",
            "long-term averages and patterns of temperature and precipitation",
            ["the temperature on a single winter day only", "the wind direction during one thunderstorm", "the daily cloud cover for one week only"],
            "Climate summaries use decades of data to characterize typical and extreme conditions.",
            "Single-day or single-event data describe weather, not climate.",
            topic=TOPIC, outcome_code="D2.1k",
            skill_tested="Defining climate using long-term data",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "Cities at the same latitude but different elevations often have different climates because",
            "temperature generally decreases with increasing altitude",
            ["solar radiation cannot reach mountainous areas", "precipitation never occurs above sea level", "albedo is zero at all mountain summits"],
            "Higher elevation means thinner atmosphere and lower average temperatures, altering biome and climate type.",
            "Mountains still receive solar radiation; elevation mainly changes temperature and precipitation patterns.",
            topic=TOPIC, outcome_code="D2.2k",
            skill_tested="Explaining altitude as a climate factor",
            difficulty="Medium", estimated_time_seconds=70,
        ),
        mc(
            "Ocean currents such as the Gulf Stream can affect coastal climate by",
            "transporting warm or cold water that heats or cools adjacent air masses",
            ["blocking all solar radiation from reaching the coast", "eliminating evaporation from the ocean surface", "preventing any seasonal temperature change"],
            "Currents redistribute ocean heat, moderating or altering temperature and humidity of nearby land.",
            "Currents transfer thermal energy; they do not stop solar input or evaporation entirely.",
            topic=TOPIC, outcome_code="D2.2k",
            skill_tested="Explaining ocean current influence on regional climate",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "A climatograph displays",
            "average monthly temperature and precipitation for a location",
            ["the daily wind speed for one week only", "the chemical composition of soil horizons", "the food web of a single pond ecosystem"],
            "Climatographs combine temperature (usually line graph) and precipitation (usually bars) by month.",
            "Climatographs show climate variables over months, not soil chemistry or food webs.",
            topic=TOPIC, outcome_code="D2.3k",
            skill_tested="Identifying climatograph variables",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "On a climatograph, a location with hot, wet summers and cold, dry winters would show",
            "high precipitation bars and high temperature line in summer, low precipitation and low temperature in winter",
            ["identical temperature and precipitation every month", "zero precipitation in all twelve months", "temperature decreasing every month without variation"],
            "Seasonal climate patterns appear as repeating monthly differences in both temperature and precipitation.",
            "Seasonal climates vary by month; flat lines and bars indicate little seasonal change.",
            topic=TOPIC, outcome_code="D2.3k",
            skill_tested="Interpreting seasonal patterns on a climatograph",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "A climatograph with little monthly temperature variation and heavy rainfall every month is typical of",
            "equatorial tropical rainforest climate",
            ["polar desert climate", "mid-latitude steppe climate", "high-latitude tundra climate"],
            "Tropical rainforests near the equator stay warm year-round with consistently high precipitation.",
            "Polar and tundra climates have low temperatures; steppe climates are drier.",
            topic=TOPIC, outcome_code="D2.3k",
            skill_tested="Matching climatograph patterns to climate types",
            difficulty="Medium", estimated_time_seconds=80,
        ),
        mc(
            "Biomes are large regions classified mainly by",
            "climate and characteristic vegetation (and associated animal life)",
            ["the age of bedrock only", "the political borders of countries", "the phase of the Moon during winter"],
            "Climate (temperature and precipitation) largely determines which biome develops in a region.",
            "Biomes are ecological, not political or geological age categories.",
            topic=TOPIC, outcome_code="D2.4k",
            skill_tested="Defining biome classification basis",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "As latitude increases from the equator toward the poles, terrestrial biomes generally shift from",
            "tropical forest toward temperate forest, grassland, and tundra",
            ["desert toward tropical rainforest only", "tundra toward equatorial savanna without change in temperature", "marine biome toward desert with no precipitation change"],
            "Lower average solar angle and cooler temperatures at high latitudes support different biome types than the equator.",
            "Biome zones change with latitude due to changing climate, not randomly.",
            topic=TOPIC, outcome_code="D2.4k",
            skill_tested="Relating latitude to biome distribution",
            difficulty="Medium", estimated_time_seconds=70,
        ),
        mc(
            "The boreal forest (taiga) biome is characterized by",
            "long, cold winters and coniferous trees such as spruce and pine",
            ["year-round temperatures above 25 °C and cacti", "no trees and permanently frozen soil only with no summer thaw", "coral reefs and mangrove swamps"],
            "Taiga occurs in subarctic regions with short summers and needle-leaf conifers adapted to cold.",
            "Hot deserts, pure ice sheets, and coral reefs belong to other biomes.",
            topic=TOPIC, outcome_code="D2.5k",
            skill_tested="Identifying boreal forest characteristics",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Grassland biomes typically experience",
            "moderate rainfall insufficient to support continuous forest cover",
            ["constant heavy rainfall supporting tropical rainforest trees", "no precipitation and no growing season at any time", "permanently frozen ground with no grasses"],
            "Grasslands occupy a precipitation range between desert and forest, supporting grasses and few trees.",
            "Grasslands receive enough rain for grasses but not dense forests.",
            topic=TOPIC, outcome_code="D2.5k",
            skill_tested="Describing grassland climate and vegetation",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Desert biomes are defined primarily by",
            "low annual precipitation and adaptations for water conservation",
            ["continuous snow cover and permafrost", "constant daily rainfall throughout the year", "submerged saline conditions with kelp forests"],
            "Deserts receive very little precipitation; plants and animals show drought adaptations.",
            "Snow, constant rain, and kelp forests describe other biomes.",
            topic=TOPIC, outcome_code="D2.5k",
            skill_tested="Identifying desert biome defining features",
            difficulty="Easy", estimated_time_seconds=55,
        ),
        mc(
            "The open-ocean zone of a marine biome is characterized by",
            "deep water far from shore with plankton and nekton adapted to open water",
            ["daily exposure to air at low tide only", "freshwater with no dissolved salts", "permanently frozen soil and low shrubs"],
            "Pelagic (open-ocean) life includes drifting plankton and swimming organisms in saline water.",
            "Intertidal, freshwater, and tundra describe different environments.",
            topic=TOPIC, outcome_code="D2.6k",
            skill_tested="Describing open-ocean marine biome features",
            difficulty="Medium", estimated_time_seconds=70,
        ),
        mc(
            "Estuaries where freshwater rivers meet the ocean are important aquatic biomes because they",
            "provide nutrient-rich nursery habitat with mixed salinity conditions",
            ["contain no life due to saltwater and freshwater mixing", "remain frozen year-round at all latitudes", "lack any connection to solar energy or food webs"],
            "Estuaries support high productivity and serve as breeding grounds for many species.",
            "Estuaries are biologically rich, not lifeless or permanently frozen.",
            topic=TOPIC, outcome_code="D2.6k",
            skill_tested="Explaining ecological importance of estuaries",
            difficulty="Medium", estimated_time_seconds=70,
        ),

        # --- D3: Climate change evidence, causes, effects, responses ---
        mc(
            "Ice core data provide evidence of past climate change because trapped bubbles contain",
            "samples of ancient atmospheric gases such as CO₂ and methane",
            ["only modern air from the drilling process", "fossilized plants from the current century only", "pure oxygen with no other gases ever present"],
            "Layered ice preserves air from when each layer formed, allowing comparison of greenhouse gas levels over millennia.",
            "Ice cores contain trapped ancient air, not only contamination from drilling.",
            topic=TOPIC, outcome_code="D3.1k",
            skill_tested="Interpreting ice cores as climate change evidence",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "Global mean sea level has risen in recent decades partly because",
            "thermal expansion of warming ocean water and melting land ice add water to oceans",
            ["Earth's total amount of water is increasing from nuclear reactions in the sea", "all rivers have stopped flowing into the oceans", "evaporation has permanently removed all ocean water"],
            "Warming increases water volume and melts glaciers and ice sheets, raising sea level.",
            "Sea level rise involves existing water expanding and ice melting, not creating new water.",
            topic=TOPIC, outcome_code="D3.1k",
            skill_tested="Identifying evidence and mechanisms of sea level rise",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "Volcanic eruptions can cause short-term cooling by",
            "injecting aerosols and ash that reflect incoming solar radiation",
            ["adding large amounts of stratospheric ozone instantly", "eliminating all greenhouse gases permanently", "increasing Earth's albedo to exactly 1.0 forever"],
            "Volcanic aerosols reflect sunlight temporarily; effects usually last months to a few years, unlike long-term CO₂ warming.",
            "Volcanic cooling is temporary reflection, not permanent removal of all greenhouse gases.",
            topic=TOPIC, outcome_code="D3.2k",
            skill_tested="Distinguishing natural volcanic cooling from long-term warming",
            difficulty="Medium", estimated_time_seconds=80,
        ),
        mc(
            "Burning fossil fuels contributes to climate change mainly by",
            "increasing atmospheric CO₂ concentration and enhancing the greenhouse effect",
            ["decreasing atmospheric nitrogen to zero", "reflecting all incoming solar radiation with ash only", "creating new water molecules that cannot absorb heat"],
            "Fossil fuel combustion releases stored carbon as CO₂, a long-lived greenhouse gas.",
            "The main issue is CO₂ accumulation, not nitrogen loss or total solar reflection.",
            topic=TOPIC, outcome_code="D3.2k",
            skill_tested="Linking fossil fuel use to anthropogenic warming",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "One predicted effect of continued global warming in Alberta includes",
            "more frequent extreme weather events and shifting ecosystems",
            ["complete elimination of all winter seasons immediately", "permanent freezing of all prairie farmland year-round", "removal of all greenhouse gases from the atmosphere naturally within days"],
            "Climate models project hotter extremes, altered precipitation, and biome shifts; changes occur over years to decades.",
            "Extremes increase and patterns shift; instant permanent ice or instant gas removal is unrealistic.",
            topic=TOPIC, outcome_code="D3.3k",
            skill_tested="Describing regional climate change impacts",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "Ocean acidification linked to increased CO₂ affects marine ecosystems by",
            "lowering pH and reducing availability of carbonate ions for shell-building organisms",
            ["increasing pH and strengthening all coral reefs without limit", "eliminating all dissolved gases from seawater", "preventing any photosynthesis by phytoplankton globally"],
            "CO₂ dissolves to form carbonic acid, harming calcifying organisms such as corals and some plankton.",
            "Acidification lowers pH; it does not strengthen shells or stop all photosynthesis.",
            topic=TOPIC, outcome_code="D3.3k",
            skill_tested="Explaining ocean acidification consequences",
            difficulty="Medium", estimated_time_seconds=80,
        ),
        mc(
            "Mitigation of climate change refers to actions that",
            "reduce greenhouse gas emissions or enhance carbon sinks",
            ["only adapt infrastructure after damage has occurred", "ignore atmospheric gases and focus solely on weather forecasts", "increase fossil fuel use to reflect sunlight"],
            "Mitigation addresses causes (e.g., renewable energy, reforestation); adaptation handles impacts.",
            "Adaptation is different from mitigation; mitigation reduces emissions or captures carbon.",
            topic=TOPIC, outcome_code="D3.4k",
            skill_tested="Defining climate change mitigation strategies",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Planting drought-resistant crop varieties in Alberta is an example of",
            "adaptation to expected climate change impacts",
            ["mitigation that removes CO₂ from the atmosphere directly", "evidence that climate never changes naturally", "elimination of the greenhouse effect entirely"],
            "Adaptation adjusts practices to cope with new conditions without necessarily lowering emissions.",
            "Crop choice adapts to change; it is not the same as emission reduction (mitigation).",
            topic=TOPIC, outcome_code="D3.4k",
            skill_tested="Distinguishing adaptation from mitigation",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "International climate agreements reflect the STS idea that addressing global warming requires",
            "cooperation among governments, scientists, and citizens using shared data",
            ["decisions by one person without any evidence", "ignoring developing nations' energy needs entirely", "avoiding all measurement of atmospheric gases"],
            "Climate change is global; policy responses involve international negotiation and scientific input.",
            "Effective response needs collaboration and evidence, not isolation or ignoring data.",
            topic=TOPIC, outcome_code="D3.1sts",
            skill_tested="Analyzing societal response to climate change",
            difficulty="Easy", estimated_time_seconds=65,
        ),

        # --- D4: Heat, specific heat, energy transfer, Q=mcΔt ---
        mc(
            "Temperature and heat differ because temperature measures",
            "average kinetic energy of particles, while heat is energy transferred due to a temperature difference",
            ["total mass of an object only", "the colour of radiation emitted by a surface only", "the amount of oxygen in the atmosphere"],
            "Temperature is a property indicating particle motion; heat (thermal energy transfer) flows from higher to lower temperature.",
            "Heat is energy in transit; temperature is not the same as total thermal energy.",
            topic=TOPIC, outcome_code="D4.1k",
            skill_tested="Distinguishing heat from temperature",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        mc(
            "Two objects at the same temperature may contain different amounts of thermal energy if they have",
            "different masses or different specific heat capacities",
            ["identical chemical formulas always", "the same colour and shape only", "zero kinetic energy in all particles"],
            "Thermal energy depends on mass, specific heat, and temperature: Q = mcΔT for a given change.",
            "Same temperature does not mean same total thermal energy for different masses or materials.",
            topic=TOPIC, outcome_code="D4.1k",
            skill_tested="Relating thermal energy to mass and material",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "Water has a high specific heat capacity, which means it",
            "absorbs or releases large amounts of energy with relatively small temperature changes",
            ["cannot store any thermal energy in oceans", "always boils at 0 °C at standard pressure", "transfers heat only by conduction, never by radiation"],
            "High c means more energy is needed per kilogram to change temperature, stabilizing coastal and global climates.",
            "High specific heat increases thermal storage and moderates temperature swings.",
            topic=TOPIC, outcome_code="D4.2k",
            skill_tested="Explaining significance of water's specific heat capacity",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "Sand heats up faster than water on a sunny day primarily because sand",
            "has a lower specific heat capacity than water",
            ["absorbs no solar radiation at all", "has a higher specific heat capacity than water", "cannot transfer energy by any mechanism"],
            "Lower c means temperature rises more quickly for the same energy input per kilogram.",
            "Sand heats faster due to lower specific heat, not because it absorbs no radiation.",
            topic=TOPIC, outcome_code="D4.2k",
            skill_tested="Comparing heating rates using specific heat capacity",
            difficulty="Easy", estimated_time_seconds=65,
        ),
        mc(
            "Energy transfer in the atmosphere that drives wind and storm systems includes",
            "radiation, conduction, and convection of thermal energy",
            ["only chemical bonds breaking in solid rock with no air movement", "transfer of matter without any energy change", "gravitational energy from the Moon stopping all air motion"],
            "Solar heating creates temperature differences; convection moves warm air and moisture, producing weather.",
            "Weather involves energy transfer in fluids (convection) and radiation from Sun and Earth.",
            topic=TOPIC, outcome_code="D4.4k",
            skill_tested="Identifying heat transfer mechanisms in the atmosphere",
            difficulty="Medium", estimated_time_seconds=70,
        ),
        mc(
            "When sunlight warms the ground, the air above it often rises because",
            "heated air expands, becomes less dense, and convection carries energy upward",
            ["cold air is always less dense than warm air", "conduction cannot occur in gases under any condition", "radiation stops once the surface is warmed"],
            "Convection transfers energy vertically in fluids when warm, low-density regions rise.",
            "Warm air is less dense; convection complements conduction and radiation.",
            topic=TOPIC, outcome_code="D4.5k",
            skill_tested="Explaining atmospheric convection from surface heating",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "In a closed system where no energy enters or leaves, if one part cools another part must warm so that",
            "total energy remains conserved",
            ["energy is created from nothing to balance temperatures", "all molecules stop moving permanently", "specific heat capacity becomes zero for all materials"],
            "Conservation of energy requires that energy lost by one component is gained by another in an isolated system.",
            "Energy cannot be created; it transfers between parts of the system.",
            topic=TOPIC, outcome_code="D4.6k",
            skill_tested="Applying conservation of energy in thermal systems",
            difficulty="Medium", estimated_time_seconds=75,
        ),
        mc(
            "Choosing lighter-coloured roofing in urban areas to reduce heat absorption is an example of applying",
            "scientific knowledge of albedo and energy transfer to community planning",
            ["only economic theory with no connection to physics", "biological classification of biomes only", "atomic structure of the nucleus exclusively"],
            "Cool-roof strategies use reflectivity (albedo) to lower building heat gain, linking science to societal choices.",
            "This STS application connects energy budget concepts to urban design.",
            topic=TOPIC, outcome_code="D4.1sts",
            skill_tested="Connecting energy transfer science to societal decisions",
            difficulty="Easy", estimated_time_seconds=65,
        ),

        # --- Numerical response: Q=mcΔt and percent values ---
        nr(
            "How much energy in joules is required to raise the temperature of 2.0 kg of water "
            "from 15 °C to 25 °C? Use c = 4200 J/(kg·°C) and Q = mcΔT. Record as an integer.",
            "84000",
            "ΔT = 25 − 15 = 10 °C. Q = mcΔT = 2.0 × 4200 × 10 = 84 000 J.",
            "Students forget to multiply by ΔT or use ΔT = 25 instead of 10.",
            topic=TOPIC, outcome_code="D4.3k",
            skill_tested="Calculating heat energy using Q = mcΔT",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        nr(
            "A 0.50 kg block of aluminum (c = 900 J/(kg·°C)) is heated from 20 °C to 60 °C. "
            "Using Q = mcΔT, what is Q in joules? Record as an integer.",
            "18000",
            "ΔT = 60 − 20 = 40 °C. Q = 0.50 × 900 × 40 = 18 000 J.",
            "Students use final temperature 60 instead of ΔT = 40.",
            topic=TOPIC, outcome_code="D1.2s",
            skill_tested="Applying Q = mcΔT to a metal sample",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        nr(
            "A lake absorbs 1.5 × 10⁶ J of solar energy. If 4.5 × 10⁵ J is reflected, "
            "what percentage of the incoming energy was absorbed? Record as an integer.",
            "70",
            "Absorbed = 1.5×10⁶ − 4.5×10⁵ = 1.05×10⁶ J. Percent absorbed = (1.05×10⁶ / 1.5×10⁶) × 100 = 70%.",
            "Students calculate reflected percentage (30%) instead of absorbed.",
            topic=TOPIC, outcome_code="D1.3s",
            skill_tested="Calculating percent of absorbed solar energy",
            difficulty="Medium", estimated_time_seconds=95,
        ),
        nr(
            "Earth's average albedo is about 0.30. What percentage of incoming solar radiation is reflected "
            "back to space? Record as an integer.",
            "30",
            "Albedo 0.30 means 30% of incoming radiation is reflected.",
            "Students multiply by 100 twice or report 0.30 instead of a percentage.",
            topic=TOPIC, outcome_code="D1.3s",
            skill_tested="Converting albedo to reflected percentage",
            difficulty="Easy", estimated_time_seconds=60,
        ),
        nr(
            "How many joules of energy are needed to warm 3.0 kg of water by 5.0 °C? "
            "Use c = 4200 J/(kg·°C). Record as an integer.",
            "63000",
            "Q = mcΔT = 3.0 × 4200 × 5.0 = 63 000 J.",
            "Students omit mass or use c = 4.2 instead of 4200.",
            topic=TOPIC, outcome_code="D1.4s",
            skill_tested="Calculating thermal energy for a water sample",
            difficulty="Medium", estimated_time_seconds=85,
        ),
        nr(
            "Atmospheric CO₂ rose from 280 ppm to 420 ppm since pre-industrial times. "
            "What is the percent increase relative to the original 280 ppm? "
            "Round to the nearest whole number and record as an integer.",
            "50",
            "Increase = 420 − 280 = 140 ppm. Percent increase = (140/280) × 100 = 50%.",
            "Students divide by 420 instead of the original 280 ppm value.",
            topic=TOPIC, outcome_code="D1.1s",
            skill_tested="Calculating percent increase in atmospheric CO₂",
            difficulty="Medium", estimated_time_seconds=90,
        ),
        nr(
            "A soil sample with mass 1.0 kg and c = 800 J/(kg·°C) releases 4000 J of heat while cooling. "
            "What is the temperature change ΔT in °C? Use Q = mcΔT. Record as an integer.",
            "5",
            "ΔT = Q/(mc) = 4000/(1.0 × 800) = 5 °C.",
            "Students multiply Q × m × c instead of solving for ΔT.",
            topic=TOPIC, outcome_code="D1.4s",
            skill_tested="Solving for temperature change using Q = mcΔT",
            difficulty="Medium", estimated_time_seconds=95,
        ),
    ]
    return q
